# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fault_Response.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Fault_response(object):
    def setupUi(self, Fault_response):
        Fault_response.setObjectName("Fault_response")
        Fault_response.resize(888, 700)
        self.centralwidget = QtWidgets.QWidget(Fault_response)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Transient = QtWidgets.QLabel(self.centralwidget)
        self.label_Transient.setGeometry(QtCore.QRect(10, 0, 871, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_Transient.setFont(font)
        self.label_Transient.setStyleSheet("background-color: rgb(38, 23, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_Transient.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Transient.setObjectName("label_Transient")
        self.frame_phase_display = QtWidgets.QFrame(self.centralwidget)
        self.frame_phase_display.setGeometry(QtCore.QRect(10, 40, 871, 651))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame_phase_display.setFont(font)
        self.frame_phase_display.setStyleSheet("\n"
"border: 2px solid darkorange;\n"
"border-radius:0px;\n"
"")
        self.frame_phase_display.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_phase_display.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_phase_display.setObjectName("frame_phase_display")
        self.pushButton_Discard = QtWidgets.QPushButton(self.frame_phase_display)
        self.pushButton_Discard.setGeometry(QtCore.QRect(300, 600, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Discard.setFont(font)
        self.pushButton_Discard.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Discard.setStyleSheet("QPushButton{background-color: rgb(219, 100, 17);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid red;\n"
"background-color: orange;\n"
"}\n"
"")
        self.pushButton_Discard.setObjectName("pushButton_Discard")
        self.pushButton_Save = QtWidgets.QPushButton(self.frame_phase_display)
        self.pushButton_Save.setGeometry(QtCore.QRect(470, 600, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Save.setStyleSheet("QPushButton{background-color: rgb(0, 153, 74);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid green;\n"
"background-color:lightgreen;\n"
"}\n"
"")
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.label_RailA_4 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_4.setGeometry(QtCore.QRect(10, 190, 161, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_4.setFont(font)
        self.label_RailA_4.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_4.setObjectName("label_RailA_4")
        self.label_RailA_5 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_5.setGeometry(QtCore.QRect(10, 230, 211, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_5.setFont(font)
        self.label_RailA_5.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_5.setObjectName("label_RailA_5")
        self.label_display_RailB = QtWidgets.QLabel(self.frame_phase_display)
        self.label_display_RailB.setGeometry(QtCore.QRect(400, 350, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_display_RailB.setFont(font)
        self.label_display_RailB.setStyleSheet("border: none;")
        self.label_display_RailB.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_display_RailB.setAlignment(QtCore.Qt.AlignCenter)
        self.label_display_RailB.setObjectName("label_display_RailB")
        self.label_display_RailA = QtWidgets.QLabel(self.frame_phase_display)
        self.label_display_RailA.setGeometry(QtCore.QRect(400, 120, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_display_RailA.setFont(font)
        self.label_display_RailA.setStyleSheet("border: none;")
        self.label_display_RailA.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_display_RailA.setAlignment(QtCore.Qt.AlignCenter)
        self.label_display_RailA.setObjectName("label_display_RailA")
        self.comboBox_over_current_response_railA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_over_current_response_railA.setGeometry(QtCore.QRect(250, 195, 190, 25))
        self.comboBox_over_current_response_railA.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_over_current_response_railA.setObjectName("comboBox_over_current_response_railA")
        self.comboBox_over_current_response_railA.addItem("")
        self.comboBox_over_current_response_railA.addItem("")
        self.comboBox_over_current_response_railA.addItem("")
        self.comboBox_over_current_response_railA.addItem("")
        self.groupBox = QtWidgets.QGroupBox(self.frame_phase_display)
        self.groupBox.setGeometry(QtCore.QRect(480, 30, 371, 31))
        self.groupBox.setStyleSheet("border:none;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.comboBox_over_current_retry_railA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_over_current_retry_railA.setGeometry(QtCore.QRect(460, 195, 115, 25))
        self.comboBox_over_current_retry_railA.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_over_current_retry_railA.setObjectName("comboBox_over_current_retry_railA")
        self.comboBox_over_current_retry_railA.addItem("")
        self.comboBox_over_current_retry_railA.addItem("")
        self.comboBox_over_current_retry_railA.addItem("")
        self.comboBox_over_current_retry_railA.addItem("")
        self.comboBox_over_current_retry_railA.addItem("")
        self.comboBox_over_current_retry_railA.addItem("")
        self.comboBox_over_current_retry_railA.addItem("")
        self.comboBox_over_current_retry_railA.addItem("")
        self.label_RailA_18 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_18.setGeometry(QtCore.QRect(290, 15, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_RailA_18.setFont(font)
        self.label_RailA_18.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_18.setObjectName("label_RailA_18")
        self.comboBox_over_current_delay_railA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_over_current_delay_railA.setGeometry(QtCore.QRect(590, 195, 270, 25))
        self.comboBox_over_current_delay_railA.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_over_current_delay_railA.setObjectName("comboBox_over_current_delay_railA")
        self.comboBox_over_current_delay_railA.addItem("")
        self.comboBox_over_current_delay_railA.addItem("")
        self.comboBox_over_current_delay_railA.addItem("")
        self.comboBox_over_current_delay_railA.addItem("")
        self.comboBox_over_current_delay_railA.addItem("")
        self.comboBox_over_current_delay_railA.addItem("")
        self.comboBox_over_current_delay_railA.addItem("")
        self.comboBox_over_current_delay_railA.addItem("")
        self.label_RailA_19 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_19.setGeometry(QtCore.QRect(470, 15, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_RailA_19.setFont(font)
        self.label_RailA_19.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_19.setObjectName("label_RailA_19")
        self.label_RailA_20 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_20.setGeometry(QtCore.QRect(590, 15, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_RailA_20.setFont(font)
        self.label_RailA_20.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_20.setObjectName("label_RailA_20")
        self.label_RailA_21 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_21.setGeometry(QtCore.QRect(220, 190, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_21.setFont(font)
        self.label_RailA_21.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RailA_21.setObjectName("label_RailA_21")
        self.comboBox_vout_over_voltage_response_railA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vout_over_voltage_response_railA.setGeometry(QtCore.QRect(250, 235, 190, 25))
        self.comboBox_vout_over_voltage_response_railA.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vout_over_voltage_response_railA.setObjectName("comboBox_vout_over_voltage_response_railA")
        self.comboBox_vout_over_voltage_response_railA.addItem("")
        self.comboBox_vout_over_voltage_response_railA.addItem("")
        self.comboBox_vout_over_voltage_response_railA.addItem("")
        self.comboBox_vout_over_voltage_delay_railA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vout_over_voltage_delay_railA.setGeometry(QtCore.QRect(590, 235, 270, 25))
        self.comboBox_vout_over_voltage_delay_railA.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vout_over_voltage_delay_railA.setObjectName("comboBox_vout_over_voltage_delay_railA")
        self.comboBox_vout_over_voltage_delay_railA.addItem("")
        self.comboBox_vout_over_voltage_delay_railA.addItem("")
        self.comboBox_vout_over_voltage_delay_railA.addItem("")
        self.comboBox_vout_over_voltage_delay_railA.addItem("")
        self.comboBox_vout_over_voltage_delay_railA.addItem("")
        self.comboBox_vout_over_voltage_delay_railA.addItem("")
        self.comboBox_vout_over_voltage_delay_railA.addItem("")
        self.comboBox_vout_over_voltage_delay_railA.addItem("")
        self.label_RailA_22 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_22.setGeometry(QtCore.QRect(220, 230, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_22.setFont(font)
        self.label_RailA_22.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_22.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RailA_22.setObjectName("label_RailA_22")
        self.comboBox_vout_over_voltage_retry_railA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vout_over_voltage_retry_railA.setGeometry(QtCore.QRect(460, 235, 115, 25))
        self.comboBox_vout_over_voltage_retry_railA.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vout_over_voltage_retry_railA.setObjectName("comboBox_vout_over_voltage_retry_railA")
        self.comboBox_vout_over_voltage_retry_railA.addItem("")
        self.comboBox_vout_over_voltage_retry_railA.addItem("")
        self.comboBox_vout_over_voltage_retry_railA.addItem("")
        self.comboBox_vout_over_voltage_retry_railA.addItem("")
        self.comboBox_vout_over_voltage_retry_railA.addItem("")
        self.comboBox_vout_over_voltage_retry_railA.addItem("")
        self.comboBox_vout_over_voltage_retry_railA.addItem("")
        self.comboBox_vout_over_voltage_retry_railA.addItem("")
        self.comboBox_over_temp_retry_railA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_over_temp_retry_railA.setGeometry(QtCore.QRect(460, 275, 115, 25))
        self.comboBox_over_temp_retry_railA.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_over_temp_retry_railA.setObjectName("comboBox_over_temp_retry_railA")
        self.comboBox_over_temp_retry_railA.addItem("")
        self.comboBox_over_temp_retry_railA.addItem("")
        self.comboBox_over_temp_retry_railA.addItem("")
        self.comboBox_over_temp_retry_railA.addItem("")
        self.comboBox_over_temp_retry_railA.addItem("")
        self.comboBox_over_temp_retry_railA.addItem("")
        self.comboBox_over_temp_retry_railA.addItem("")
        self.comboBox_over_temp_retry_railA.addItem("")
        self.label_RailA_23 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_23.setGeometry(QtCore.QRect(220, 270, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_23.setFont(font)
        self.label_RailA_23.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RailA_23.setObjectName("label_RailA_23")
        self.comboBox_over_temp_delay_railA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_over_temp_delay_railA.setGeometry(QtCore.QRect(590, 275, 270, 25))
        self.comboBox_over_temp_delay_railA.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_over_temp_delay_railA.setObjectName("comboBox_over_temp_delay_railA")
        self.comboBox_over_temp_delay_railA.addItem("")
        self.comboBox_over_temp_delay_railA.addItem("")
        self.comboBox_over_temp_delay_railA.addItem("")
        self.comboBox_over_temp_delay_railA.addItem("")
        self.comboBox_over_temp_delay_railA.addItem("")
        self.comboBox_over_temp_delay_railA.addItem("")
        self.comboBox_over_temp_delay_railA.addItem("")
        self.comboBox_over_temp_delay_railA.addItem("")
        self.label_RailA_9 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_9.setGeometry(QtCore.QRect(10, 270, 211, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_9.setFont(font)
        self.label_RailA_9.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_9.setObjectName("label_RailA_9")
        self.comboBox_over_temp_response_railA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_over_temp_response_railA.setGeometry(QtCore.QRect(250, 275, 190, 25))
        self.comboBox_over_temp_response_railA.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_over_temp_response_railA.setObjectName("comboBox_over_temp_response_railA")
        self.comboBox_over_temp_response_railA.addItem("")
        self.comboBox_over_temp_response_railA.addItem("")
        self.comboBox_over_temp_response_railA.addItem("")
        self.comboBox_vout_under_voltage_retry_railA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vout_under_voltage_retry_railA.setGeometry(QtCore.QRect(460, 315, 115, 25))
        self.comboBox_vout_under_voltage_retry_railA.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vout_under_voltage_retry_railA.setObjectName("comboBox_vout_under_voltage_retry_railA")
        self.comboBox_vout_under_voltage_retry_railA.addItem("")
        self.comboBox_vout_under_voltage_retry_railA.addItem("")
        self.comboBox_vout_under_voltage_retry_railA.addItem("")
        self.comboBox_vout_under_voltage_retry_railA.addItem("")
        self.comboBox_vout_under_voltage_retry_railA.addItem("")
        self.comboBox_vout_under_voltage_retry_railA.addItem("")
        self.comboBox_vout_under_voltage_retry_railA.addItem("")
        self.comboBox_vout_under_voltage_retry_railA.addItem("")
        self.label_RailA_24 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_24.setGeometry(QtCore.QRect(220, 310, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_24.setFont(font)
        self.label_RailA_24.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_24.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RailA_24.setObjectName("label_RailA_24")
        self.comboBox_vout_under_voltage_delay_railA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vout_under_voltage_delay_railA.setGeometry(QtCore.QRect(590, 315, 270, 25))
        self.comboBox_vout_under_voltage_delay_railA.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vout_under_voltage_delay_railA.setObjectName("comboBox_vout_under_voltage_delay_railA")
        self.comboBox_vout_under_voltage_delay_railA.addItem("")
        self.comboBox_vout_under_voltage_delay_railA.addItem("")
        self.comboBox_vout_under_voltage_delay_railA.addItem("")
        self.comboBox_vout_under_voltage_delay_railA.addItem("")
        self.comboBox_vout_under_voltage_delay_railA.addItem("")
        self.comboBox_vout_under_voltage_delay_railA.addItem("")
        self.comboBox_vout_under_voltage_delay_railA.addItem("")
        self.comboBox_vout_under_voltage_delay_railA.addItem("")
        self.label_RailA_10 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_10.setGeometry(QtCore.QRect(10, 311, 211, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_10.setFont(font)
        self.label_RailA_10.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_10.setObjectName("label_RailA_10")
        self.comboBox_vout_under_voltage_response_railA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vout_under_voltage_response_railA.setGeometry(QtCore.QRect(250, 315, 190, 25))
        self.comboBox_vout_under_voltage_response_railA.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vout_under_voltage_response_railA.setObjectName("comboBox_vout_under_voltage_response_railA")
        self.comboBox_vout_under_voltage_response_railA.addItem("")
        self.comboBox_vout_under_voltage_response_railA.addItem("")
        self.comboBox_vout_under_voltage_response_railA.addItem("")
        self.comboBox_vin_OV_retry = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vin_OV_retry.setGeometry(QtCore.QRect(460, 40, 115, 25))
        self.comboBox_vin_OV_retry.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vin_OV_retry.setObjectName("comboBox_vin_OV_retry")
        self.comboBox_vin_OV_retry.addItem("")
        self.comboBox_vin_OV_retry.addItem("")
        self.comboBox_vin_OV_retry.addItem("")
        self.comboBox_vin_OV_retry.addItem("")
        self.comboBox_vin_OV_retry.addItem("")
        self.comboBox_vin_OV_retry.addItem("")
        self.comboBox_vin_OV_retry.addItem("")
        self.comboBox_vin_OV_retry.addItem("")
        self.label_RailA_25 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_25.setGeometry(QtCore.QRect(220, 35, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_25.setFont(font)
        self.label_RailA_25.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_25.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RailA_25.setObjectName("label_RailA_25")
        self.comboBox_vin_OV_delay = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vin_OV_delay.setGeometry(QtCore.QRect(590, 40, 270, 25))
        self.comboBox_vin_OV_delay.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vin_OV_delay.setObjectName("comboBox_vin_OV_delay")
        self.comboBox_vin_OV_delay.addItem("")
        self.comboBox_vin_OV_delay.addItem("")
        self.comboBox_vin_OV_delay.addItem("")
        self.comboBox_vin_OV_delay.addItem("")
        self.comboBox_vin_OV_delay.addItem("")
        self.comboBox_vin_OV_delay.addItem("")
        self.comboBox_vin_OV_delay.addItem("")
        self.comboBox_vin_OV_delay.addItem("")
        self.label_RailA_11 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_11.setGeometry(QtCore.QRect(10, 35, 211, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_11.setFont(font)
        self.label_RailA_11.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_11.setObjectName("label_RailA_11")
        self.comboBox_vin_OV_response = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vin_OV_response.setGeometry(QtCore.QRect(250, 40, 190, 25))
        self.comboBox_vin_OV_response.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vin_OV_response.setObjectName("comboBox_vin_OV_response")
        self.comboBox_vin_OV_response.addItem("")
        self.comboBox_vin_OV_response.addItem("")
        self.comboBox_vin_OV_response.addItem("")
        self.label_RailA_13 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_13.setGeometry(QtCore.QRect(10, 76, 211, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_13.setFont(font)
        self.label_RailA_13.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_13.setObjectName("label_RailA_13")
        self.comboBox_vin_UV_delay = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vin_UV_delay.setGeometry(QtCore.QRect(590, 80, 270, 25))
        self.comboBox_vin_UV_delay.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vin_UV_delay.setObjectName("comboBox_vin_UV_delay")
        self.comboBox_vin_UV_delay.addItem("")
        self.comboBox_vin_UV_delay.addItem("")
        self.comboBox_vin_UV_delay.addItem("")
        self.comboBox_vin_UV_delay.addItem("")
        self.comboBox_vin_UV_delay.addItem("")
        self.comboBox_vin_UV_delay.addItem("")
        self.comboBox_vin_UV_delay.addItem("")
        self.comboBox_vin_UV_delay.addItem("")
        self.comboBox_vin_UV_retry = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vin_UV_retry.setGeometry(QtCore.QRect(460, 80, 115, 25))
        self.comboBox_vin_UV_retry.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vin_UV_retry.setObjectName("comboBox_vin_UV_retry")
        self.comboBox_vin_UV_retry.addItem("")
        self.comboBox_vin_UV_retry.addItem("")
        self.comboBox_vin_UV_retry.addItem("")
        self.comboBox_vin_UV_retry.addItem("")
        self.comboBox_vin_UV_retry.addItem("")
        self.comboBox_vin_UV_retry.addItem("")
        self.comboBox_vin_UV_retry.addItem("")
        self.comboBox_vin_UV_retry.addItem("")
        self.label_RailA_26 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_26.setGeometry(QtCore.QRect(220, 75, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_26.setFont(font)
        self.label_RailA_26.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_26.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RailA_26.setObjectName("label_RailA_26")
        self.comboBox_vin_UV_response = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vin_UV_response.setGeometry(QtCore.QRect(250, 80, 190, 25))
        self.comboBox_vin_UV_response.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vin_UV_response.setObjectName("comboBox_vin_UV_response")
        self.comboBox_vin_UV_response.addItem("")
        self.comboBox_vin_UV_response.addItem("")
        self.comboBox_vin_UV_response.addItem("")
        self.comboBox_vout_turn_on_time_response_railA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vout_turn_on_time_response_railA.setGeometry(QtCore.QRect(250, 155, 190, 25))
        self.comboBox_vout_turn_on_time_response_railA.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vout_turn_on_time_response_railA.setObjectName("comboBox_vout_turn_on_time_response_railA")
        self.comboBox_vout_turn_on_time_response_railA.addItem("")
        self.comboBox_vout_turn_on_time_response_railA.addItem("")
        self.comboBox_vout_turn_on_time_response_railA.addItem("")
        self.label_RailA_14 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_14.setGeometry(QtCore.QRect(10, 150, 211, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_14.setFont(font)
        self.label_RailA_14.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_14.setObjectName("label_RailA_14")
        self.label_RailA_27 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_27.setGeometry(QtCore.QRect(220, 150, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_27.setFont(font)
        self.label_RailA_27.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_27.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RailA_27.setObjectName("label_RailA_27")
        self.label_RailA_12 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_12.setGeometry(QtCore.QRect(10, 510, 211, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_12.setFont(font)
        self.label_RailA_12.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_12.setObjectName("label_RailA_12")
        self.label_RailA_6 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_6.setGeometry(QtCore.QRect(10, 430, 161, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_6.setFont(font)
        self.label_RailA_6.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_6.setObjectName("label_RailA_6")
        self.label_RailA_7 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_7.setGeometry(QtCore.QRect(10, 470, 211, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_7.setFont(font)
        self.label_RailA_7.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_7.setObjectName("label_RailA_7")
        self.label_RailA_28 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_28.setGeometry(QtCore.QRect(220, 430, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_28.setFont(font)
        self.label_RailA_28.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_28.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RailA_28.setObjectName("label_RailA_28")
        self.comboBox_vout_over_voltage_response_railB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vout_over_voltage_response_railB.setGeometry(QtCore.QRect(250, 475, 190, 25))
        self.comboBox_vout_over_voltage_response_railB.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vout_over_voltage_response_railB.setObjectName("comboBox_vout_over_voltage_response_railB")
        self.comboBox_vout_over_voltage_response_railB.addItem("")
        self.comboBox_vout_over_voltage_response_railB.addItem("")
        self.comboBox_vout_over_voltage_response_railB.addItem("")
        self.comboBox_vout_under_voltage_delay_railB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vout_under_voltage_delay_railB.setGeometry(QtCore.QRect(590, 555, 270, 25))
        self.comboBox_vout_under_voltage_delay_railB.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vout_under_voltage_delay_railB.setObjectName("comboBox_vout_under_voltage_delay_railB")
        self.comboBox_vout_under_voltage_delay_railB.addItem("")
        self.comboBox_vout_under_voltage_delay_railB.addItem("")
        self.comboBox_vout_under_voltage_delay_railB.addItem("")
        self.comboBox_vout_under_voltage_delay_railB.addItem("")
        self.comboBox_vout_under_voltage_delay_railB.addItem("")
        self.comboBox_vout_under_voltage_delay_railB.addItem("")
        self.comboBox_vout_under_voltage_delay_railB.addItem("")
        self.comboBox_vout_under_voltage_delay_railB.addItem("")
        self.comboBox_over_temp_delay_railB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_over_temp_delay_railB.setGeometry(QtCore.QRect(590, 515, 270, 25))
        self.comboBox_over_temp_delay_railB.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_over_temp_delay_railB.setObjectName("comboBox_over_temp_delay_railB")
        self.comboBox_over_temp_delay_railB.addItem("")
        self.comboBox_over_temp_delay_railB.addItem("")
        self.comboBox_over_temp_delay_railB.addItem("")
        self.comboBox_over_temp_delay_railB.addItem("")
        self.comboBox_over_temp_delay_railB.addItem("")
        self.comboBox_over_temp_delay_railB.addItem("")
        self.comboBox_over_temp_delay_railB.addItem("")
        self.comboBox_over_temp_delay_railB.addItem("")
        self.comboBox_over_temp_retry_railB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_over_temp_retry_railB.setGeometry(QtCore.QRect(460, 515, 115, 25))
        self.comboBox_over_temp_retry_railB.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_over_temp_retry_railB.setObjectName("comboBox_over_temp_retry_railB")
        self.comboBox_over_temp_retry_railB.addItem("")
        self.comboBox_over_temp_retry_railB.addItem("")
        self.comboBox_over_temp_retry_railB.addItem("")
        self.comboBox_over_temp_retry_railB.addItem("")
        self.comboBox_over_temp_retry_railB.addItem("")
        self.comboBox_over_temp_retry_railB.addItem("")
        self.comboBox_over_temp_retry_railB.addItem("")
        self.comboBox_over_temp_retry_railB.addItem("")
        self.comboBox_over_temp_response_railB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_over_temp_response_railB.setGeometry(QtCore.QRect(250, 515, 190, 25))
        self.comboBox_over_temp_response_railB.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_over_temp_response_railB.setObjectName("comboBox_over_temp_response_railB")
        self.comboBox_over_temp_response_railB.addItem("")
        self.comboBox_over_temp_response_railB.addItem("")
        self.comboBox_over_temp_response_railB.addItem("")
        self.label_RailA_15 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_15.setGeometry(QtCore.QRect(10, 551, 211, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_15.setFont(font)
        self.label_RailA_15.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_15.setObjectName("label_RailA_15")
        self.label_RailA_16 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_16.setGeometry(QtCore.QRect(10, 390, 211, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_16.setFont(font)
        self.label_RailA_16.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_16.setObjectName("label_RailA_16")
        self.comboBox_over_current_response_railB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_over_current_response_railB.setGeometry(QtCore.QRect(250, 435, 190, 25))
        self.comboBox_over_current_response_railB.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_over_current_response_railB.setObjectName("comboBox_over_current_response_railB")
        self.comboBox_over_current_response_railB.addItem("")
        self.comboBox_over_current_response_railB.addItem("")
        self.comboBox_over_current_response_railB.addItem("")
        self.comboBox_over_current_response_railB.addItem("")
        self.comboBox_over_current_retry_railB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_over_current_retry_railB.setGeometry(QtCore.QRect(460, 435, 115, 25))
        self.comboBox_over_current_retry_railB.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_over_current_retry_railB.setObjectName("comboBox_over_current_retry_railB")
        self.comboBox_over_current_retry_railB.addItem("")
        self.comboBox_over_current_retry_railB.addItem("")
        self.comboBox_over_current_retry_railB.addItem("")
        self.comboBox_over_current_retry_railB.addItem("")
        self.comboBox_over_current_retry_railB.addItem("")
        self.comboBox_over_current_retry_railB.addItem("")
        self.comboBox_over_current_retry_railB.addItem("")
        self.comboBox_over_current_retry_railB.addItem("")
        self.comboBox_vout_under_voltage_response_railB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vout_under_voltage_response_railB.setGeometry(QtCore.QRect(250, 555, 190, 25))
        self.comboBox_vout_under_voltage_response_railB.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vout_under_voltage_response_railB.setObjectName("comboBox_vout_under_voltage_response_railB")
        self.comboBox_vout_under_voltage_response_railB.addItem("")
        self.comboBox_vout_under_voltage_response_railB.addItem("")
        self.comboBox_vout_under_voltage_response_railB.addItem("")
        self.label_RailA_29 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_29.setGeometry(QtCore.QRect(220, 510, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_29.setFont(font)
        self.label_RailA_29.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_29.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RailA_29.setObjectName("label_RailA_29")
        self.comboBox_vout_turn_on_time_response_railB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vout_turn_on_time_response_railB.setGeometry(QtCore.QRect(250, 395, 190, 25))
        self.comboBox_vout_turn_on_time_response_railB.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vout_turn_on_time_response_railB.setObjectName("comboBox_vout_turn_on_time_response_railB")
        self.comboBox_vout_turn_on_time_response_railB.addItem("")
        self.comboBox_vout_turn_on_time_response_railB.addItem("")
        self.comboBox_vout_turn_on_time_response_railB.addItem("")
        self.label_RailA_30 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_30.setGeometry(QtCore.QRect(220, 470, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_30.setFont(font)
        self.label_RailA_30.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RailA_30.setObjectName("label_RailA_30")
        self.comboBox_vout_over_voltage_retry_railB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vout_over_voltage_retry_railB.setGeometry(QtCore.QRect(460, 475, 115, 25))
        self.comboBox_vout_over_voltage_retry_railB.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vout_over_voltage_retry_railB.setObjectName("comboBox_vout_over_voltage_retry_railB")
        self.comboBox_vout_over_voltage_retry_railB.addItem("")
        self.comboBox_vout_over_voltage_retry_railB.addItem("")
        self.comboBox_vout_over_voltage_retry_railB.addItem("")
        self.comboBox_vout_over_voltage_retry_railB.addItem("")
        self.comboBox_vout_over_voltage_retry_railB.addItem("")
        self.comboBox_vout_over_voltage_retry_railB.addItem("")
        self.comboBox_vout_over_voltage_retry_railB.addItem("")
        self.comboBox_vout_over_voltage_retry_railB.addItem("")
        self.comboBox_vout_over_voltage_delay_railB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vout_over_voltage_delay_railB.setGeometry(QtCore.QRect(590, 475, 270, 25))
        self.comboBox_vout_over_voltage_delay_railB.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vout_over_voltage_delay_railB.setObjectName("comboBox_vout_over_voltage_delay_railB")
        self.comboBox_vout_over_voltage_delay_railB.addItem("")
        self.comboBox_vout_over_voltage_delay_railB.addItem("")
        self.comboBox_vout_over_voltage_delay_railB.addItem("")
        self.comboBox_vout_over_voltage_delay_railB.addItem("")
        self.comboBox_vout_over_voltage_delay_railB.addItem("")
        self.comboBox_vout_over_voltage_delay_railB.addItem("")
        self.comboBox_vout_over_voltage_delay_railB.addItem("")
        self.comboBox_vout_over_voltage_delay_railB.addItem("")
        self.comboBox_over_current_delay_railB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_over_current_delay_railB.setGeometry(QtCore.QRect(590, 435, 270, 25))
        self.comboBox_over_current_delay_railB.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_over_current_delay_railB.setObjectName("comboBox_over_current_delay_railB")
        self.comboBox_over_current_delay_railB.addItem("")
        self.comboBox_over_current_delay_railB.addItem("")
        self.comboBox_over_current_delay_railB.addItem("")
        self.comboBox_over_current_delay_railB.addItem("")
        self.comboBox_over_current_delay_railB.addItem("")
        self.comboBox_over_current_delay_railB.addItem("")
        self.comboBox_over_current_delay_railB.addItem("")
        self.comboBox_over_current_delay_railB.addItem("")
        self.comboBox_vout_under_voltage_retry_railB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vout_under_voltage_retry_railB.setGeometry(QtCore.QRect(460, 555, 115, 25))
        self.comboBox_vout_under_voltage_retry_railB.setStyleSheet("QComboBox{\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vout_under_voltage_retry_railB.setObjectName("comboBox_vout_under_voltage_retry_railB")
        self.comboBox_vout_under_voltage_retry_railB.addItem("")
        self.comboBox_vout_under_voltage_retry_railB.addItem("")
        self.comboBox_vout_under_voltage_retry_railB.addItem("")
        self.comboBox_vout_under_voltage_retry_railB.addItem("")
        self.comboBox_vout_under_voltage_retry_railB.addItem("")
        self.comboBox_vout_under_voltage_retry_railB.addItem("")
        self.comboBox_vout_under_voltage_retry_railB.addItem("")
        self.comboBox_vout_under_voltage_retry_railB.addItem("")
        self.label_RailA_31 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_31.setGeometry(QtCore.QRect(220, 550, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_31.setFont(font)
        self.label_RailA_31.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_31.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RailA_31.setObjectName("label_RailA_31")
        self.label_RailA_32 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_32.setGeometry(QtCore.QRect(220, 390, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_32.setFont(font)
        self.label_RailA_32.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_32.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RailA_32.setObjectName("label_RailA_32")
        Fault_response.setCentralWidget(self.centralwidget)

        self.retranslateUi(Fault_response)
        QtCore.QMetaObject.connectSlotsByName(Fault_response)

    def retranslateUi(self, Fault_response):
        _translate = QtCore.QCoreApplication.translate
        Fault_response.setWindowTitle(_translate("Fault_response", "Fault"))
        self.label_Transient.setText(_translate("Fault_response", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Fault</span><span style=\" font-size:14pt;\"> Response</span></p></body></html>"))
        self.pushButton_Discard.setText(_translate("Fault_response", "Discard"))
        self.pushButton_Save.setText(_translate("Fault_response", "Save"))
        self.label_RailA_4.setText(_translate("Fault_response", "Over Current Fault "))
        self.label_RailA_5.setText(_translate("Fault_response", "Vout Over Voltage Fault"))
        self.label_display_RailB.setText(_translate("Fault_response", "Beta"))
        self.label_display_RailA.setText(_translate("Fault_response", "Alpha"))
        self.comboBox_over_current_response_railA.setItemText(0, _translate("Fault_response", "No Shutdown"))
        self.comboBox_over_current_response_railA.setItemText(1, _translate("Fault_response", "Shutdown when tracking UVP hits"))
        self.comboBox_over_current_response_railA.setItemText(2, _translate("Fault_response", "Shutdown after debounce time"))
        self.comboBox_over_current_response_railA.setItemText(3, _translate("Fault_response", "Immediate Shutdown"))
        self.comboBox_over_current_retry_railA.setItemText(0, _translate("Fault_response", "No Retry"))
        self.comboBox_over_current_retry_railA.setItemText(1, _translate("Fault_response", "Retry first time"))
        self.comboBox_over_current_retry_railA.setItemText(2, _translate("Fault_response", "Retry second time"))
        self.comboBox_over_current_retry_railA.setItemText(3, _translate("Fault_response", "Retry third time"))
        self.comboBox_over_current_retry_railA.setItemText(4, _translate("Fault_response", "Retry fourth time"))
        self.comboBox_over_current_retry_railA.setItemText(5, _translate("Fault_response", "Retry fifth time"))
        self.comboBox_over_current_retry_railA.setItemText(6, _translate("Fault_response", "Retry sixth time"))
        self.comboBox_over_current_retry_railA.setItemText(7, _translate("Fault_response", "Not supported"))
        self.label_RailA_18.setText(_translate("Fault_response", "Response Setting"))
        self.comboBox_over_current_delay_railA.setItemText(0, _translate("Fault_response", "1xMAX(TON DELAY,0.25ms): debounce 100us"))
        self.comboBox_over_current_delay_railA.setItemText(1, _translate("Fault_response", "2xMAX(TON DELAY,0.25ms): debounce 200us"))
        self.comboBox_over_current_delay_railA.setItemText(2, _translate("Fault_response", "3xMAX(TON DELAY,0.25ms): debounce 400us"))
        self.comboBox_over_current_delay_railA.setItemText(3, _translate("Fault_response", "4xMAX(TON DELAY,0.25ms): debounce 800us"))
        self.comboBox_over_current_delay_railA.setItemText(4, _translate("Fault_response", "5xMAX(TON DELAY,0.25ms): debounce 1000us"))
        self.comboBox_over_current_delay_railA.setItemText(5, _translate("Fault_response", "6xMAX(TON DELAY,0.25ms): debounce 1600us"))
        self.comboBox_over_current_delay_railA.setItemText(6, _translate("Fault_response", "7xMAX(TON DELAY,0.25ms): debounce 2000us"))
        self.comboBox_over_current_delay_railA.setItemText(7, _translate("Fault_response", "8xMAX(TON DELAY,0.25ms): debounce 3200us"))
        self.label_RailA_19.setText(_translate("Fault_response", "Retry Setting"))
        self.label_RailA_20.setText(_translate("Fault_response", "Retry delay Setting : Debounce delay"))
        self.label_RailA_21.setText(_translate("Fault_response", "  :  "))
        self.comboBox_vout_over_voltage_response_railA.setItemText(0, _translate("Fault_response", "No Shutdown"))
        self.comboBox_vout_over_voltage_response_railA.setItemText(1, _translate("Fault_response", "Shuts down after delay"))
        self.comboBox_vout_over_voltage_response_railA.setItemText(2, _translate("Fault_response", "Immediate Shuts down"))
        self.comboBox_vout_over_voltage_delay_railA.setItemText(0, _translate("Fault_response", "1xMAX(TON DELAY,0.25ms): debounce 0us"))
        self.comboBox_vout_over_voltage_delay_railA.setItemText(1, _translate("Fault_response", "2xMAX(TON DELAY,0.25ms): debounce 2us"))
        self.comboBox_vout_over_voltage_delay_railA.setItemText(2, _translate("Fault_response", "3xMAX(TON DELAY,0.25ms): debounce 4us"))
        self.comboBox_vout_over_voltage_delay_railA.setItemText(3, _translate("Fault_response", "4xMAX(TON DELAY,0.25ms): debounce 6us"))
        self.comboBox_vout_over_voltage_delay_railA.setItemText(4, _translate("Fault_response", "5xMAX(TON DELAY,0.25ms): debounce 8us"))
        self.comboBox_vout_over_voltage_delay_railA.setItemText(5, _translate("Fault_response", "6xMAX(TON DELAY,0.25ms): debounce 10us"))
        self.comboBox_vout_over_voltage_delay_railA.setItemText(6, _translate("Fault_response", "7xMAX(TON DELAY,0.25ms): debounce 12us"))
        self.comboBox_vout_over_voltage_delay_railA.setItemText(7, _translate("Fault_response", "8xMAX(TON DELAY,0.25ms): debounce 14us"))
        self.label_RailA_22.setText(_translate("Fault_response", "  :  "))
        self.comboBox_vout_over_voltage_retry_railA.setItemText(0, _translate("Fault_response", "No Retry"))
        self.comboBox_vout_over_voltage_retry_railA.setItemText(1, _translate("Fault_response", "Retry first time"))
        self.comboBox_vout_over_voltage_retry_railA.setItemText(2, _translate("Fault_response", "Retry second time"))
        self.comboBox_vout_over_voltage_retry_railA.setItemText(3, _translate("Fault_response", "Retry third time"))
        self.comboBox_vout_over_voltage_retry_railA.setItemText(4, _translate("Fault_response", "Retry fourth time"))
        self.comboBox_vout_over_voltage_retry_railA.setItemText(5, _translate("Fault_response", "Retry fifth time"))
        self.comboBox_vout_over_voltage_retry_railA.setItemText(6, _translate("Fault_response", "Retry sixth time"))
        self.comboBox_vout_over_voltage_retry_railA.setItemText(7, _translate("Fault_response", "Not supported"))
        self.comboBox_over_temp_retry_railA.setItemText(0, _translate("Fault_response", "No Retry"))
        self.comboBox_over_temp_retry_railA.setItemText(1, _translate("Fault_response", "Retry first time"))
        self.comboBox_over_temp_retry_railA.setItemText(2, _translate("Fault_response", "Retry second time"))
        self.comboBox_over_temp_retry_railA.setItemText(3, _translate("Fault_response", "Retry third time"))
        self.comboBox_over_temp_retry_railA.setItemText(4, _translate("Fault_response", "Retry fourth time"))
        self.comboBox_over_temp_retry_railA.setItemText(5, _translate("Fault_response", "Retry fifth time"))
        self.comboBox_over_temp_retry_railA.setItemText(6, _translate("Fault_response", "Retry sixth time"))
        self.comboBox_over_temp_retry_railA.setItemText(7, _translate("Fault_response", "Not supported"))
        self.label_RailA_23.setText(_translate("Fault_response", "  :  "))
        self.comboBox_over_temp_delay_railA.setItemText(0, _translate("Fault_response", "1xMAX(TON DELAY,0.25ms): debounce 1ms"))
        self.comboBox_over_temp_delay_railA.setItemText(1, _translate("Fault_response", "2xMAX(TON DELAY,0.25ms): debounce 2ms"))
        self.comboBox_over_temp_delay_railA.setItemText(2, _translate("Fault_response", "3xMAX(TON DELAY,0.25ms): debounce 3ms"))
        self.comboBox_over_temp_delay_railA.setItemText(3, _translate("Fault_response", "4xMAX(TON DELAY,0.25ms): debounce 4ms"))
        self.comboBox_over_temp_delay_railA.setItemText(4, _translate("Fault_response", "5xMAX(TON DELAY,0.25ms): debounce 5ms"))
        self.comboBox_over_temp_delay_railA.setItemText(5, _translate("Fault_response", "6xMAX(TON DELAY,0.25ms): debounce 6ms"))
        self.comboBox_over_temp_delay_railA.setItemText(6, _translate("Fault_response", "7xMAX(TON DELAY,0.25ms): debounce 8ms"))
        self.comboBox_over_temp_delay_railA.setItemText(7, _translate("Fault_response", "8xMAX(TON DELAY,0.25ms): debounce 10ms"))
        self.label_RailA_9.setText(_translate("Fault_response", "Over Temperature Fault"))
        self.comboBox_over_temp_response_railA.setItemText(0, _translate("Fault_response", "No Shutdown"))
        self.comboBox_over_temp_response_railA.setItemText(1, _translate("Fault_response", "Shuts down after delay"))
        self.comboBox_over_temp_response_railA.setItemText(2, _translate("Fault_response", "Immediate Shuts down"))
        self.comboBox_vout_under_voltage_retry_railA.setItemText(0, _translate("Fault_response", "No Retry"))
        self.comboBox_vout_under_voltage_retry_railA.setItemText(1, _translate("Fault_response", "Retry first time"))
        self.comboBox_vout_under_voltage_retry_railA.setItemText(2, _translate("Fault_response", "Retry second time"))
        self.comboBox_vout_under_voltage_retry_railA.setItemText(3, _translate("Fault_response", "Retry third time"))
        self.comboBox_vout_under_voltage_retry_railA.setItemText(4, _translate("Fault_response", "Retry fourth time"))
        self.comboBox_vout_under_voltage_retry_railA.setItemText(5, _translate("Fault_response", "Retry fifth time"))
        self.comboBox_vout_under_voltage_retry_railA.setItemText(6, _translate("Fault_response", "Retry sixth time"))
        self.comboBox_vout_under_voltage_retry_railA.setItemText(7, _translate("Fault_response", "Not supported"))
        self.label_RailA_24.setText(_translate("Fault_response", "  :  "))
        self.comboBox_vout_under_voltage_delay_railA.setItemText(0, _translate("Fault_response", "1xMAX(TON DELAY,0.25ms): debounce 5us"))
        self.comboBox_vout_under_voltage_delay_railA.setItemText(1, _translate("Fault_response", "2xMAX(TON DELAY,0.25ms): debounce 10us"))
        self.comboBox_vout_under_voltage_delay_railA.setItemText(2, _translate("Fault_response", "3xMAX(TON DELAY,0.25ms): debounce 20us"))
        self.comboBox_vout_under_voltage_delay_railA.setItemText(3, _translate("Fault_response", "4xMAX(TON DELAY,0.25ms): debounce 40us"))
        self.comboBox_vout_under_voltage_delay_railA.setItemText(4, _translate("Fault_response", "5xMAX(TON DELAY,0.25ms): debounce 80us"))
        self.comboBox_vout_under_voltage_delay_railA.setItemText(5, _translate("Fault_response", "6xMAX(TON DELAY,0.25ms): debounce 160us"))
        self.comboBox_vout_under_voltage_delay_railA.setItemText(6, _translate("Fault_response", "7xMAX(TON DELAY,0.25ms): debounce 320us"))
        self.comboBox_vout_under_voltage_delay_railA.setItemText(7, _translate("Fault_response", "8xMAX(TON DELAY,0.25ms): debounce 640us"))
        self.label_RailA_10.setText(_translate("Fault_response", "Vout Under Voltage Fault"))
        self.comboBox_vout_under_voltage_response_railA.setItemText(0, _translate("Fault_response", "No Shutdown"))
        self.comboBox_vout_under_voltage_response_railA.setItemText(1, _translate("Fault_response", "Shuts down after delay"))
        self.comboBox_vout_under_voltage_response_railA.setItemText(2, _translate("Fault_response", "Immediate Shuts down"))
        self.comboBox_vin_OV_retry.setItemText(0, _translate("Fault_response", "No Retry"))
        self.comboBox_vin_OV_retry.setItemText(1, _translate("Fault_response", "Retry first time"))
        self.comboBox_vin_OV_retry.setItemText(2, _translate("Fault_response", "Retry second time"))
        self.comboBox_vin_OV_retry.setItemText(3, _translate("Fault_response", "Retry third time"))
        self.comboBox_vin_OV_retry.setItemText(4, _translate("Fault_response", "Retry fourth time"))
        self.comboBox_vin_OV_retry.setItemText(5, _translate("Fault_response", "Retry fifth time"))
        self.comboBox_vin_OV_retry.setItemText(6, _translate("Fault_response", "Retry sixth time"))
        self.comboBox_vin_OV_retry.setItemText(7, _translate("Fault_response", "Not supported"))
        self.label_RailA_25.setText(_translate("Fault_response", "  :  "))
        self.comboBox_vin_OV_delay.setItemText(0, _translate("Fault_response", "1xMAX(TON DELAY,0.25ms): debounce 0us"))
        self.comboBox_vin_OV_delay.setItemText(1, _translate("Fault_response", "2xMAX(TON DELAY,0.25ms): debounce 2us"))
        self.comboBox_vin_OV_delay.setItemText(2, _translate("Fault_response", "3xMAX(TON DELAY,0.25ms): debounce 4us"))
        self.comboBox_vin_OV_delay.setItemText(3, _translate("Fault_response", "4xMAX(TON DELAY,0.25ms): debounce 6us"))
        self.comboBox_vin_OV_delay.setItemText(4, _translate("Fault_response", "5xMAX(TON DELAY,0.25ms): debounce 8us"))
        self.comboBox_vin_OV_delay.setItemText(5, _translate("Fault_response", "6xMAX(TON DELAY,0.25ms): debounce 10us"))
        self.comboBox_vin_OV_delay.setItemText(6, _translate("Fault_response", "7xMAX(TON DELAY,0.25ms): debounce 12us"))
        self.comboBox_vin_OV_delay.setItemText(7, _translate("Fault_response", "8xMAX(TON DELAY,0.25ms): debounce 14us"))
        self.label_RailA_11.setText(_translate("Fault_response", "Vin Over Voltage Fault"))
        self.comboBox_vin_OV_response.setItemText(0, _translate("Fault_response", "No Shutdown"))
        self.comboBox_vin_OV_response.setItemText(1, _translate("Fault_response", "Shuts down after delay"))
        self.comboBox_vin_OV_response.setItemText(2, _translate("Fault_response", "Immediate Shuts down"))
        self.label_RailA_13.setText(_translate("Fault_response", "Vin Under Voltage Fault"))
        self.comboBox_vin_UV_delay.setItemText(0, _translate("Fault_response", "1xMAX(TON DELAY,0.25ms): debounce 5us"))
        self.comboBox_vin_UV_delay.setItemText(1, _translate("Fault_response", "2xMAX(TON DELAY,0.25ms): debounce 10us"))
        self.comboBox_vin_UV_delay.setItemText(2, _translate("Fault_response", "3xMAX(TON DELAY,0.25ms): debounce 20us"))
        self.comboBox_vin_UV_delay.setItemText(3, _translate("Fault_response", "4xMAX(TON DELAY,0.25ms): debounce 40us"))
        self.comboBox_vin_UV_delay.setItemText(4, _translate("Fault_response", "5xMAX(TON DELAY,0.25ms): debounce 80us"))
        self.comboBox_vin_UV_delay.setItemText(5, _translate("Fault_response", "6xMAX(TON DELAY,0.25ms): debounce 160us"))
        self.comboBox_vin_UV_delay.setItemText(6, _translate("Fault_response", "7xMAX(TON DELAY,0.25ms): debounce 320us"))
        self.comboBox_vin_UV_delay.setItemText(7, _translate("Fault_response", "8xMAX(TON DELAY,0.25ms): debounce 640us"))
        self.comboBox_vin_UV_retry.setItemText(0, _translate("Fault_response", "No Retry"))
        self.comboBox_vin_UV_retry.setItemText(1, _translate("Fault_response", "Retry first time"))
        self.comboBox_vin_UV_retry.setItemText(2, _translate("Fault_response", "Retry second time"))
        self.comboBox_vin_UV_retry.setItemText(3, _translate("Fault_response", "Retry third time"))
        self.comboBox_vin_UV_retry.setItemText(4, _translate("Fault_response", "Retry fourth time"))
        self.comboBox_vin_UV_retry.setItemText(5, _translate("Fault_response", "Retry fifth time"))
        self.comboBox_vin_UV_retry.setItemText(6, _translate("Fault_response", "Retry sixth time"))
        self.comboBox_vin_UV_retry.setItemText(7, _translate("Fault_response", "Not supported"))
        self.label_RailA_26.setText(_translate("Fault_response", "  :  "))
        self.comboBox_vin_UV_response.setItemText(0, _translate("Fault_response", "No Shutdown"))
        self.comboBox_vin_UV_response.setItemText(1, _translate("Fault_response", "Shuts down after delay"))
        self.comboBox_vin_UV_response.setItemText(2, _translate("Fault_response", "Immediate Shuts down"))
        self.comboBox_vout_turn_on_time_response_railA.setItemText(0, _translate("Fault_response", "No Shutdown"))
        self.comboBox_vout_turn_on_time_response_railA.setItemText(1, _translate("Fault_response", "Shuts down after delay"))
        self.comboBox_vout_turn_on_time_response_railA.setItemText(2, _translate("Fault_response", "Immediate Shuts down"))
        self.label_RailA_14.setText(_translate("Fault_response", "Vout Turn on time Fault"))
        self.label_RailA_27.setText(_translate("Fault_response", "  :  "))
        self.label_RailA_12.setText(_translate("Fault_response", "Over Temperature Fault"))
        self.label_RailA_6.setText(_translate("Fault_response", "Over Current Fault "))
        self.label_RailA_7.setText(_translate("Fault_response", "Vout Over Voltage Fault"))
        self.label_RailA_28.setText(_translate("Fault_response", "  :  "))
        self.comboBox_vout_over_voltage_response_railB.setItemText(0, _translate("Fault_response", "No Shutdown"))
        self.comboBox_vout_over_voltage_response_railB.setItemText(1, _translate("Fault_response", "Shuts down after delay"))
        self.comboBox_vout_over_voltage_response_railB.setItemText(2, _translate("Fault_response", "Immediate Shuts down"))
        self.comboBox_vout_under_voltage_delay_railB.setItemText(0, _translate("Fault_response", "1xMAX(TON DELAY,0.25ms): debounce 5us"))
        self.comboBox_vout_under_voltage_delay_railB.setItemText(1, _translate("Fault_response", "2xMAX(TON DELAY,0.25ms): debounce 10us"))
        self.comboBox_vout_under_voltage_delay_railB.setItemText(2, _translate("Fault_response", "3xMAX(TON DELAY,0.25ms): debounce 20us"))
        self.comboBox_vout_under_voltage_delay_railB.setItemText(3, _translate("Fault_response", "4xMAX(TON DELAY,0.25ms): debounce 40us"))
        self.comboBox_vout_under_voltage_delay_railB.setItemText(4, _translate("Fault_response", "5xMAX(TON DELAY,0.25ms): debounce 80us"))
        self.comboBox_vout_under_voltage_delay_railB.setItemText(5, _translate("Fault_response", "6xMAX(TON DELAY,0.25ms): debounce 160us"))
        self.comboBox_vout_under_voltage_delay_railB.setItemText(6, _translate("Fault_response", "7xMAX(TON DELAY,0.25ms): debounce 320us"))
        self.comboBox_vout_under_voltage_delay_railB.setItemText(7, _translate("Fault_response", "8xMAX(TON DELAY,0.25ms): debounce 640us"))
        self.comboBox_over_temp_delay_railB.setItemText(0, _translate("Fault_response", "1xMAX(TON DELAY,0.25ms): debounce 1ms"))
        self.comboBox_over_temp_delay_railB.setItemText(1, _translate("Fault_response", "2xMAX(TON DELAY,0.25ms): debounce 2ms"))
        self.comboBox_over_temp_delay_railB.setItemText(2, _translate("Fault_response", "3xMAX(TON DELAY,0.25ms): debounce 3ms"))
        self.comboBox_over_temp_delay_railB.setItemText(3, _translate("Fault_response", "4xMAX(TON DELAY,0.25ms): debounce 4ms"))
        self.comboBox_over_temp_delay_railB.setItemText(4, _translate("Fault_response", "5xMAX(TON DELAY,0.25ms): debounce 5ms"))
        self.comboBox_over_temp_delay_railB.setItemText(5, _translate("Fault_response", "6xMAX(TON DELAY,0.25ms): debounce 6ms"))
        self.comboBox_over_temp_delay_railB.setItemText(6, _translate("Fault_response", "7xMAX(TON DELAY,0.25ms): debounce 8ms"))
        self.comboBox_over_temp_delay_railB.setItemText(7, _translate("Fault_response", "8xMAX(TON DELAY,0.25ms): debounce 10ms"))
        self.comboBox_over_temp_retry_railB.setItemText(0, _translate("Fault_response", "No Retry"))
        self.comboBox_over_temp_retry_railB.setItemText(1, _translate("Fault_response", "Retry first time"))
        self.comboBox_over_temp_retry_railB.setItemText(2, _translate("Fault_response", "Retry second time"))
        self.comboBox_over_temp_retry_railB.setItemText(3, _translate("Fault_response", "Retry third time"))
        self.comboBox_over_temp_retry_railB.setItemText(4, _translate("Fault_response", "Retry fourth time"))
        self.comboBox_over_temp_retry_railB.setItemText(5, _translate("Fault_response", "Retry fifth time"))
        self.comboBox_over_temp_retry_railB.setItemText(6, _translate("Fault_response", "Retry sixth time"))
        self.comboBox_over_temp_retry_railB.setItemText(7, _translate("Fault_response", "Not supported"))
        self.comboBox_over_temp_response_railB.setItemText(0, _translate("Fault_response", "No Shutdown"))
        self.comboBox_over_temp_response_railB.setItemText(1, _translate("Fault_response", "Shuts down after delay"))
        self.comboBox_over_temp_response_railB.setItemText(2, _translate("Fault_response", "Immediate Shuts down"))
        self.label_RailA_15.setText(_translate("Fault_response", "Vout Under Voltage Fault"))
        self.label_RailA_16.setText(_translate("Fault_response", "Vout Turn on time Fault"))
        self.comboBox_over_current_response_railB.setItemText(0, _translate("Fault_response", "No Shutdown"))
        self.comboBox_over_current_response_railB.setItemText(1, _translate("Fault_response", "Shutdown when tracking UVP hits"))
        self.comboBox_over_current_response_railB.setItemText(2, _translate("Fault_response", "Shutdown after debounce time"))
        self.comboBox_over_current_response_railB.setItemText(3, _translate("Fault_response", "Immediate Shutdown"))
        self.comboBox_over_current_retry_railB.setItemText(0, _translate("Fault_response", "No Retry"))
        self.comboBox_over_current_retry_railB.setItemText(1, _translate("Fault_response", "Retry first time"))
        self.comboBox_over_current_retry_railB.setItemText(2, _translate("Fault_response", "Retry second time"))
        self.comboBox_over_current_retry_railB.setItemText(3, _translate("Fault_response", "Retry third time"))
        self.comboBox_over_current_retry_railB.setItemText(4, _translate("Fault_response", "Retry fourth time"))
        self.comboBox_over_current_retry_railB.setItemText(5, _translate("Fault_response", "Retry fifth time"))
        self.comboBox_over_current_retry_railB.setItemText(6, _translate("Fault_response", "Retry sixth time"))
        self.comboBox_over_current_retry_railB.setItemText(7, _translate("Fault_response", "Not supported"))
        self.comboBox_vout_under_voltage_response_railB.setItemText(0, _translate("Fault_response", "No Shutdown"))
        self.comboBox_vout_under_voltage_response_railB.setItemText(1, _translate("Fault_response", "Shuts down after delay"))
        self.comboBox_vout_under_voltage_response_railB.setItemText(2, _translate("Fault_response", "Immediate Shuts down"))
        self.label_RailA_29.setText(_translate("Fault_response", "  :  "))
        self.comboBox_vout_turn_on_time_response_railB.setItemText(0, _translate("Fault_response", "No Shutdown"))
        self.comboBox_vout_turn_on_time_response_railB.setItemText(1, _translate("Fault_response", "Shuts down after delay"))
        self.comboBox_vout_turn_on_time_response_railB.setItemText(2, _translate("Fault_response", "Immediate Shuts down"))
        self.label_RailA_30.setText(_translate("Fault_response", "  :  "))
        self.comboBox_vout_over_voltage_retry_railB.setItemText(0, _translate("Fault_response", "No Retry"))
        self.comboBox_vout_over_voltage_retry_railB.setItemText(1, _translate("Fault_response", "Retry first time"))
        self.comboBox_vout_over_voltage_retry_railB.setItemText(2, _translate("Fault_response", "Retry second time"))
        self.comboBox_vout_over_voltage_retry_railB.setItemText(3, _translate("Fault_response", "Retry third time"))
        self.comboBox_vout_over_voltage_retry_railB.setItemText(4, _translate("Fault_response", "Retry fourth time"))
        self.comboBox_vout_over_voltage_retry_railB.setItemText(5, _translate("Fault_response", "Retry fifth time"))
        self.comboBox_vout_over_voltage_retry_railB.setItemText(6, _translate("Fault_response", "Retry sixth time"))
        self.comboBox_vout_over_voltage_retry_railB.setItemText(7, _translate("Fault_response", "Not supported"))
        self.comboBox_vout_over_voltage_delay_railB.setItemText(0, _translate("Fault_response", "1xMAX(TON DELAY,0.25ms): debounce 0us"))
        self.comboBox_vout_over_voltage_delay_railB.setItemText(1, _translate("Fault_response", "2xMAX(TON DELAY,0.25ms): debounce 2us"))
        self.comboBox_vout_over_voltage_delay_railB.setItemText(2, _translate("Fault_response", "3xMAX(TON DELAY,0.25ms): debounce 4us"))
        self.comboBox_vout_over_voltage_delay_railB.setItemText(3, _translate("Fault_response", "4xMAX(TON DELAY,0.25ms): debounce 6us"))
        self.comboBox_vout_over_voltage_delay_railB.setItemText(4, _translate("Fault_response", "5xMAX(TON DELAY,0.25ms): debounce 8us"))
        self.comboBox_vout_over_voltage_delay_railB.setItemText(5, _translate("Fault_response", "6xMAX(TON DELAY,0.25ms): debounce 10us"))
        self.comboBox_vout_over_voltage_delay_railB.setItemText(6, _translate("Fault_response", "7xMAX(TON DELAY,0.25ms): debounce 12us"))
        self.comboBox_vout_over_voltage_delay_railB.setItemText(7, _translate("Fault_response", "8xMAX(TON DELAY,0.25ms): debounce 14us"))
        self.comboBox_over_current_delay_railB.setItemText(0, _translate("Fault_response", "1xMAX(TON DELAY,0.25ms): debounce 100us"))
        self.comboBox_over_current_delay_railB.setItemText(1, _translate("Fault_response", "2xMAX(TON DELAY,0.25ms): debounce 200us"))
        self.comboBox_over_current_delay_railB.setItemText(2, _translate("Fault_response", "3xMAX(TON DELAY,0.25ms): debounce 400us"))
        self.comboBox_over_current_delay_railB.setItemText(3, _translate("Fault_response", "4xMAX(TON DELAY,0.25ms): debounce 800us"))
        self.comboBox_over_current_delay_railB.setItemText(4, _translate("Fault_response", "5xMAX(TON DELAY,0.25ms): debounce 1000us"))
        self.comboBox_over_current_delay_railB.setItemText(5, _translate("Fault_response", "6xMAX(TON DELAY,0.25ms): debounce 1600us"))
        self.comboBox_over_current_delay_railB.setItemText(6, _translate("Fault_response", "7xMAX(TON DELAY,0.25ms): debounce 2000us"))
        self.comboBox_over_current_delay_railB.setItemText(7, _translate("Fault_response", "8xMAX(TON DELAY,0.25ms): debounce 3200us"))
        self.comboBox_vout_under_voltage_retry_railB.setItemText(0, _translate("Fault_response", "No Retry"))
        self.comboBox_vout_under_voltage_retry_railB.setItemText(1, _translate("Fault_response", "Retry first time"))
        self.comboBox_vout_under_voltage_retry_railB.setItemText(2, _translate("Fault_response", "Retry second time"))
        self.comboBox_vout_under_voltage_retry_railB.setItemText(3, _translate("Fault_response", "Retry third time"))
        self.comboBox_vout_under_voltage_retry_railB.setItemText(4, _translate("Fault_response", "Retry fourth time"))
        self.comboBox_vout_under_voltage_retry_railB.setItemText(5, _translate("Fault_response", "Retry fifth time"))
        self.comboBox_vout_under_voltage_retry_railB.setItemText(6, _translate("Fault_response", "Retry sixth time"))
        self.comboBox_vout_under_voltage_retry_railB.setItemText(7, _translate("Fault_response", "Not supported"))
        self.label_RailA_31.setText(_translate("Fault_response", "  :  "))
        self.label_RailA_32.setText(_translate("Fault_response", "  :  "))

