# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PMBus_Address.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PMBus_address_configuration(object):
    def setupUi(self, PMBus_address_configuration):
        PMBus_address_configuration.setObjectName("PMBus_address_configuration")
        PMBus_address_configuration.resize(614, 576)
        self.centralwidget = QtWidgets.QWidget(PMBus_address_configuration)
        self.centralwidget.setObjectName("centralwidget")
        self.label_main_PMBus_Address = QtWidgets.QLabel(self.centralwidget)
        self.label_main_PMBus_Address.setGeometry(QtCore.QRect(10, 0, 591, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_main_PMBus_Address.setFont(font)
        self.label_main_PMBus_Address.setStyleSheet("background-color: rgb(38, 23, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_main_PMBus_Address.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main_PMBus_Address.setObjectName("label_main_PMBus_Address")
        self.frame_phase_display = QtWidgets.QFrame(self.centralwidget)
        self.frame_phase_display.setGeometry(QtCore.QRect(10, 45, 591, 521))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame_phase_display.setFont(font)
        self.frame_phase_display.setStyleSheet("\n"
"border: 2px solid darkorange;\n"
"border-radius:0px;\n"
"")
        self.frame_phase_display.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_phase_display.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_phase_display.setObjectName("frame_phase_display")
        self.pushButton_Discard = QtWidgets.QPushButton(self.frame_phase_display)
        self.pushButton_Discard.setGeometry(QtCore.QRect(160, 450, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Discard.setFont(font)
        self.pushButton_Discard.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Discard.setStyleSheet("QPushButton{background-color: rgb(219, 100, 17);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid red;\n"
"background-color: orange;\n"
"}\n"
"")
        self.pushButton_Discard.setObjectName("pushButton_Discard")
        self.pushButton_Save = QtWidgets.QPushButton(self.frame_phase_display)
        self.pushButton_Save.setGeometry(QtCore.QRect(320, 450, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Save.setStyleSheet("QPushButton{background-color: rgb(0, 153, 74);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid green;\n"
"background-color:lightgreen;\n"
"}\n"
"")
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.label_RailA = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA.setGeometry(QtCore.QRect(90, 20, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA.setFont(font)
        self.label_RailA.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA.setObjectName("label_RailA")
        self.label_RailA_2 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_2.setGeometry(QtCore.QRect(90, 70, 141, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_2.setFont(font)
        self.label_RailA_2.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_2.setObjectName("label_RailA_2")
        self.label_RailA_3 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_3.setGeometry(QtCore.QRect(90, 120, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_3.setFont(font)
        self.label_RailA_3.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_3.setObjectName("label_RailA_3")
        self.label_RailA_4 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_4.setGeometry(QtCore.QRect(90, 370, 191, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_4.setFont(font)
        self.label_RailA_4.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_4.setObjectName("label_RailA_4")
        self.label_RailA_5 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_5.setGeometry(QtCore.QRect(90, 170, 121, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_5.setFont(font)
        self.label_RailA_5.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_5.setObjectName("label_RailA_5")
        self.label_RailA_6 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_6.setGeometry(QtCore.QRect(90, 220, 101, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_6.setFont(font)
        self.label_RailA_6.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_6.setObjectName("label_RailA_6")
        self.label_RailA_7 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_7.setGeometry(QtCore.QRect(90, 270, 121, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_7.setFont(font)
        self.label_RailA_7.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_7.setObjectName("label_RailA_7")
        self.label_RailA_8 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_8.setGeometry(QtCore.QRect(90, 320, 91, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_8.setFont(font)
        self.label_RailA_8.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_8.setObjectName("label_RailA_8")
        self.lineEdit_PMBus_address = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_PMBus_address.setGeometry(QtCore.QRect(370, 70, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PMBus_address.setFont(font)
        self.lineEdit_PMBus_address.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PMBus_address.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PMBus_address.setObjectName("lineEdit_PMBus_address")
        self.lineEdit_MFR_ID = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_MFR_ID.setGeometry(QtCore.QRect(370, 120, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_MFR_ID.setFont(font)
        self.lineEdit_MFR_ID.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_MFR_ID.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_MFR_ID.setObjectName("lineEdit_MFR_ID")
        self.lineEdit_MFR_location = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_MFR_location.setGeometry(QtCore.QRect(370, 170, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_MFR_location.setFont(font)
        self.lineEdit_MFR_location.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_MFR_location.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_MFR_location.setObjectName("lineEdit_MFR_location")
        self.lineEdit_MFR_model = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_MFR_model.setGeometry(QtCore.QRect(370, 220, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_MFR_model.setFont(font)
        self.lineEdit_MFR_model.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_MFR_model.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_MFR_model.setObjectName("lineEdit_MFR_model")
        self.lineEdit_MFR_revision = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_MFR_revision.setGeometry(QtCore.QRect(370, 270, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_MFR_revision.setFont(font)
        self.lineEdit_MFR_revision.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_MFR_revision.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_MFR_revision.setObjectName("lineEdit_MFR_revision")
        self.lineEdit_device_serial_number = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_device_serial_number.setGeometry(QtCore.QRect(370, 370, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_device_serial_number.setFont(font)
        self.lineEdit_device_serial_number.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_device_serial_number.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_device_serial_number.setObjectName("lineEdit_device_serial_number")
        self.label_part_name = QtWidgets.QLabel(self.frame_phase_display)
        self.label_part_name.setGeometry(QtCore.QRect(370, 20, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_part_name.setFont(font)
        self.label_part_name.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_part_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_part_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_part_name.setObjectName("label_part_name")
        self.label_RailA_10 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_10.setGeometry(QtCore.QRect(280, 70, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_10.setFont(font)
        self.label_RailA_10.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_10.setObjectName("label_RailA_10")
        self.label_RailA_11 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_11.setGeometry(QtCore.QRect(270, 120, 91, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_11.setFont(font)
        self.label_RailA_11.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_11.setObjectName("label_RailA_11")
        self.label_RailA_12 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_12.setGeometry(QtCore.QRect(280, 170, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_12.setFont(font)
        self.label_RailA_12.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_12.setObjectName("label_RailA_12")
        self.label_RailA_13 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_13.setGeometry(QtCore.QRect(280, 270, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_13.setFont(font)
        self.label_RailA_13.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_13.setObjectName("label_RailA_13")
        self.label_RailA_14 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_14.setGeometry(QtCore.QRect(290, 320, 71, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_14.setFont(font)
        self.label_RailA_14.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_14.setObjectName("label_RailA_14")
        self.label_RailA_15 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_15.setGeometry(QtCore.QRect(280, 370, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_15.setFont(font)
        self.label_RailA_15.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_15.setObjectName("label_RailA_15")
        self.label_RailA_16 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_16.setGeometry(QtCore.QRect(280, 220, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_16.setFont(font)
        self.label_RailA_16.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_16.setObjectName("label_RailA_16")
        self.lineEdit_MFR_date = QtWidgets.QDateEdit(self.centralwidget)
        self.lineEdit_MFR_date.setGeometry(QtCore.QRect(380, 370, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_MFR_date.setFont(font)
        self.lineEdit_MFR_date.setStyleSheet("QDateEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QDateEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QDateEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.lineEdit_MFR_date.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_MFR_date.setMaximumDate(QtCore.QDate(2100, 12, 31))
        self.lineEdit_MFR_date.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.lineEdit_MFR_date.setCalendarPopup(True)
        self.lineEdit_MFR_date.setObjectName("lineEdit_MFR_date")
        PMBus_address_configuration.setCentralWidget(self.centralwidget)

        self.retranslateUi(PMBus_address_configuration)
        QtCore.QMetaObject.connectSlotsByName(PMBus_address_configuration)

    def retranslateUi(self, PMBus_address_configuration):
        _translate = QtCore.QCoreApplication.translate
        PMBus_address_configuration.setWindowTitle(_translate("PMBus_address_configuration", "Device Configuration"))
        self.label_main_PMBus_Address.setText(_translate("PMBus_address_configuration", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">PMBus</span><span style=\" font-size:14pt;\"> Address</span></p></body></html>"))
        self.pushButton_Discard.setText(_translate("PMBus_address_configuration", "Discard"))
        self.pushButton_Save.setText(_translate("PMBus_address_configuration", "Save"))
        self.label_RailA.setText(_translate("PMBus_address_configuration", "Part Name"))
        self.label_RailA_2.setText(_translate("PMBus_address_configuration", "PMBus Address"))
        self.label_RailA_3.setText(_translate("PMBus_address_configuration", "MFR ID"))
        self.label_RailA_4.setText(_translate("PMBus_address_configuration", "Device Serial Number"))
        self.label_RailA_5.setText(_translate("PMBus_address_configuration", "MFR Location"))
        self.label_RailA_6.setText(_translate("PMBus_address_configuration", "MFR Model"))
        self.label_RailA_7.setText(_translate("PMBus_address_configuration", "MFR Revision"))
        self.label_RailA_8.setText(_translate("PMBus_address_configuration", "MFR Date"))
        self.lineEdit_PMBus_address.setPlaceholderText(_translate("PMBus_address_configuration", "75"))
        self.lineEdit_MFR_ID.setPlaceholderText(_translate("PMBus_address_configuration", "0000"))
        self.lineEdit_MFR_location.setPlaceholderText(_translate("PMBus_address_configuration", "0000"))
        self.lineEdit_MFR_model.setPlaceholderText(_translate("PMBus_address_configuration", "0000"))
        self.lineEdit_MFR_revision.setPlaceholderText(_translate("PMBus_address_configuration", "0000"))
        self.lineEdit_device_serial_number.setPlaceholderText(_translate("PMBus_address_configuration", "0000"))
        self.label_part_name.setText(_translate("PMBus_address_configuration", "AMP4592"))
        self.label_RailA_10.setText(_translate("PMBus_address_configuration", "  :         0x"))
        self.label_RailA_11.setText(_translate("PMBus_address_configuration", "  :         0x"))
        self.label_RailA_12.setText(_translate("PMBus_address_configuration", "  :         0x"))
        self.label_RailA_13.setText(_translate("PMBus_address_configuration", "  :         0x"))
        self.label_RailA_14.setText(_translate("PMBus_address_configuration", "  :             "))
        self.label_RailA_15.setText(_translate("PMBus_address_configuration", "  :         0x"))
        self.label_RailA_16.setText(_translate("PMBus_address_configuration", "  :         0x"))

