# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SVI2_Configuration.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_label_main_SVI2_Configuration(object):
    def setupUi(self, label_main_SVI2_Configuration):
        label_main_SVI2_Configuration.setObjectName("label_main_SVI2_Configuration")
        label_main_SVI2_Configuration.resize(1042, 559)
        self.centralwidget = QtWidgets.QWidget(label_main_SVI2_Configuration)
        self.centralwidget.setObjectName("centralwidget")
        self.label_SVID_Configuration = QtWidgets.QLabel(self.centralwidget)
        self.label_SVID_Configuration.setGeometry(QtCore.QRect(10, 0, 1021, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_SVID_Configuration.setFont(font)
        self.label_SVID_Configuration.setStyleSheet("background-color: rgb(38, 23, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_SVID_Configuration.setAlignment(QtCore.Qt.AlignCenter)
        self.label_SVID_Configuration.setObjectName("label_SVID_Configuration")
        self.frame_display = QtWidgets.QFrame(self.centralwidget)
        self.frame_display.setGeometry(QtCore.QRect(10, 40, 1021, 511))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame_display.setFont(font)
        self.frame_display.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_display.setStyleSheet("\n"
"border: 2px solid darkorange;\n"
"border-radius:0px;\n"
"")
        self.frame_display.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_display.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_display.setObjectName("frame_display")
        self.pushButton_Discard = QtWidgets.QPushButton(self.frame_display)
        self.pushButton_Discard.setGeometry(QtCore.QRect(160, 460, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Discard.setFont(font)
        self.pushButton_Discard.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Discard.setStyleSheet("QPushButton{background-color: rgb(219, 100, 17);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid red;\n"
"background-color: orange;\n"
"}\n"
"")
        self.pushButton_Discard.setObjectName("pushButton_Discard")
        self.pushButton_Save = QtWidgets.QPushButton(self.frame_display)
        self.pushButton_Save.setGeometry(QtCore.QRect(330, 460, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Save.setStyleSheet("QPushButton{background-color: rgb(0, 153, 74);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid green;\n"
"background-color:lightgreen;\n"
"}\n"
"")
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.label_RailA_4 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_4.setGeometry(QtCore.QRect(10, 115, 131, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_4.setFont(font)
        self.label_RailA_4.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_4.setObjectName("label_RailA_4")
        self.label_RailA_6 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_6.setGeometry(QtCore.QRect(10, 80, 141, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_6.setFont(font)
        self.label_RailA_6.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_6.setObjectName("label_RailA_6")
        self.label_RailA_8 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_8.setGeometry(QtCore.QRect(110, 380, 161, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_8.setFont(font)
        self.label_RailA_8.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_8.setObjectName("label_RailA_8")
        self.lineEdit_icc_max_railA = QtWidgets.QLineEdit(self.frame_display)
        self.lineEdit_icc_max_railA.setGeometry(QtCore.QRect(300, 80, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_icc_max_railA.setFont(font)
        self.lineEdit_icc_max_railA.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_icc_max_railA.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_icc_max_railA.setObjectName("lineEdit_icc_max_railA")
        self.lineEdit_temp_max = QtWidgets.QLineEdit(self.frame_display)
        self.lineEdit_temp_max.setGeometry(QtCore.QRect(320, 380, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_temp_max.setFont(font)
        self.lineEdit_temp_max.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_temp_max.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_temp_max.setObjectName("lineEdit_temp_max")
        self.lineEdit_vid_max_railA = QtWidgets.QLineEdit(self.frame_display)
        self.lineEdit_vid_max_railA.setGeometry(QtCore.QRect(300, 115, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_vid_max_railA.setFont(font)
        self.lineEdit_vid_max_railA.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_vid_max_railA.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vid_max_railA.setObjectName("lineEdit_vid_max_railA")
        self.lineEdit_icc_max_railB = QtWidgets.QLineEdit(self.frame_display)
        self.lineEdit_icc_max_railB.setGeometry(QtCore.QRect(420, 80, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_icc_max_railB.setFont(font)
        self.lineEdit_icc_max_railB.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_icc_max_railB.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_icc_max_railB.setObjectName("lineEdit_icc_max_railB")
        self.lineEdit_vid_max_railB = QtWidgets.QLineEdit(self.frame_display)
        self.lineEdit_vid_max_railB.setGeometry(QtCore.QRect(420, 115, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_vid_max_railB.setFont(font)
        self.lineEdit_vid_max_railB.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_vid_max_railB.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vid_max_railB.setObjectName("lineEdit_vid_max_railB")
        self.label_RailA_12 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_12.setGeometry(QtCore.QRect(10, 150, 250, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_12.setFont(font)
        self.label_RailA_12.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_12.setObjectName("label_RailA_12")
        self.comboBox_slewrate_fast_RailA = QtWidgets.QComboBox(self.frame_display)
        self.comboBox_slewrate_fast_RailA.setGeometry(QtCore.QRect(300, 150, 100, 25))
        self.comboBox_slewrate_fast_RailA.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_slewrate_fast_RailA.setObjectName("comboBox_slewrate_fast_RailA")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailB = QtWidgets.QComboBox(self.frame_display)
        self.comboBox_slewrate_fast_RailB.setGeometry(QtCore.QRect(420, 150, 100, 25))
        self.comboBox_slewrate_fast_RailB.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_slewrate_fast_RailB.setObjectName("comboBox_slewrate_fast_RailB")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.checkBox_PMBus_override_railA = QtWidgets.QCheckBox(self.frame_display)
        self.checkBox_PMBus_override_railA.setGeometry(QtCore.QRect(270, 255, 130, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_PMBus_override_railA.sizePolicy().hasHeightForWidth())
        self.checkBox_PMBus_override_railA.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.checkBox_PMBus_override_railA.setFont(font)
        self.checkBox_PMBus_override_railA.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_PMBus_override_railA.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.checkBox_PMBus_override_railA.setObjectName("checkBox_PMBus_override_railA")
        self.comboBox_vid_resolution_RailA = QtWidgets.QComboBox(self.frame_display)
        self.comboBox_vid_resolution_RailA.setGeometry(QtCore.QRect(310, 295, 75, 26))
        self.comboBox_vid_resolution_RailA.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vid_resolution_RailA.setObjectName("comboBox_vid_resolution_RailA")
        self.comboBox_vid_resolution_RailA.addItem("")
        self.comboBox_vid_resolution_RailA.addItem("")
        self.comboBox_vid_resolution_RailA.addItem("")
        self.comboBox_vid_resolution_RailB = QtWidgets.QComboBox(self.frame_display)
        self.comboBox_vid_resolution_RailB.setGeometry(QtCore.QRect(430, 295, 75, 25))
        self.comboBox_vid_resolution_RailB.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vid_resolution_RailB.setObjectName("comboBox_vid_resolution_RailB")
        self.comboBox_vid_resolution_RailB.addItem("")
        self.comboBox_vid_resolution_RailB.addItem("")
        self.comboBox_vid_resolution_RailB.addItem("")
        self.frame = QtWidgets.QFrame(self.frame_display)
        self.frame.setGeometry(QtCore.QRect(620, 10, 391, 481))
        self.frame.setStyleSheet("border: 1px solid black;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_PVID_A_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_A_6.setGeometry(QtCore.QRect(80, 390, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_A_6.setFont(font)
        self.lineEdit_PVID_A_6.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_A_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_A_6.setObjectName("lineEdit_PVID_A_6")
        self.label_RailA_18 = QtWidgets.QLabel(self.frame)
        self.label_RailA_18.setGeometry(QtCore.QRect(30, 90, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_18.setFont(font)
        self.label_RailA_18.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_18.setObjectName("label_RailA_18")
        self.lineEdit_PVID_A_7 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_A_7.setGeometry(QtCore.QRect(80, 440, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_A_7.setFont(font)
        self.lineEdit_PVID_A_7.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_A_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_A_7.setObjectName("lineEdit_PVID_A_7")
        self.lineEdit_PVID_B_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_B_6.setGeometry(QtCore.QRect(230, 390, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_B_6.setFont(font)
        self.lineEdit_PVID_B_6.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_B_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_B_6.setObjectName("lineEdit_PVID_B_6")
        self.lineEdit_PVID_A_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_A_3.setGeometry(QtCore.QRect(80, 240, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_A_3.setFont(font)
        self.lineEdit_PVID_A_3.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_A_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_A_3.setObjectName("lineEdit_PVID_A_3")
        self.lineEdit_PVID_B_1 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_B_1.setGeometry(QtCore.QRect(230, 140, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_B_1.setFont(font)
        self.lineEdit_PVID_B_1.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_B_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_B_1.setObjectName("lineEdit_PVID_B_1")
        self.pushButton_Enable_APD_railA = QtWidgets.QPushButton(self.frame)
        self.pushButton_Enable_APD_railA.setGeometry(QtCore.QRect(220, 0, 51, 51))
        self.pushButton_Enable_APD_railA.setMouseTracking(True)
        self.pushButton_Enable_APD_railA.setTabletTracking(True)
        self.pushButton_Enable_APD_railA.setStyleSheet("QPushButton{\n"
"border-image: url(:/GUI_IMAGE/but0.png);\n"
"}\n"
"\n"
"\n"
"QPushButton::hover {\n"
"border-image: url(:/GUI_IMAGE/but0_hover.png);\n"
"    }\n"
"")
        self.pushButton_Enable_APD_railA.setText("")
        self.pushButton_Enable_APD_railA.setCheckable(True)
        self.pushButton_Enable_APD_railA.setDefault(True)
        self.pushButton_Enable_APD_railA.setObjectName("pushButton_Enable_APD_railA")
        self.label_RailA_20 = QtWidgets.QLabel(self.frame)
        self.label_RailA_20.setGeometry(QtCore.QRect(30, 190, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_20.setFont(font)
        self.label_RailA_20.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_20.setObjectName("label_RailA_20")
        self.lineEdit_PVID_A_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_A_4.setGeometry(QtCore.QRect(80, 290, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_A_4.setFont(font)
        self.lineEdit_PVID_A_4.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_A_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_A_4.setObjectName("lineEdit_PVID_A_4")
        self.lineEdit_PVID_A_0 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_A_0.setGeometry(QtCore.QRect(80, 90, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_A_0.setFont(font)
        self.lineEdit_PVID_A_0.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_A_0.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_A_0.setObjectName("lineEdit_PVID_A_0")
        self.lineEdit_PVID_B_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_B_3.setGeometry(QtCore.QRect(230, 240, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_B_3.setFont(font)
        self.lineEdit_PVID_B_3.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_B_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_B_3.setObjectName("lineEdit_PVID_B_3")
        self.lineEdit_PVID_A_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_A_5.setGeometry(QtCore.QRect(80, 340, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_A_5.setFont(font)
        self.lineEdit_PVID_A_5.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_A_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_A_5.setObjectName("lineEdit_PVID_A_5")
        self.lineEdit_PVID_A_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_A_2.setGeometry(QtCore.QRect(80, 190, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_A_2.setFont(font)
        self.lineEdit_PVID_A_2.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_A_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_A_2.setObjectName("lineEdit_PVID_A_2")
        self.lineEdit_PVID_B_0 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_B_0.setGeometry(QtCore.QRect(230, 90, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_B_0.setFont(font)
        self.lineEdit_PVID_B_0.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_B_0.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_B_0.setObjectName("lineEdit_PVID_B_0")
        self.label_RailA_19 = QtWidgets.QLabel(self.frame)
        self.label_RailA_19.setGeometry(QtCore.QRect(30, 140, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_19.setFont(font)
        self.label_RailA_19.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_19.setObjectName("label_RailA_19")
        self.label_RailA_22 = QtWidgets.QLabel(self.frame)
        self.label_RailA_22.setGeometry(QtCore.QRect(30, 290, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_22.setFont(font)
        self.label_RailA_22.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_22.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_22.setObjectName("label_RailA_22")
        self.lineEdit_PVID_A_1 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_A_1.setGeometry(QtCore.QRect(80, 140, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_A_1.setFont(font)
        self.lineEdit_PVID_A_1.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_A_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_A_1.setObjectName("lineEdit_PVID_A_1")
        self.label_RailA_21 = QtWidgets.QLabel(self.frame)
        self.label_RailA_21.setGeometry(QtCore.QRect(30, 240, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_21.setFont(font)
        self.label_RailA_21.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_21.setObjectName("label_RailA_21")
        self.label_RailA_27 = QtWidgets.QLabel(self.frame)
        self.label_RailA_27.setGeometry(QtCore.QRect(30, 440, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_27.setFont(font)
        self.label_RailA_27.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_27.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_27.setObjectName("label_RailA_27")
        self.label_RailA_24 = QtWidgets.QLabel(self.frame)
        self.label_RailA_24.setGeometry(QtCore.QRect(30, 390, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_24.setFont(font)
        self.label_RailA_24.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_24.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_24.setObjectName("label_RailA_24")
        self.label_RailA_23 = QtWidgets.QLabel(self.frame)
        self.label_RailA_23.setGeometry(QtCore.QRect(30, 340, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_23.setFont(font)
        self.label_RailA_23.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_23.setObjectName("label_RailA_23")
        self.lineEdit_PVID_B_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_B_2.setGeometry(QtCore.QRect(230, 190, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_B_2.setFont(font)
        self.lineEdit_PVID_B_2.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_B_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_B_2.setObjectName("lineEdit_PVID_B_2")
        self.lineEdit_PVID_B_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_B_5.setGeometry(QtCore.QRect(230, 340, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_B_5.setFont(font)
        self.lineEdit_PVID_B_5.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_B_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_B_5.setObjectName("lineEdit_PVID_B_5")
        self.lineEdit_PVID_B_7 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_B_7.setGeometry(QtCore.QRect(230, 440, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_B_7.setFont(font)
        self.lineEdit_PVID_B_7.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_B_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_B_7.setObjectName("lineEdit_PVID_B_7")
        self.lineEdit_PVID_B_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_B_4.setGeometry(QtCore.QRect(230, 290, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_B_4.setFont(font)
        self.lineEdit_PVID_B_4.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_B_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_B_4.setObjectName("lineEdit_PVID_B_4")
        self.label_EnableA = QtWidgets.QLabel(self.frame)
        self.label_EnableA.setGeometry(QtCore.QRect(280, 10, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_EnableA.setFont(font)
        self.label_EnableA.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_EnableA.setAlignment(QtCore.Qt.AlignCenter)
        self.label_EnableA.setObjectName("label_EnableA")
        self.label_DisableA = QtWidgets.QLabel(self.frame)
        self.label_DisableA.setGeometry(QtCore.QRect(160, 12, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_DisableA.setFont(font)
        self.label_DisableA.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_DisableA.setObjectName("label_DisableA")
        self.label_RailA_17 = QtWidgets.QLabel(self.frame)
        self.label_RailA_17.setGeometry(QtCore.QRect(40, 10, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_RailA_17.setFont(font)
        self.label_RailA_17.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_17.setObjectName("label_RailA_17")
        self.label_display_RailA = QtWidgets.QLabel(self.frame)
        self.label_display_RailA.setGeometry(QtCore.QRect(100, 50, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_display_RailA.setFont(font)
        self.label_display_RailA.setStyleSheet("border: none;")
        self.label_display_RailA.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_display_RailA.setAlignment(QtCore.Qt.AlignCenter)
        self.label_display_RailA.setObjectName("label_display_RailA")
        self.label_display_RailB = QtWidgets.QLabel(self.frame)
        self.label_display_RailB.setGeometry(QtCore.QRect(240, 50, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_display_RailB.setFont(font)
        self.label_display_RailB.setStyleSheet("border: none;")
        self.label_display_RailB.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_display_RailB.setAlignment(QtCore.Qt.AlignCenter)
        self.label_display_RailB.setObjectName("label_display_RailB")
        self.label_RailA_42 = QtWidgets.QLabel(self.frame)
        self.label_RailA_42.setGeometry(QtCore.QRect(351, 91, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_42.setFont(font)
        self.label_RailA_42.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_42.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_42.setObjectName("label_RailA_42")
        self.label_RailA_43 = QtWidgets.QLabel(self.frame)
        self.label_RailA_43.setGeometry(QtCore.QRect(351, 142, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_43.setFont(font)
        self.label_RailA_43.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_43.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_43.setObjectName("label_RailA_43")
        self.label_RailA_44 = QtWidgets.QLabel(self.frame)
        self.label_RailA_44.setGeometry(QtCore.QRect(351, 198, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_44.setFont(font)
        self.label_RailA_44.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_44.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_44.setObjectName("label_RailA_44")
        self.label_RailA_45 = QtWidgets.QLabel(self.frame)
        self.label_RailA_45.setGeometry(QtCore.QRect(351, 242, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_45.setFont(font)
        self.label_RailA_45.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_45.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_45.setObjectName("label_RailA_45")
        self.label_RailA_46 = QtWidgets.QLabel(self.frame)
        self.label_RailA_46.setGeometry(QtCore.QRect(351, 298, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_46.setFont(font)
        self.label_RailA_46.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_46.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_46.setObjectName("label_RailA_46")
        self.label_RailA_47 = QtWidgets.QLabel(self.frame)
        self.label_RailA_47.setGeometry(QtCore.QRect(351, 348, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_47.setFont(font)
        self.label_RailA_47.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_47.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_47.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_47.setObjectName("label_RailA_47")
        self.label_RailA_48 = QtWidgets.QLabel(self.frame)
        self.label_RailA_48.setGeometry(QtCore.QRect(351, 392, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_48.setFont(font)
        self.label_RailA_48.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_48.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_48.setObjectName("label_RailA_48")
        self.label_RailA_49 = QtWidgets.QLabel(self.frame)
        self.label_RailA_49.setGeometry(QtCore.QRect(351, 442, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_49.setFont(font)
        self.label_RailA_49.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_49.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_49.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_49.setObjectName("label_RailA_49")
        self.label_RailA_50 = QtWidgets.QLabel(self.frame)
        self.label_RailA_50.setGeometry(QtCore.QRect(380, 120, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_50.setFont(font)
        self.label_RailA_50.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_50.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_50.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_50.setObjectName("label_RailA_50")
        self.frame_2 = QtWidgets.QFrame(self.frame_display)
        self.frame_2.setGeometry(QtCore.QRect(30, 245, 551, 101))
        self.frame_2.setStyleSheet("border: 1px solid black;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_pmbus_vid_resolution = QtWidgets.QLabel(self.frame_2)
        self.label_pmbus_vid_resolution.setGeometry(QtCore.QRect(20, 50, 190, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_pmbus_vid_resolution.setFont(font)
        self.label_pmbus_vid_resolution.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_pmbus_vid_resolution.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_pmbus_vid_resolution.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pmbus_vid_resolution.setObjectName("label_pmbus_vid_resolution")
        self.label_display_RailB_2 = QtWidgets.QLabel(self.frame_display)
        self.label_display_RailB_2.setGeometry(QtCore.QRect(420, 30, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_display_RailB_2.setFont(font)
        self.label_display_RailB_2.setStyleSheet("border: none;")
        self.label_display_RailB_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_display_RailB_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_display_RailB_2.setObjectName("label_display_RailB_2")
        self.label_display_RailA_2 = QtWidgets.QLabel(self.frame_display)
        self.label_display_RailA_2.setGeometry(QtCore.QRect(300, 30, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_display_RailA_2.setFont(font)
        self.label_display_RailA_2.setStyleSheet("border: none;")
        self.label_display_RailA_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_display_RailA_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_display_RailA_2.setObjectName("label_display_RailA_2")
        self.label_RailA_38 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_38.setGeometry(QtCore.QRect(520, 80, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_38.setFont(font)
        self.label_RailA_38.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_38.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_38.setObjectName("label_RailA_38")
        self.label_RailA_39 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_39.setGeometry(QtCore.QRect(520, 120, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_39.setFont(font)
        self.label_RailA_39.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_39.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_39.setObjectName("label_RailA_39")
        self.label_RailA_40 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_40.setGeometry(QtCore.QRect(420, 380, 21, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_40.setFont(font)
        self.label_RailA_40.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_40.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_40.setObjectName("label_RailA_40")
        self.label_RailA_51 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_51.setGeometry(QtCore.QRect(240, 290, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_51.setFont(font)
        self.label_RailA_51.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_51.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_51.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_51.setObjectName("label_RailA_51")
        self.label_RailA_52 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_52.setGeometry(QtCore.QRect(250, 150, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_52.setFont(font)
        self.label_RailA_52.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_52.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_52.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_52.setObjectName("label_RailA_52")
        self.label_RailA_53 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_53.setGeometry(QtCore.QRect(250, 110, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_53.setFont(font)
        self.label_RailA_53.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_53.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_53.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_53.setObjectName("label_RailA_53")
        self.label_RailA_54 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_54.setGeometry(QtCore.QRect(250, 80, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_54.setFont(font)
        self.label_RailA_54.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_54.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_54.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_54.setObjectName("label_RailA_54")
        self.label_RailA_60 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_60.setGeometry(QtCore.QRect(270, 380, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_60.setFont(font)
        self.label_RailA_60.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_60.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_60.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_60.setObjectName("label_RailA_60")
        self.checkBox_PMBus_override_railA_2 = QtWidgets.QCheckBox(self.frame_display)
        self.checkBox_PMBus_override_railA_2.setGeometry(QtCore.QRect(420, 255, 130, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_PMBus_override_railA_2.sizePolicy().hasHeightForWidth())
        self.checkBox_PMBus_override_railA_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.checkBox_PMBus_override_railA_2.setFont(font)
        self.checkBox_PMBus_override_railA_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_PMBus_override_railA_2.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.checkBox_PMBus_override_railA_2.setObjectName("checkBox_PMBus_override_railA_2")
        self.frame_2.raise_()
        self.frame.raise_()
        self.pushButton_Discard.raise_()
        self.pushButton_Save.raise_()
        self.label_RailA_4.raise_()
        self.label_RailA_6.raise_()
        self.label_RailA_8.raise_()
        self.lineEdit_icc_max_railA.raise_()
        self.lineEdit_temp_max.raise_()
        self.lineEdit_vid_max_railA.raise_()
        self.lineEdit_icc_max_railB.raise_()
        self.lineEdit_vid_max_railB.raise_()
        self.label_RailA_12.raise_()
        self.comboBox_slewrate_fast_RailA.raise_()
        self.comboBox_slewrate_fast_RailB.raise_()
        self.checkBox_PMBus_override_railA.raise_()
        self.comboBox_vid_resolution_RailA.raise_()
        self.comboBox_vid_resolution_RailB.raise_()
        self.label_display_RailB_2.raise_()
        self.label_display_RailA_2.raise_()
        self.label_RailA_38.raise_()
        self.label_RailA_39.raise_()
        self.label_RailA_40.raise_()
        self.label_RailA_51.raise_()
        self.label_RailA_52.raise_()
        self.label_RailA_53.raise_()
        self.label_RailA_54.raise_()
        self.label_RailA_60.raise_()
        self.checkBox_PMBus_override_railA_2.raise_()
        label_main_SVI2_Configuration.setCentralWidget(self.centralwidget)

        self.retranslateUi(label_main_SVI2_Configuration)
        QtCore.QMetaObject.connectSlotsByName(label_main_SVI2_Configuration)

    def retranslateUi(self, label_main_SVI2_Configuration):
        _translate = QtCore.QCoreApplication.translate
        label_main_SVI2_Configuration.setWindowTitle(_translate("label_main_SVI2_Configuration", "Device Configuration"))
        self.label_SVID_Configuration.setText(_translate("label_main_SVI2_Configuration", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">SVI2</span><span style=\" font-size:14pt;\"> Configuration</span></p></body></html>"))
        self.pushButton_Discard.setText(_translate("label_main_SVI2_Configuration", "Discard"))
        self.pushButton_Save.setText(_translate("label_main_SVI2_Configuration", "Save"))
        self.label_RailA_4.setText(_translate("label_main_SVI2_Configuration", "VID Max"))
        self.label_RailA_6.setText(_translate("label_main_SVI2_Configuration", "ICC Max"))
        self.label_RailA_8.setText(_translate("label_main_SVI2_Configuration", "Temp Max"))
        self.lineEdit_icc_max_railA.setPlaceholderText(_translate("label_main_SVI2_Configuration", "125"))
        self.lineEdit_temp_max.setPlaceholderText(_translate("label_main_SVI2_Configuration", "27"))
        self.lineEdit_vid_max_railA.setPlaceholderText(_translate("label_main_SVI2_Configuration", "1.25"))
        self.lineEdit_icc_max_railB.setPlaceholderText(_translate("label_main_SVI2_Configuration", "125"))
        self.lineEdit_vid_max_railB.setPlaceholderText(_translate("label_main_SVI2_Configuration", "1.25"))
        self.label_RailA_12.setText(_translate("label_main_SVI2_Configuration", "VOUT_TRANSITION_RATE"))
        self.comboBox_slewrate_fast_RailA.setItemText(0, _translate("label_main_SVI2_Configuration", "0.12mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(1, _translate("label_main_SVI2_Configuration", "0.5mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(2, _translate("label_main_SVI2_Configuration", "1mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(3, _translate("label_main_SVI2_Configuration", "2.5mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(4, _translate("label_main_SVI2_Configuration", "5mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(5, _translate("label_main_SVI2_Configuration", "7.5mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(6, _translate("label_main_SVI2_Configuration", "10mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(7, _translate("label_main_SVI2_Configuration", "12.5mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(8, _translate("label_main_SVI2_Configuration", "15mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(9, _translate("label_main_SVI2_Configuration", "17.5mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(10, _translate("label_main_SVI2_Configuration", "20mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(11, _translate("label_main_SVI2_Configuration", "22.5mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(12, _translate("label_main_SVI2_Configuration", "25mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(13, _translate("label_main_SVI2_Configuration", "27.5mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(14, _translate("label_main_SVI2_Configuration", "30mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(15, _translate("label_main_SVI2_Configuration", "32.5mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(16, _translate("label_main_SVI2_Configuration", "35mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(17, _translate("label_main_SVI2_Configuration", "37.5mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(18, _translate("label_main_SVI2_Configuration", "40mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(19, _translate("label_main_SVI2_Configuration", "48mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(20, _translate("label_main_SVI2_Configuration", "60mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(21, _translate("label_main_SVI2_Configuration", "80mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(22, _translate("label_main_SVI2_Configuration", "96mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(23, _translate("label_main_SVI2_Configuration", "125mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(0, _translate("label_main_SVI2_Configuration", "0.12mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(1, _translate("label_main_SVI2_Configuration", "0.5mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(2, _translate("label_main_SVI2_Configuration", "1mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(3, _translate("label_main_SVI2_Configuration", "2.5mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(4, _translate("label_main_SVI2_Configuration", "5mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(5, _translate("label_main_SVI2_Configuration", "7.5mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(6, _translate("label_main_SVI2_Configuration", "10mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(7, _translate("label_main_SVI2_Configuration", "12.5mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(8, _translate("label_main_SVI2_Configuration", "15mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(9, _translate("label_main_SVI2_Configuration", "17.5mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(10, _translate("label_main_SVI2_Configuration", "20mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(11, _translate("label_main_SVI2_Configuration", "22.5mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(12, _translate("label_main_SVI2_Configuration", "25mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(13, _translate("label_main_SVI2_Configuration", "27.5mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(14, _translate("label_main_SVI2_Configuration", "30mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(15, _translate("label_main_SVI2_Configuration", "32.5mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(16, _translate("label_main_SVI2_Configuration", "35mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(17, _translate("label_main_SVI2_Configuration", "37.5mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(18, _translate("label_main_SVI2_Configuration", "40mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(19, _translate("label_main_SVI2_Configuration", "48mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(20, _translate("label_main_SVI2_Configuration", "60mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(21, _translate("label_main_SVI2_Configuration", "80mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(22, _translate("label_main_SVI2_Configuration", "96mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(23, _translate("label_main_SVI2_Configuration", "125mV/μs"))
        self.checkBox_PMBus_override_railA.setText(_translate("label_main_SVI2_Configuration", "PMBus Vid override"))
        self.comboBox_vid_resolution_RailA.setItemText(0, _translate("label_main_SVI2_Configuration", "5mV"))
        self.comboBox_vid_resolution_RailA.setItemText(1, _translate("label_main_SVI2_Configuration", "6.25mV"))
        self.comboBox_vid_resolution_RailA.setItemText(2, _translate("label_main_SVI2_Configuration", "10mV"))
        self.comboBox_vid_resolution_RailB.setItemText(0, _translate("label_main_SVI2_Configuration", "5mV"))
        self.comboBox_vid_resolution_RailB.setItemText(1, _translate("label_main_SVI2_Configuration", "6.25mV"))
        self.comboBox_vid_resolution_RailB.setItemText(2, _translate("label_main_SVI2_Configuration", "10mV"))
        self.lineEdit_PVID_A_6.setPlaceholderText(_translate("label_main_SVI2_Configuration", "1.25"))
        self.label_RailA_18.setText(_translate("label_main_SVI2_Configuration", "0  :"))
        self.lineEdit_PVID_A_7.setPlaceholderText(_translate("label_main_SVI2_Configuration", "1.25"))
        self.lineEdit_PVID_B_6.setPlaceholderText(_translate("label_main_SVI2_Configuration", "1.25"))
        self.lineEdit_PVID_A_3.setPlaceholderText(_translate("label_main_SVI2_Configuration", "1.25"))
        self.lineEdit_PVID_B_1.setPlaceholderText(_translate("label_main_SVI2_Configuration", "1.25"))
        self.label_RailA_20.setText(_translate("label_main_SVI2_Configuration", "2  :"))
        self.lineEdit_PVID_A_4.setPlaceholderText(_translate("label_main_SVI2_Configuration", "1.25"))
        self.lineEdit_PVID_A_0.setPlaceholderText(_translate("label_main_SVI2_Configuration", "1.25"))
        self.lineEdit_PVID_B_3.setPlaceholderText(_translate("label_main_SVI2_Configuration", "1.25"))
        self.lineEdit_PVID_A_5.setPlaceholderText(_translate("label_main_SVI2_Configuration", "1.25"))
        self.lineEdit_PVID_A_2.setPlaceholderText(_translate("label_main_SVI2_Configuration", "1.25"))
        self.lineEdit_PVID_B_0.setPlaceholderText(_translate("label_main_SVI2_Configuration", "1.25"))
        self.label_RailA_19.setText(_translate("label_main_SVI2_Configuration", "1  :"))
        self.label_RailA_22.setText(_translate("label_main_SVI2_Configuration", "4  :"))
        self.lineEdit_PVID_A_1.setPlaceholderText(_translate("label_main_SVI2_Configuration", "1.25"))
        self.label_RailA_21.setText(_translate("label_main_SVI2_Configuration", "3  :"))
        self.label_RailA_27.setText(_translate("label_main_SVI2_Configuration", "7  :"))
        self.label_RailA_24.setText(_translate("label_main_SVI2_Configuration", "6  :"))
        self.label_RailA_23.setText(_translate("label_main_SVI2_Configuration", "5  :"))
        self.lineEdit_PVID_B_2.setPlaceholderText(_translate("label_main_SVI2_Configuration", "1.25"))
        self.lineEdit_PVID_B_5.setPlaceholderText(_translate("label_main_SVI2_Configuration", "1.25"))
        self.lineEdit_PVID_B_7.setPlaceholderText(_translate("label_main_SVI2_Configuration", "1.25"))
        self.lineEdit_PVID_B_4.setPlaceholderText(_translate("label_main_SVI2_Configuration", "1.25"))
        self.label_EnableA.setText(_translate("label_main_SVI2_Configuration", "Enable"))
        self.label_DisableA.setText(_translate("label_main_SVI2_Configuration", "Disable"))
        self.label_RailA_17.setText(_translate("label_main_SVI2_Configuration", "PVID-Table"))
        self.label_display_RailA.setText(_translate("label_main_SVI2_Configuration", "Alpha"))
        self.label_display_RailB.setText(_translate("label_main_SVI2_Configuration", "Beta"))
        self.label_RailA_42.setText(_translate("label_main_SVI2_Configuration", "V"))
        self.label_RailA_43.setText(_translate("label_main_SVI2_Configuration", "V"))
        self.label_RailA_44.setText(_translate("label_main_SVI2_Configuration", "V"))
        self.label_RailA_45.setText(_translate("label_main_SVI2_Configuration", "V"))
        self.label_RailA_46.setText(_translate("label_main_SVI2_Configuration", "V"))
        self.label_RailA_47.setText(_translate("label_main_SVI2_Configuration", "V"))
        self.label_RailA_48.setText(_translate("label_main_SVI2_Configuration", "V"))
        self.label_RailA_49.setText(_translate("label_main_SVI2_Configuration", "V"))
        self.label_RailA_50.setText(_translate("label_main_SVI2_Configuration", "V"))
        self.label_pmbus_vid_resolution.setText(_translate("label_main_SVI2_Configuration", "VID resolution"))
        self.label_display_RailB_2.setText(_translate("label_main_SVI2_Configuration", "Beta"))
        self.label_display_RailA_2.setText(_translate("label_main_SVI2_Configuration", "Alpha"))
        self.label_RailA_38.setText(_translate("label_main_SVI2_Configuration", "A"))
        self.label_RailA_39.setText(_translate("label_main_SVI2_Configuration", "V"))
        self.label_RailA_40.setText(_translate("label_main_SVI2_Configuration", "°C"))
        self.label_RailA_51.setText(_translate("label_main_SVI2_Configuration", "  :"))
        self.label_RailA_52.setText(_translate("label_main_SVI2_Configuration", "  :"))
        self.label_RailA_53.setText(_translate("label_main_SVI2_Configuration", "  :"))
        self.label_RailA_54.setText(_translate("label_main_SVI2_Configuration", "  :"))
        self.label_RailA_60.setText(_translate("label_main_SVI2_Configuration", "  :"))
        self.checkBox_PMBus_override_railA_2.setText(_translate("label_main_SVI2_Configuration", "PMBus Vid override"))

