# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Telemetry_senstivity.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Telemetry_senstivity(object):
    def setupUi(self, Telemetry_senstivity):
        Telemetry_senstivity.setObjectName("Telemetry_senstivity")
        Telemetry_senstivity.resize(541, 435)
        self.centralwidget = QtWidgets.QWidget(Telemetry_senstivity)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Senstivity = QtWidgets.QLabel(self.centralwidget)
        self.label_Senstivity.setGeometry(QtCore.QRect(10, 0, 521, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_Senstivity.setFont(font)
        self.label_Senstivity.setStyleSheet("background-color: rgb(38, 23, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_Senstivity.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Senstivity.setObjectName("label_Senstivity")
        self.frame_display = QtWidgets.QFrame(self.centralwidget)
        self.frame_display.setGeometry(QtCore.QRect(10, 45, 521, 381))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame_display.setFont(font)
        self.frame_display.setStyleSheet("\n"
"border: 2px solid darkorange;\n"
"border-radius:0px;\n"
"")
        self.frame_display.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_display.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_display.setObjectName("frame_display")
        self.pushButton_Discard = QtWidgets.QPushButton(self.frame_display)
        self.pushButton_Discard.setGeometry(QtCore.QRect(120, 310, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Discard.setFont(font)
        self.pushButton_Discard.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Discard.setStyleSheet("QPushButton{background-color: rgb(219, 100, 17);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid red;\n"
"background-color: orange;\n"
"}\n"
"")
        self.pushButton_Discard.setObjectName("pushButton_Discard")
        self.pushButton_Save = QtWidgets.QPushButton(self.frame_display)
        self.pushButton_Save.setGeometry(QtCore.QRect(280, 310, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Save.setStyleSheet("QPushButton{background-color: rgb(0, 153, 74);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid green;\n"
"background-color:lightgreen;\n"
"}\n"
"")
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.lineEdit_tmonB_scaling = QtWidgets.QLineEdit(self.frame_display)
        self.lineEdit_tmonB_scaling.setGeometry(QtCore.QRect(305, 195, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_tmonB_scaling.setFont(font)
        self.lineEdit_tmonB_scaling.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_tmonB_scaling.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tmonB_scaling.setObjectName("lineEdit_tmonB_scaling")
        self.label_RailA_54 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_54.setGeometry(QtCore.QRect(240, 70, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_54.setFont(font)
        self.label_RailA_54.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_54.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_54.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_54.setObjectName("label_RailA_54")
        self.label_RailA_6 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_6.setGeometry(QtCore.QRect(50, 70, 141, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_6.setFont(font)
        self.label_RailA_6.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_6.setObjectName("label_RailA_6")
        self.lineEdit_ioutA_scaling = QtWidgets.QLineEdit(self.frame_display)
        self.lineEdit_ioutA_scaling.setGeometry(QtCore.QRect(305, 75, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_ioutA_scaling.setFont(font)
        self.lineEdit_ioutA_scaling.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_ioutA_scaling.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ioutA_scaling.setObjectName("lineEdit_ioutA_scaling")
        self.label_RailA_39 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_39.setGeometry(QtCore.QRect(415, 200, 45, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_39.setFont(font)
        self.label_RailA_39.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_39.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_39.setObjectName("label_RailA_39")
        self.lineEdit_tmonA_scaling = QtWidgets.QLineEdit(self.frame_display)
        self.lineEdit_tmonA_scaling.setGeometry(QtCore.QRect(305, 115, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_tmonA_scaling.setFont(font)
        self.lineEdit_tmonA_scaling.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_tmonA_scaling.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tmonA_scaling.setObjectName("lineEdit_tmonA_scaling")
        self.lineEdit_ioutB_scaling = QtWidgets.QLineEdit(self.frame_display)
        self.lineEdit_ioutB_scaling.setGeometry(QtCore.QRect(305, 155, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_ioutB_scaling.setFont(font)
        self.lineEdit_ioutB_scaling.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_ioutB_scaling.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ioutB_scaling.setObjectName("lineEdit_ioutB_scaling")
        self.label_RailA_53 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_53.setGeometry(QtCore.QRect(240, 110, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_53.setFont(font)
        self.label_RailA_53.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_53.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_53.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_53.setObjectName("label_RailA_53")
        self.label_RailA_4 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_4.setGeometry(QtCore.QRect(50, 110, 131, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_4.setFont(font)
        self.label_RailA_4.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_4.setObjectName("label_RailA_4")
        self.label_RailA_5 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_5.setGeometry(QtCore.QRect(50, 230, 171, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_5.setFont(font)
        self.label_RailA_5.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_5.setObjectName("label_RailA_5")
        self.label_RailA_40 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_40.setGeometry(QtCore.QRect(415, 160, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_40.setFont(font)
        self.label_RailA_40.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_40.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_40.setObjectName("label_RailA_40")
        self.label_RailA_7 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_7.setGeometry(QtCore.QRect(50, 190, 131, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_7.setFont(font)
        self.label_RailA_7.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_7.setObjectName("label_RailA_7")
        self.label_RailA_55 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_55.setGeometry(QtCore.QRect(240, 150, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_55.setFont(font)
        self.label_RailA_55.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_55.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_55.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_55.setObjectName("label_RailA_55")
        self.label_RailA_56 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_56.setGeometry(QtCore.QRect(240, 190, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_56.setFont(font)
        self.label_RailA_56.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_56.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_56.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_56.setObjectName("label_RailA_56")
        self.label_RailA_8 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_8.setGeometry(QtCore.QRect(50, 150, 141, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_8.setFont(font)
        self.label_RailA_8.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_8.setObjectName("label_RailA_8")
        self.label_RailA_41 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_41.setGeometry(QtCore.QRect(415, 75, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_41.setFont(font)
        self.label_RailA_41.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_41.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_41.setObjectName("label_RailA_41")
        self.label_RailA_42 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_42.setGeometry(QtCore.QRect(415, 115, 45, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_42.setFont(font)
        self.label_RailA_42.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_42.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_42.setObjectName("label_RailA_42")
        self.label_RailA_57 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_57.setGeometry(QtCore.QRect(240, 230, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_57.setFont(font)
        self.label_RailA_57.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_57.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_57.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_57.setObjectName("label_RailA_57")
        self.lineEdit_imon_aux_scaling = QtWidgets.QLineEdit(self.frame_display)
        self.lineEdit_imon_aux_scaling.setGeometry(QtCore.QRect(305, 235, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_imon_aux_scaling.setFont(font)
        self.lineEdit_imon_aux_scaling.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_imon_aux_scaling.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_imon_aux_scaling.setObjectName("lineEdit_imon_aux_scaling")
        self.label_RailA_43 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_43.setGeometry(QtCore.QRect(415, 235, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_43.setFont(font)
        self.label_RailA_43.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_43.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_43.setObjectName("label_RailA_43")
        Telemetry_senstivity.setCentralWidget(self.centralwidget)

        self.retranslateUi(Telemetry_senstivity)
        QtCore.QMetaObject.connectSlotsByName(Telemetry_senstivity)

    def retranslateUi(self, Telemetry_senstivity):
        _translate = QtCore.QCoreApplication.translate
        Telemetry_senstivity.setWindowTitle(_translate("Telemetry_senstivity", "Telemetry"))
        self.label_Senstivity.setText(_translate("Telemetry_senstivity", "<html><head/><body><p><span style=\" font-size:14pt;\">Sensitivity</span></p></body></html>"))
        self.pushButton_Discard.setText(_translate("Telemetry_senstivity", "Discard"))
        self.pushButton_Save.setText(_translate("Telemetry_senstivity", "Save"))
        self.lineEdit_tmonB_scaling.setPlaceholderText(_translate("Telemetry_senstivity", "10"))
        self.label_RailA_54.setText(_translate("Telemetry_senstivity", "  :"))
        self.label_RailA_6.setText(_translate("Telemetry_senstivity", "IOUTA Scaling"))
        self.lineEdit_ioutA_scaling.setPlaceholderText(_translate("Telemetry_senstivity", "1.25"))
        self.label_RailA_39.setText(_translate("Telemetry_senstivity", "mV / °C"))
        self.lineEdit_tmonA_scaling.setPlaceholderText(_translate("Telemetry_senstivity", "-1"))
        self.lineEdit_ioutB_scaling.setPlaceholderText(_translate("Telemetry_senstivity", "0.25"))
        self.label_RailA_53.setText(_translate("Telemetry_senstivity", "  :"))
        self.label_RailA_4.setText(_translate("Telemetry_senstivity", "TmonA Scaling"))
        self.label_RailA_5.setText(_translate("Telemetry_senstivity", "IMON_AUX Scaling"))
        self.label_RailA_40.setText(_translate("Telemetry_senstivity", "mV / A"))
        self.label_RailA_7.setText(_translate("Telemetry_senstivity", "TmonB Scaling"))
        self.label_RailA_55.setText(_translate("Telemetry_senstivity", "  :"))
        self.label_RailA_56.setText(_translate("Telemetry_senstivity", "  :"))
        self.label_RailA_8.setText(_translate("Telemetry_senstivity", "IOUTB Scaling"))
        self.label_RailA_41.setText(_translate("Telemetry_senstivity", "mV / A"))
        self.label_RailA_42.setText(_translate("Telemetry_senstivity", "mV / °C"))
        self.label_RailA_57.setText(_translate("Telemetry_senstivity", "  :"))
        self.lineEdit_imon_aux_scaling.setPlaceholderText(_translate("Telemetry_senstivity", "10"))
        self.label_RailA_43.setText(_translate("Telemetry_senstivity", "mV / A"))

