# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fault_Configuration.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Fault_config(object):
    def setupUi(self, Fault_config):
        Fault_config.setObjectName("Fault_config")
        Fault_config.resize(880, 576)
        self.centralwidget = QtWidgets.QWidget(Fault_config)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Transient = QtWidgets.QLabel(self.centralwidget)
        self.label_Transient.setGeometry(QtCore.QRect(10, 0, 861, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_Transient.setFont(font)
        self.label_Transient.setStyleSheet("background-color: rgb(38, 23, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_Transient.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Transient.setObjectName("label_Transient")
        self.frame_phase_display = QtWidgets.QFrame(self.centralwidget)
        self.frame_phase_display.setGeometry(QtCore.QRect(10, 40, 861, 531))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame_phase_display.setFont(font)
        self.frame_phase_display.setStyleSheet("\n"
"border: 2px solid darkorange;\n"
"border-radius:0px;\n"
"")
        self.frame_phase_display.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_phase_display.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_phase_display.setObjectName("frame_phase_display")
        self.pushButton_Discard = QtWidgets.QPushButton(self.frame_phase_display)
        self.pushButton_Discard.setGeometry(QtCore.QRect(310, 480, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Discard.setFont(font)
        self.pushButton_Discard.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Discard.setStyleSheet("QPushButton{background-color: rgb(219, 100, 17);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid red;\n"
"background-color: orange;\n"
"}\n"
"")
        self.pushButton_Discard.setObjectName("pushButton_Discard")
        self.pushButton_Save = QtWidgets.QPushButton(self.frame_phase_display)
        self.pushButton_Save.setGeometry(QtCore.QRect(480, 480, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Save.setStyleSheet("QPushButton{background-color: rgb(0, 153, 74);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid green;\n"
"background-color:lightgreen;\n"
"}\n"
"")
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.label_RailA_3 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_3.setGeometry(QtCore.QRect(50, 30, 331, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_3.setFont(font)
        self.label_RailA_3.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_3.setObjectName("label_RailA_3")
        self.label_RailA_4 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_4.setGeometry(QtCore.QRect(50, 280, 311, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_4.setFont(font)
        self.label_RailA_4.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_4.setObjectName("label_RailA_4")
        self.label_RailA_5 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_5.setGeometry(QtCore.QRect(50, 320, 301, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_5.setFont(font)
        self.label_RailA_5.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_5.setObjectName("label_RailA_5")
        self.label_RailA_6 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_6.setGeometry(QtCore.QRect(50, 110, 190, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_6.setFont(font)
        self.label_RailA_6.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_6.setObjectName("label_RailA_6")
        self.label_RailA_12 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_12.setGeometry(QtCore.QRect(50, 70, 330, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_12.setFont(font)
        self.label_RailA_12.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_12.setObjectName("label_RailA_12")
        self.comboBox_PhaseOverCurrent_RailA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_PhaseOverCurrent_RailA.setGeometry(QtCore.QRect(545, 360, 81, 25))
        self.comboBox_PhaseOverCurrent_RailA.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_PhaseOverCurrent_RailA.setObjectName("comboBox_PhaseOverCurrent_RailA")
        self.comboBox_PhaseOverCurrent_RailA.addItem("")
        self.comboBox_PhaseOverCurrent_RailA.addItem("")
        self.comboBox_PhaseOverCurrent_RailA.addItem("")
        self.comboBox_PhaseOverCurrent_RailA.addItem("")
        self.comboBox_PhaseOverCurrent_RailA.addItem("")
        self.comboBox_PhaseOverCurrent_RailA.addItem("")
        self.comboBox_PhaseOverCurrent_RailA.addItem("")
        self.comboBox_PhaseOverCurrent_RailA.addItem("")
        self.comboBox_PhaseOverCurrent_RailA.addItem("")
        self.comboBox_PhaseOverCurrent_RailA.addItem("")
        self.comboBox_PhaseOverCurrent_RailA.addItem("")
        self.comboBox_PhaseOverCurrent_RailA.addItem("")
        self.comboBox_PhaseOverCurrent_RailA.addItem("")
        self.comboBox_PhaseOverCurrent_RailA.addItem("")
        self.comboBox_PhaseOverCurrent_RailA.addItem("")
        self.comboBox_PhaseOverCurrent_RailA.addItem("")
        self.label_display_RailB = QtWidgets.QLabel(self.frame_phase_display)
        self.label_display_RailB.setGeometry(QtCore.QRect(680, 240, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_display_RailB.setFont(font)
        self.label_display_RailB.setStyleSheet("border: none;")
        self.label_display_RailB.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_display_RailB.setAlignment(QtCore.Qt.AlignCenter)
        self.label_display_RailB.setObjectName("label_display_RailB")
        self.label_display_RailA = QtWidgets.QLabel(self.frame_phase_display)
        self.label_display_RailA.setGeometry(QtCore.QRect(530, 240, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_display_RailA.setFont(font)
        self.label_display_RailA.setStyleSheet("border: none;")
        self.label_display_RailA.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_display_RailA.setAlignment(QtCore.Qt.AlignCenter)
        self.label_display_RailA.setObjectName("label_display_RailA")
        self.label_RailA_15 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_15.setGeometry(QtCore.QRect(440, 30, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_15.setFont(font)
        self.label_RailA_15.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RailA_15.setObjectName("label_RailA_15")
        self.label_RailA_26 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_26.setGeometry(QtCore.QRect(440, 320, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_26.setFont(font)
        self.label_RailA_26.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_26.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_26.setObjectName("label_RailA_26")
        self.label_RailA_28 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_28.setGeometry(QtCore.QRect(440, 280, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_28.setFont(font)
        self.label_RailA_28.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_28.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_28.setObjectName("label_RailA_28")
        self.label_RailA_29 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_29.setGeometry(QtCore.QRect(440, 70, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_29.setFont(font)
        self.label_RailA_29.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_29.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_29.setObjectName("label_RailA_29")
        self.label_RailA_30 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_30.setGeometry(QtCore.QRect(440, 110, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_30.setFont(font)
        self.label_RailA_30.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_30.setObjectName("label_RailA_30")
        self.label_RailA_31 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_31.setGeometry(QtCore.QRect(440, 360, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_31.setFont(font)
        self.label_RailA_31.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_31.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_31.setObjectName("label_RailA_31")
        self.comboBox_temp_fault_threshold = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_temp_fault_threshold.setGeometry(QtCore.QRect(580, 70, 160, 25))
        self.comboBox_temp_fault_threshold.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_temp_fault_threshold.setObjectName("comboBox_temp_fault_threshold")
        self.comboBox_temp_fault_threshold.addItem("")
        self.comboBox_temp_fault_threshold.addItem("")
        self.comboBox_temp_fault_threshold.addItem("")
        self.comboBox_temp_fault_threshold.addItem("")
        self.comboBox_trackingUVP_RailA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_trackingUVP_RailA.setGeometry(QtCore.QRect(545, 280, 81, 25))
        self.comboBox_trackingUVP_RailA.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_trackingUVP_RailA.setObjectName("comboBox_trackingUVP_RailA")
        self.comboBox_trackingUVP_RailA.addItem("")
        self.comboBox_trackingUVP_RailA.addItem("")
        self.comboBox_trackingUVP_RailA.addItem("")
        self.comboBox_trackingUVP_RailA.addItem("")
        self.comboBox_trackingUVP_RailA.addItem("")
        self.comboBox_trackingUVP_RailA.addItem("")
        self.comboBox_trackingUVP_RailA.addItem("")
        self.comboBox_trackingUVP_RailA.addItem("")
        self.label_RailA_13 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_13.setGeometry(QtCore.QRect(50, 360, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_13.setFont(font)
        self.label_RailA_13.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_13.setObjectName("label_RailA_13")
        self.label_RailA_16 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_16.setGeometry(QtCore.QRect(50, 400, 400, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_16.setFont(font)
        self.label_RailA_16.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_16.setObjectName("label_RailA_16")
        self.label_RailA_17 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_17.setGeometry(QtCore.QRect(50, 440, 400, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_17.setFont(font)
        self.label_RailA_17.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_17.setObjectName("label_RailA_17")
        self.label_RailA_33 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_33.setGeometry(QtCore.QRect(440, 400, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_33.setFont(font)
        self.label_RailA_33.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_33.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_33.setObjectName("label_RailA_33")
        self.label_RailA_35 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_35.setGeometry(QtCore.QRect(440, 440, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_35.setFont(font)
        self.label_RailA_35.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_35.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_35.setObjectName("label_RailA_35")
        self.comboBox_AbsoluteOVP_RailA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_AbsoluteOVP_RailA.setGeometry(QtCore.QRect(545, 400, 81, 25))
        self.comboBox_AbsoluteOVP_RailA.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_AbsoluteOVP_RailA.setObjectName("comboBox_AbsoluteOVP_RailA")
        self.comboBox_AbsoluteOVP_RailA.addItem("")
        self.comboBox_AbsoluteOVP_RailA.addItem("")
        self.comboBox_AbsoluteOVP_RailA.addItem("")
        self.comboBox_AbsoluteOVP_RailA.addItem("")
        self.comboBox_AbsoluteOVP_RailA.addItem("")
        self.comboBox_AbsoluteOVP_RailA.addItem("")
        self.comboBox_AbsoluteOVP_RailA.addItem("")
        self.comboBox_AbsoluteOVP_RailA.addItem("")
        self.comboBox_voutTurnOnTime_RailA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_voutTurnOnTime_RailA.setGeometry(QtCore.QRect(545, 440, 81, 25))
        self.comboBox_voutTurnOnTime_RailA.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_voutTurnOnTime_RailA.setObjectName("comboBox_voutTurnOnTime_RailA")
        self.comboBox_voutTurnOnTime_RailA.addItem("")
        self.comboBox_voutTurnOnTime_RailA.addItem("")
        self.comboBox_voutTurnOnTime_RailA.addItem("")
        self.comboBox_voutTurnOnTime_RailA.addItem("")
        self.comboBox_iout_fault_limit = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_iout_fault_limit.setGeometry(QtCore.QRect(580, 110, 160, 25))
        self.comboBox_iout_fault_limit.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_iout_fault_limit.setObjectName("comboBox_iout_fault_limit")
        self.comboBox_iout_fault_limit.addItem("")
        self.comboBox_iout_fault_limit.addItem("")
        self.comboBox_iout_fault_limit.addItem("")
        self.comboBox_iout_fault_limit.addItem("")
        self.groupBox = QtWidgets.QGroupBox(self.frame_phase_display)
        self.groupBox.setGeometry(QtCore.QRect(480, 30, 371, 31))
        self.groupBox.setStyleSheet("border:none;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton_soft_shutdown = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_soft_shutdown.setGeometry(QtCore.QRect(10, 10, 211, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_soft_shutdown.setFont(font)
        self.radioButton_soft_shutdown.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_soft_shutdown.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.radioButton_soft_shutdown.setObjectName("radioButton_soft_shutdown")
        self.radioButton_immediate_shutdown = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_immediate_shutdown.setGeometry(QtCore.QRect(210, 10, 221, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_immediate_shutdown.setFont(font)
        self.radioButton_immediate_shutdown.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_immediate_shutdown.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.radioButton_immediate_shutdown.setObjectName("radioButton_immediate_shutdown")
        self.comboBox_trackingUVP_RailB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_trackingUVP_RailB.setGeometry(QtCore.QRect(695, 280, 81, 25))
        self.comboBox_trackingUVP_RailB.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_trackingUVP_RailB.setObjectName("comboBox_trackingUVP_RailB")
        self.comboBox_trackingUVP_RailB.addItem("")
        self.comboBox_trackingUVP_RailB.addItem("")
        self.comboBox_trackingUVP_RailB.addItem("")
        self.comboBox_trackingUVP_RailB.addItem("")
        self.comboBox_trackingUVP_RailB.addItem("")
        self.comboBox_trackingUVP_RailB.addItem("")
        self.comboBox_trackingUVP_RailB.addItem("")
        self.comboBox_trackingUVP_RailB.addItem("")
        self.comboBox_trackingOVP_RailA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_trackingOVP_RailA.setGeometry(QtCore.QRect(545, 320, 81, 25))
        self.comboBox_trackingOVP_RailA.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_trackingOVP_RailA.setObjectName("comboBox_trackingOVP_RailA")
        self.comboBox_trackingOVP_RailA.addItem("")
        self.comboBox_trackingOVP_RailA.addItem("")
        self.comboBox_trackingOVP_RailA.addItem("")
        self.comboBox_trackingOVP_RailA.addItem("")
        self.comboBox_trackingOVP_RailA.addItem("")
        self.comboBox_trackingOVP_RailA.addItem("")
        self.comboBox_trackingOVP_RailA.addItem("")
        self.comboBox_trackingOVP_RailA.addItem("")
        self.comboBox_trackingOVP_RailB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_trackingOVP_RailB.setGeometry(QtCore.QRect(695, 320, 81, 25))
        self.comboBox_trackingOVP_RailB.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_trackingOVP_RailB.setObjectName("comboBox_trackingOVP_RailB")
        self.comboBox_trackingOVP_RailB.addItem("")
        self.comboBox_trackingOVP_RailB.addItem("")
        self.comboBox_trackingOVP_RailB.addItem("")
        self.comboBox_trackingOVP_RailB.addItem("")
        self.comboBox_trackingOVP_RailB.addItem("")
        self.comboBox_trackingOVP_RailB.addItem("")
        self.comboBox_trackingOVP_RailB.addItem("")
        self.comboBox_trackingOVP_RailB.addItem("")
        self.comboBox_PhaseOverCurrent_RailB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_PhaseOverCurrent_RailB.setGeometry(QtCore.QRect(695, 360, 81, 25))
        self.comboBox_PhaseOverCurrent_RailB.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_PhaseOverCurrent_RailB.setObjectName("comboBox_PhaseOverCurrent_RailB")
        self.comboBox_PhaseOverCurrent_RailB.addItem("")
        self.comboBox_PhaseOverCurrent_RailB.addItem("")
        self.comboBox_PhaseOverCurrent_RailB.addItem("")
        self.comboBox_PhaseOverCurrent_RailB.addItem("")
        self.comboBox_PhaseOverCurrent_RailB.addItem("")
        self.comboBox_PhaseOverCurrent_RailB.addItem("")
        self.comboBox_PhaseOverCurrent_RailB.addItem("")
        self.comboBox_PhaseOverCurrent_RailB.addItem("")
        self.comboBox_PhaseOverCurrent_RailB.addItem("")
        self.comboBox_PhaseOverCurrent_RailB.addItem("")
        self.comboBox_PhaseOverCurrent_RailB.addItem("")
        self.comboBox_PhaseOverCurrent_RailB.addItem("")
        self.comboBox_PhaseOverCurrent_RailB.addItem("")
        self.comboBox_PhaseOverCurrent_RailB.addItem("")
        self.comboBox_PhaseOverCurrent_RailB.addItem("")
        self.comboBox_PhaseOverCurrent_RailB.addItem("")
        self.comboBox_AbsoluteOVP_RailB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_AbsoluteOVP_RailB.setGeometry(QtCore.QRect(695, 400, 81, 25))
        self.comboBox_AbsoluteOVP_RailB.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_AbsoluteOVP_RailB.setObjectName("comboBox_AbsoluteOVP_RailB")
        self.comboBox_AbsoluteOVP_RailB.addItem("")
        self.comboBox_AbsoluteOVP_RailB.addItem("")
        self.comboBox_AbsoluteOVP_RailB.addItem("")
        self.comboBox_AbsoluteOVP_RailB.addItem("")
        self.comboBox_AbsoluteOVP_RailB.addItem("")
        self.comboBox_AbsoluteOVP_RailB.addItem("")
        self.comboBox_AbsoluteOVP_RailB.addItem("")
        self.comboBox_AbsoluteOVP_RailB.addItem("")
        self.comboBox_voutTurnOnTime_RailB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_voutTurnOnTime_RailB.setGeometry(QtCore.QRect(695, 440, 81, 25))
        self.comboBox_voutTurnOnTime_RailB.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_voutTurnOnTime_RailB.setObjectName("comboBox_voutTurnOnTime_RailB")
        self.comboBox_voutTurnOnTime_RailB.addItem("")
        self.comboBox_voutTurnOnTime_RailB.addItem("")
        self.comboBox_voutTurnOnTime_RailB.addItem("")
        self.comboBox_voutTurnOnTime_RailB.addItem("")
        self.label_RailA_7 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_7.setGeometry(QtCore.QRect(50, 150, 250, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_7.setFont(font)
        self.label_RailA_7.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_7.setObjectName("label_RailA_7")
        self.label_RailA_32 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_32.setGeometry(QtCore.QRect(440, 150, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_32.setFont(font)
        self.label_RailA_32.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_32.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_32.setObjectName("label_RailA_32")
        self.comboBox_vin_UVP = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vin_UVP.setGeometry(QtCore.QRect(610, 150, 80, 25))
        self.comboBox_vin_UVP.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vin_UVP.setObjectName("comboBox_vin_UVP")
        self.comboBox_vin_UVP.addItem("")
        self.comboBox_vin_UVP.addItem("")
        self.comboBox_vin_UVP.addItem("")
        self.comboBox_vin_UVP.addItem("")
        self.comboBox_vin_UVP.addItem("")
        self.comboBox_vin_UVP.addItem("")
        self.comboBox_vin_UVP.addItem("")
        self.comboBox_vin_UVP.addItem("")
        self.comboBox_vin_UVP.addItem("")
        self.label_RailA_34 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_34.setGeometry(QtCore.QRect(440, 190, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_34.setFont(font)
        self.label_RailA_34.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_34.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_34.setObjectName("label_RailA_34")
        self.comboBox_vin_OVP = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vin_OVP.setGeometry(QtCore.QRect(610, 190, 80, 25))
        self.comboBox_vin_OVP.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vin_OVP.setObjectName("comboBox_vin_OVP")
        self.comboBox_vin_OVP.addItem("")
        self.comboBox_vin_OVP.addItem("")
        self.comboBox_vin_OVP.addItem("")
        self.comboBox_vin_OVP.addItem("")
        self.comboBox_vin_OVP.addItem("")
        self.label_RailA_8 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_8.setGeometry(QtCore.QRect(50, 190, 250, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_8.setFont(font)
        self.label_RailA_8.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_8.setObjectName("label_RailA_8")
        Fault_config.setCentralWidget(self.centralwidget)

        self.retranslateUi(Fault_config)
        QtCore.QMetaObject.connectSlotsByName(Fault_config)

    def retranslateUi(self, Fault_config):
        _translate = QtCore.QCoreApplication.translate
        Fault_config.setWindowTitle(_translate("Fault_config", "Fault"))
        self.label_Transient.setText(_translate("Fault_config", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Fault</span><span style=\" font-size:14pt;\"> Configuration</span></p></body></html>"))
        self.pushButton_Discard.setText(_translate("Fault_config", "Discard"))
        self.pushButton_Save.setText(_translate("Fault_config", "Save"))
        self.label_RailA_3.setText(_translate("Fault_config", "Shutdown Behaviour during Fault"))
        self.label_RailA_4.setText(_translate("Fault_config", "Tracking Under Voltage Protection"))
        self.label_RailA_5.setText(_translate("Fault_config", "Tracking Over Voltage Protection"))
        self.label_RailA_6.setText(_translate("Fault_config", "IOUT Fault Limit"))
        self.label_RailA_12.setText(_translate("Fault_config", "Temperature Fault Threshold"))
        self.comboBox_PhaseOverCurrent_RailA.setItemText(0, _translate("Fault_config", "20A"))
        self.comboBox_PhaseOverCurrent_RailA.setItemText(1, _translate("Fault_config", "24A"))
        self.comboBox_PhaseOverCurrent_RailA.setItemText(2, _translate("Fault_config", "28A"))
        self.comboBox_PhaseOverCurrent_RailA.setItemText(3, _translate("Fault_config", "32A"))
        self.comboBox_PhaseOverCurrent_RailA.setItemText(4, _translate("Fault_config", "36A"))
        self.comboBox_PhaseOverCurrent_RailA.setItemText(5, _translate("Fault_config", "40A"))
        self.comboBox_PhaseOverCurrent_RailA.setItemText(6, _translate("Fault_config", "44A"))
        self.comboBox_PhaseOverCurrent_RailA.setItemText(7, _translate("Fault_config", "48A"))
        self.comboBox_PhaseOverCurrent_RailA.setItemText(8, _translate("Fault_config", "52A"))
        self.comboBox_PhaseOverCurrent_RailA.setItemText(9, _translate("Fault_config", "56A"))
        self.comboBox_PhaseOverCurrent_RailA.setItemText(10, _translate("Fault_config", "60A"))
        self.comboBox_PhaseOverCurrent_RailA.setItemText(11, _translate("Fault_config", "64A"))
        self.comboBox_PhaseOverCurrent_RailA.setItemText(12, _translate("Fault_config", "68A"))
        self.comboBox_PhaseOverCurrent_RailA.setItemText(13, _translate("Fault_config", "72A"))
        self.comboBox_PhaseOverCurrent_RailA.setItemText(14, _translate("Fault_config", "76A"))
        self.comboBox_PhaseOverCurrent_RailA.setItemText(15, _translate("Fault_config", "80A"))
        self.label_display_RailB.setText(_translate("Fault_config", "Beta"))
        self.label_display_RailA.setText(_translate("Fault_config", "Alpha"))
        self.label_RailA_15.setText(_translate("Fault_config", "  :  "))
        self.label_RailA_26.setText(_translate("Fault_config", "  :             "))
        self.label_RailA_28.setText(_translate("Fault_config", "  :             "))
        self.label_RailA_29.setText(_translate("Fault_config", "  :             "))
        self.label_RailA_30.setText(_translate("Fault_config", "  :             "))
        self.label_RailA_31.setText(_translate("Fault_config", "  :             "))
        self.comboBox_temp_fault_threshold.setItemText(0, _translate("Fault_config", "110% of TEMPMAX"))
        self.comboBox_temp_fault_threshold.setItemText(1, _translate("Fault_config", "115% of TEMPMAX"))
        self.comboBox_temp_fault_threshold.setItemText(2, _translate("Fault_config", "120% of TEMPMAX"))
        self.comboBox_temp_fault_threshold.setItemText(3, _translate("Fault_config", "125% of TEMPMAX"))
        self.comboBox_trackingUVP_RailA.setItemText(0, _translate("Fault_config", "Disabled"))
        self.comboBox_trackingUVP_RailA.setItemText(1, _translate("Fault_config", "100mV"))
        self.comboBox_trackingUVP_RailA.setItemText(2, _translate("Fault_config", "150mV"))
        self.comboBox_trackingUVP_RailA.setItemText(3, _translate("Fault_config", "200mV"))
        self.comboBox_trackingUVP_RailA.setItemText(4, _translate("Fault_config", "250mV"))
        self.comboBox_trackingUVP_RailA.setItemText(5, _translate("Fault_config", "300mV"))
        self.comboBox_trackingUVP_RailA.setItemText(6, _translate("Fault_config", "350mV"))
        self.comboBox_trackingUVP_RailA.setItemText(7, _translate("Fault_config", "400mV"))
        self.label_RailA_13.setText(_translate("Fault_config", "Phase Over Current Limit"))
        self.label_RailA_16.setText(_translate("Fault_config", "Absolute Over Voltage Protection"))
        self.label_RailA_17.setText(_translate("Fault_config", "Max VOUT Turn On Time"))
        self.label_RailA_33.setText(_translate("Fault_config", "  :             "))
        self.label_RailA_35.setText(_translate("Fault_config", "  :             "))
        self.comboBox_AbsoluteOVP_RailA.setItemText(0, _translate("Fault_config", "1.3V"))
        self.comboBox_AbsoluteOVP_RailA.setItemText(1, _translate("Fault_config", "1.5V"))
        self.comboBox_AbsoluteOVP_RailA.setItemText(2, _translate("Fault_config", "1.7V"))
        self.comboBox_AbsoluteOVP_RailA.setItemText(3, _translate("Fault_config", "1.9V"))
        self.comboBox_AbsoluteOVP_RailA.setItemText(4, _translate("Fault_config", "2.1V"))
        self.comboBox_AbsoluteOVP_RailA.setItemText(5, _translate("Fault_config", "2.4V"))
        self.comboBox_AbsoluteOVP_RailA.setItemText(6, _translate("Fault_config", "2.6V"))
        self.comboBox_AbsoluteOVP_RailA.setItemText(7, _translate("Fault_config", "2.8V"))
        self.comboBox_voutTurnOnTime_RailA.setItemText(0, _translate("Fault_config", "Disabled"))
        self.comboBox_voutTurnOnTime_RailA.setItemText(1, _translate("Fault_config", "50 ms"))
        self.comboBox_voutTurnOnTime_RailA.setItemText(2, _translate("Fault_config", "75 ms"))
        self.comboBox_voutTurnOnTime_RailA.setItemText(3, _translate("Fault_config", "100 ms"))
        self.comboBox_iout_fault_limit.setItemText(0, _translate("Fault_config", "110% of ICCMAX"))
        self.comboBox_iout_fault_limit.setItemText(1, _translate("Fault_config", "115% of ICCMAX"))
        self.comboBox_iout_fault_limit.setItemText(2, _translate("Fault_config", "120% of ICCMAX"))
        self.comboBox_iout_fault_limit.setItemText(3, _translate("Fault_config", "125% of ICCMAX"))
        self.radioButton_soft_shutdown.setText(_translate("Fault_config", "Slew controlled shutdown"))
        self.radioButton_immediate_shutdown.setText(_translate("Fault_config", "Immediate shutdown"))
        self.comboBox_trackingUVP_RailB.setItemText(0, _translate("Fault_config", "Disabled"))
        self.comboBox_trackingUVP_RailB.setItemText(1, _translate("Fault_config", "100mV"))
        self.comboBox_trackingUVP_RailB.setItemText(2, _translate("Fault_config", "150mV"))
        self.comboBox_trackingUVP_RailB.setItemText(3, _translate("Fault_config", "200mV"))
        self.comboBox_trackingUVP_RailB.setItemText(4, _translate("Fault_config", "250mV"))
        self.comboBox_trackingUVP_RailB.setItemText(5, _translate("Fault_config", "300mV"))
        self.comboBox_trackingUVP_RailB.setItemText(6, _translate("Fault_config", "350mV"))
        self.comboBox_trackingUVP_RailB.setItemText(7, _translate("Fault_config", "400mV"))
        self.comboBox_trackingOVP_RailA.setItemText(0, _translate("Fault_config", "Disabled"))
        self.comboBox_trackingOVP_RailA.setItemText(1, _translate("Fault_config", "100mV"))
        self.comboBox_trackingOVP_RailA.setItemText(2, _translate("Fault_config", "150mV"))
        self.comboBox_trackingOVP_RailA.setItemText(3, _translate("Fault_config", "200mV"))
        self.comboBox_trackingOVP_RailA.setItemText(4, _translate("Fault_config", "250mV"))
        self.comboBox_trackingOVP_RailA.setItemText(5, _translate("Fault_config", "300mV"))
        self.comboBox_trackingOVP_RailA.setItemText(6, _translate("Fault_config", "350mV"))
        self.comboBox_trackingOVP_RailA.setItemText(7, _translate("Fault_config", "400mV"))
        self.comboBox_trackingOVP_RailB.setItemText(0, _translate("Fault_config", "Disabled"))
        self.comboBox_trackingOVP_RailB.setItemText(1, _translate("Fault_config", "100mV"))
        self.comboBox_trackingOVP_RailB.setItemText(2, _translate("Fault_config", "150mV"))
        self.comboBox_trackingOVP_RailB.setItemText(3, _translate("Fault_config", "200mV"))
        self.comboBox_trackingOVP_RailB.setItemText(4, _translate("Fault_config", "250mV"))
        self.comboBox_trackingOVP_RailB.setItemText(5, _translate("Fault_config", "300mV"))
        self.comboBox_trackingOVP_RailB.setItemText(6, _translate("Fault_config", "350mV"))
        self.comboBox_trackingOVP_RailB.setItemText(7, _translate("Fault_config", "400mV"))
        self.comboBox_PhaseOverCurrent_RailB.setItemText(0, _translate("Fault_config", "20A"))
        self.comboBox_PhaseOverCurrent_RailB.setItemText(1, _translate("Fault_config", "24A"))
        self.comboBox_PhaseOverCurrent_RailB.setItemText(2, _translate("Fault_config", "28A"))
        self.comboBox_PhaseOverCurrent_RailB.setItemText(3, _translate("Fault_config", "32A"))
        self.comboBox_PhaseOverCurrent_RailB.setItemText(4, _translate("Fault_config", "36A"))
        self.comboBox_PhaseOverCurrent_RailB.setItemText(5, _translate("Fault_config", "40A"))
        self.comboBox_PhaseOverCurrent_RailB.setItemText(6, _translate("Fault_config", "44A"))
        self.comboBox_PhaseOverCurrent_RailB.setItemText(7, _translate("Fault_config", "48A"))
        self.comboBox_PhaseOverCurrent_RailB.setItemText(8, _translate("Fault_config", "52A"))
        self.comboBox_PhaseOverCurrent_RailB.setItemText(9, _translate("Fault_config", "56A"))
        self.comboBox_PhaseOverCurrent_RailB.setItemText(10, _translate("Fault_config", "60A"))
        self.comboBox_PhaseOverCurrent_RailB.setItemText(11, _translate("Fault_config", "64A"))
        self.comboBox_PhaseOverCurrent_RailB.setItemText(12, _translate("Fault_config", "68A"))
        self.comboBox_PhaseOverCurrent_RailB.setItemText(13, _translate("Fault_config", "72A"))
        self.comboBox_PhaseOverCurrent_RailB.setItemText(14, _translate("Fault_config", "76A"))
        self.comboBox_PhaseOverCurrent_RailB.setItemText(15, _translate("Fault_config", "80A"))
        self.comboBox_AbsoluteOVP_RailB.setItemText(0, _translate("Fault_config", "1.3V"))
        self.comboBox_AbsoluteOVP_RailB.setItemText(1, _translate("Fault_config", "1.5V"))
        self.comboBox_AbsoluteOVP_RailB.setItemText(2, _translate("Fault_config", "1.7V"))
        self.comboBox_AbsoluteOVP_RailB.setItemText(3, _translate("Fault_config", "1.9V"))
        self.comboBox_AbsoluteOVP_RailB.setItemText(4, _translate("Fault_config", "2.1V"))
        self.comboBox_AbsoluteOVP_RailB.setItemText(5, _translate("Fault_config", "2.4V"))
        self.comboBox_AbsoluteOVP_RailB.setItemText(6, _translate("Fault_config", "2.6V"))
        self.comboBox_AbsoluteOVP_RailB.setItemText(7, _translate("Fault_config", "2.8V"))
        self.comboBox_voutTurnOnTime_RailB.setItemText(0, _translate("Fault_config", "Disabled"))
        self.comboBox_voutTurnOnTime_RailB.setItemText(1, _translate("Fault_config", "50 ms"))
        self.comboBox_voutTurnOnTime_RailB.setItemText(2, _translate("Fault_config", "75 ms"))
        self.comboBox_voutTurnOnTime_RailB.setItemText(3, _translate("Fault_config", "100 ms"))
        self.label_RailA_7.setText(_translate("Fault_config", "VIN Under Voltage Protection"))
        self.label_RailA_32.setText(_translate("Fault_config", "  :             "))
        self.comboBox_vin_UVP.setItemText(0, _translate("Fault_config", "4.25 V"))
        self.comboBox_vin_UVP.setItemText(1, _translate("Fault_config", "4.75 V"))
        self.comboBox_vin_UVP.setItemText(2, _translate("Fault_config", "5.25 V"))
        self.comboBox_vin_UVP.setItemText(3, _translate("Fault_config", "6.25 V"))
        self.comboBox_vin_UVP.setItemText(4, _translate("Fault_config", "7.25 V"))
        self.comboBox_vin_UVP.setItemText(5, _translate("Fault_config", "8.25 V"))
        self.comboBox_vin_UVP.setItemText(6, _translate("Fault_config", "9.25 V"))
        self.comboBox_vin_UVP.setItemText(7, _translate("Fault_config", "10.25 V"))
        self.comboBox_vin_UVP.setItemText(8, _translate("Fault_config", "11.25 V"))
        self.label_RailA_34.setText(_translate("Fault_config", "  :             "))
        self.comboBox_vin_OVP.setItemText(0, _translate("Fault_config", "16 V"))
        self.comboBox_vin_OVP.setItemText(1, _translate("Fault_config", "16.5 V"))
        self.comboBox_vin_OVP.setItemText(2, _translate("Fault_config", "17 V"))
        self.comboBox_vin_OVP.setItemText(3, _translate("Fault_config", "17.5 V"))
        self.comboBox_vin_OVP.setItemText(4, _translate("Fault_config", "18 V"))
        self.label_RailA_8.setText(_translate("Fault_config", "VIN Over Voltage Protection"))

