# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SVID_configuration.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SVID_Configuration(object):
    def setupUi(self, SVID_Configuration):
        SVID_Configuration.setObjectName("SVID_Configuration")
        SVID_Configuration.resize(1042, 734)
        self.centralwidget = QtWidgets.QWidget(SVID_Configuration)
        self.centralwidget.setObjectName("centralwidget")
        self.label_SVID_Configuration = QtWidgets.QLabel(self.centralwidget)
        self.label_SVID_Configuration.setGeometry(QtCore.QRect(10, 0, 1021, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_SVID_Configuration.setFont(font)
        self.label_SVID_Configuration.setStyleSheet("background-color: rgb(38, 23, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_SVID_Configuration.setAlignment(QtCore.Qt.AlignCenter)
        self.label_SVID_Configuration.setObjectName("label_SVID_Configuration")
        self.frame_display = QtWidgets.QFrame(self.centralwidget)
        self.frame_display.setGeometry(QtCore.QRect(10, 40, 1021, 691))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame_display.setFont(font)
        self.frame_display.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_display.setStyleSheet("\n"
"border: 2px solid darkorange;\n"
"border-radius:0px;\n"
"")
        self.frame_display.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_display.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_display.setObjectName("frame_display")
        self.pushButton_Discard = QtWidgets.QPushButton(self.frame_display)
        self.pushButton_Discard.setGeometry(QtCore.QRect(380, 650, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Discard.setFont(font)
        self.pushButton_Discard.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Discard.setStyleSheet("QPushButton{background-color: rgb(219, 100, 17);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid red;\n"
"background-color: orange;\n"
"}\n"
"")
        self.pushButton_Discard.setObjectName("pushButton_Discard")
        self.pushButton_Save = QtWidgets.QPushButton(self.frame_display)
        self.pushButton_Save.setGeometry(QtCore.QRect(550, 650, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Save.setStyleSheet("QPushButton{background-color: rgb(0, 153, 74);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid green;\n"
"background-color:lightgreen;\n"
"}\n"
"")
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.label_RailA_2 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_2.setGeometry(QtCore.QRect(50, 10, 141, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_2.setFont(font)
        self.label_RailA_2.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_2.setObjectName("label_RailA_2")
        self.label_RailA_3 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_3.setGeometry(QtCore.QRect(50, 180, 141, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_3.setFont(font)
        self.label_RailA_3.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_3.setObjectName("label_RailA_3")
        self.label_RailA_4 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_4.setGeometry(QtCore.QRect(50, 285, 131, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_4.setFont(font)
        self.label_RailA_4.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_4.setObjectName("label_RailA_4")
        self.label_RailA_5 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_5.setGeometry(QtCore.QRect(50, 215, 191, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_5.setFont(font)
        self.label_RailA_5.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_5.setObjectName("label_RailA_5")
        self.label_RailA_6 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_6.setGeometry(QtCore.QRect(50, 250, 141, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_6.setFont(font)
        self.label_RailA_6.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_6.setObjectName("label_RailA_6")
        self.label_RailA_7 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_7.setGeometry(QtCore.QRect(620, 50, 121, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_7.setFont(font)
        self.label_RailA_7.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_7.setObjectName("label_RailA_7")
        self.label_RailA_8 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_8.setGeometry(QtCore.QRect(620, 10, 161, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_8.setFont(font)
        self.label_RailA_8.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_8.setObjectName("label_RailA_8")
        self.lineEdit_SVID_address = QtWidgets.QLineEdit(self.frame_display)
        self.lineEdit_SVID_address.setGeometry(QtCore.QRect(330, 10, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_SVID_address.setFont(font)
        self.lineEdit_SVID_address.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_SVID_address.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_SVID_address.setObjectName("lineEdit_SVID_address")
        self.lineEdit_icc_max_railA = QtWidgets.QLineEdit(self.frame_display)
        self.lineEdit_icc_max_railA.setGeometry(QtCore.QRect(300, 250, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_icc_max_railA.setFont(font)
        self.lineEdit_icc_max_railA.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_icc_max_railA.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_icc_max_railA.setObjectName("lineEdit_icc_max_railA")
        self.lineEdit_temp_max = QtWidgets.QLineEdit(self.frame_display)
        self.lineEdit_temp_max.setGeometry(QtCore.QRect(830, 10, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_temp_max.setFont(font)
        self.lineEdit_temp_max.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_temp_max.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_temp_max.setObjectName("lineEdit_temp_max")
        self.lineEdit_vid_max_railA = QtWidgets.QLineEdit(self.frame_display)
        self.lineEdit_vid_max_railA.setGeometry(QtCore.QRect(300, 285, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_vid_max_railA.setFont(font)
        self.lineEdit_vid_max_railA.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_vid_max_railA.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vid_max_railA.setObjectName("lineEdit_vid_max_railA")
        self.label_RailA_10 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_10.setGeometry(QtCore.QRect(240, 10, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_10.setFont(font)
        self.label_RailA_10.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_10.setObjectName("label_RailA_10")
        self.comboBox_svid_protocol_RailA = QtWidgets.QComboBox(self.frame_display)
        self.comboBox_svid_protocol_RailA.setGeometry(QtCore.QRect(310, 180, 81, 25))
        self.comboBox_svid_protocol_RailA.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_svid_protocol_RailA.setObjectName("comboBox_svid_protocol_RailA")
        self.comboBox_svid_protocol_RailA.addItem("")
        self.comboBox_svid_protocol_RailA.addItem("")
        self.comboBox_svid_protocol_RailA.addItem("")
        self.comboBox_svid_protocol_RailB = QtWidgets.QComboBox(self.frame_display)
        self.comboBox_svid_protocol_RailB.setGeometry(QtCore.QRect(430, 180, 81, 25))
        self.comboBox_svid_protocol_RailB.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_svid_protocol_RailB.setObjectName("comboBox_svid_protocol_RailB")
        self.comboBox_svid_protocol_RailB.addItem("")
        self.comboBox_svid_protocol_RailB.addItem("")
        self.comboBox_svid_protocol_RailB.addItem("")
        self.comboBox_all_call_address_RailA = QtWidgets.QComboBox(self.frame_display)
        self.comboBox_all_call_address_RailA.setGeometry(QtCore.QRect(310, 215, 81, 25))
        self.comboBox_all_call_address_RailA.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_all_call_address_RailA.setObjectName("comboBox_all_call_address_RailA")
        self.comboBox_all_call_address_RailA.addItem("")
        self.comboBox_all_call_address_RailA.addItem("")
        self.comboBox_all_call_address_RailA.addItem("")
        self.comboBox_all_call_address_RailA.addItem("")
        self.comboBox_all_call_address_RailB = QtWidgets.QComboBox(self.frame_display)
        self.comboBox_all_call_address_RailB.setGeometry(QtCore.QRect(430, 215, 81, 25))
        self.comboBox_all_call_address_RailB.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_all_call_address_RailB.setObjectName("comboBox_all_call_address_RailB")
        self.comboBox_all_call_address_RailB.addItem("")
        self.comboBox_all_call_address_RailB.addItem("")
        self.comboBox_all_call_address_RailB.addItem("")
        self.comboBox_all_call_address_RailB.addItem("")
        self.lineEdit_icc_max_railB = QtWidgets.QLineEdit(self.frame_display)
        self.lineEdit_icc_max_railB.setGeometry(QtCore.QRect(420, 250, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_icc_max_railB.setFont(font)
        self.lineEdit_icc_max_railB.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_icc_max_railB.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_icc_max_railB.setObjectName("lineEdit_icc_max_railB")
        self.lineEdit_imon_aux = QtWidgets.QLineEdit(self.frame_display)
        self.lineEdit_imon_aux.setGeometry(QtCore.QRect(830, 50, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_imon_aux.setFont(font)
        self.lineEdit_imon_aux.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_imon_aux.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_imon_aux.setObjectName("lineEdit_imon_aux")
        self.lineEdit_vid_max_railB = QtWidgets.QLineEdit(self.frame_display)
        self.lineEdit_vid_max_railB.setGeometry(QtCore.QRect(420, 285, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_vid_max_railB.setFont(font)
        self.lineEdit_vid_max_railB.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_vid_max_railB.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vid_max_railB.setObjectName("lineEdit_vid_max_railB")
        self.label_RailA_9 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_9.setGeometry(QtCore.QRect(50, 50, 131, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_9.setFont(font)
        self.label_RailA_9.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_9.setObjectName("label_RailA_9")
        self.lineEdit_Pin_max = QtWidgets.QLineEdit(self.frame_display)
        self.lineEdit_Pin_max.setGeometry(QtCore.QRect(330, 50, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_Pin_max.setFont(font)
        self.lineEdit_Pin_max.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_Pin_max.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Pin_max.setObjectName("lineEdit_Pin_max")
        self.label_RailA_12 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_12.setGeometry(QtCore.QRect(50, 320, 141, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_12.setFont(font)
        self.label_RailA_12.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_12.setObjectName("label_RailA_12")
        self.comboBox_slewrate_fast_RailA = QtWidgets.QComboBox(self.frame_display)
        self.comboBox_slewrate_fast_RailA.setGeometry(QtCore.QRect(300, 320, 100, 25))
        self.comboBox_slewrate_fast_RailA.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_slewrate_fast_RailA.setObjectName("comboBox_slewrate_fast_RailA")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.comboBox_slewrate_fast_RailA.addItem("")
        self.label_RailA_13 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_13.setGeometry(QtCore.QRect(50, 570, 141, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_13.setFont(font)
        self.label_RailA_13.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_13.setObjectName("label_RailA_13")
        self.comboBox_slew_rate_slow_railA = QtWidgets.QComboBox(self.frame_display)
        self.comboBox_slew_rate_slow_railA.setGeometry(QtCore.QRect(230, 575, 161, 25))
        self.comboBox_slew_rate_slow_railA.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_slew_rate_slow_railA.setObjectName("comboBox_slew_rate_slow_railA")
        self.comboBox_slew_rate_slow_railA.addItem("")
        self.comboBox_slew_rate_slow_railA.addItem("")
        self.comboBox_slew_rate_slow_railA.addItem("")
        self.comboBox_slew_rate_slow_railA.addItem("")
        self.comboBox_slew_rate_slow_railB = QtWidgets.QComboBox(self.frame_display)
        self.comboBox_slew_rate_slow_railB.setGeometry(QtCore.QRect(420, 575, 161, 25))
        self.comboBox_slew_rate_slow_railB.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_slew_rate_slow_railB.setObjectName("comboBox_slew_rate_slow_railB")
        self.comboBox_slew_rate_slow_railB.addItem("")
        self.comboBox_slew_rate_slow_railB.addItem("")
        self.comboBox_slew_rate_slow_railB.addItem("")
        self.comboBox_slew_rate_slow_railB.addItem("")
        self.checkBox_PMBus_override_railA = QtWidgets.QCheckBox(self.frame_display)
        self.checkBox_PMBus_override_railA.setGeometry(QtCore.QRect(270, 370, 130, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_PMBus_override_railA.sizePolicy().hasHeightForWidth())
        self.checkBox_PMBus_override_railA.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.checkBox_PMBus_override_railA.setFont(font)
        self.checkBox_PMBus_override_railA.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_PMBus_override_railA.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.checkBox_PMBus_override_railA.setObjectName("checkBox_PMBus_override_railA")
        self.comboBox_vid_resolution_RailA = QtWidgets.QComboBox(self.frame_display)
        self.comboBox_vid_resolution_RailA.setGeometry(QtCore.QRect(310, 410, 75, 26))
        self.comboBox_vid_resolution_RailA.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vid_resolution_RailA.setObjectName("comboBox_vid_resolution_RailA")
        self.comboBox_vid_resolution_RailA.addItem("")
        self.comboBox_vid_resolution_RailA.addItem("")
        self.comboBox_vid_resolution_RailA.addItem("")
        self.comboBox_vid_resolution_RailB = QtWidgets.QComboBox(self.frame_display)
        self.comboBox_vid_resolution_RailB.setGeometry(QtCore.QRect(430, 410, 75, 25))
        self.comboBox_vid_resolution_RailB.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vid_resolution_RailB.setObjectName("comboBox_vid_resolution_RailB")
        self.comboBox_vid_resolution_RailB.addItem("")
        self.comboBox_vid_resolution_RailB.addItem("")
        self.comboBox_vid_resolution_RailB.addItem("")
        self.label_RailA_16 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_16.setGeometry(QtCore.QRect(50, 460, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_16.setFont(font)
        self.label_RailA_16.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_16.setObjectName("label_RailA_16")
        self.comboBox_vid_sel_pin_resolution_railA = QtWidgets.QComboBox(self.frame_display)
        self.comboBox_vid_sel_pin_resolution_railA.setGeometry(QtCore.QRect(310, 520, 75, 25))
        self.comboBox_vid_sel_pin_resolution_railA.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vid_sel_pin_resolution_railA.setObjectName("comboBox_vid_sel_pin_resolution_railA")
        self.comboBox_vid_sel_pin_resolution_railA.addItem("")
        self.comboBox_vid_sel_pin_resolution_railA.addItem("")
        self.comboBox_vid_sel_pin_resolution_railB = QtWidgets.QComboBox(self.frame_display)
        self.comboBox_vid_sel_pin_resolution_railB.setGeometry(QtCore.QRect(430, 520, 75, 25))
        self.comboBox_vid_sel_pin_resolution_railB.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vid_sel_pin_resolution_railB.setObjectName("comboBox_vid_sel_pin_resolution_railB")
        self.comboBox_vid_sel_pin_resolution_railB.addItem("")
        self.comboBox_vid_sel_pin_resolution_railB.addItem("")
        self.label_DisableA_2 = QtWidgets.QLabel(self.frame_display)
        self.label_DisableA_2.setGeometry(QtCore.QRect(827, 100, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_DisableA_2.setFont(font)
        self.label_DisableA_2.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_DisableA_2.setObjectName("label_DisableA_2")
        self.label_EnableA_2 = QtWidgets.QLabel(self.frame_display)
        self.label_EnableA_2.setGeometry(QtCore.QRect(930, 100, 45, 13))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_EnableA_2.setFont(font)
        self.label_EnableA_2.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_EnableA_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_EnableA_2.setObjectName("label_EnableA_2")
        self.label_RailA_25 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_25.setGeometry(QtCore.QRect(620, 90, 171, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_25.setFont(font)
        self.label_RailA_25.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_25.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_25.setObjectName("label_RailA_25")
        self.pushButton_Enable_imon_aux_PS3 = QtWidgets.QPushButton(self.frame_display)
        self.pushButton_Enable_imon_aux_PS3.setGeometry(QtCore.QRect(875, 83, 51, 51))
        self.pushButton_Enable_imon_aux_PS3.setMouseTracking(True)
        self.pushButton_Enable_imon_aux_PS3.setTabletTracking(True)
        self.pushButton_Enable_imon_aux_PS3.setStyleSheet("QPushButton{\n"
"border-image: url(:/D:/Au4592/Ampsemi/Main Files/GUI_IMAGE/but0.png);\n"
"}\n"
"\n"
"\n"
"QPushButton::hover {\n"
"border-image: url(:/D:/Au4592/Ampsemi/Main Files/GUI_IMAGE/but0_hover.png);\n"
"    }\n"
"")
        self.pushButton_Enable_imon_aux_PS3.setText("")
        self.pushButton_Enable_imon_aux_PS3.setCheckable(True)
        self.pushButton_Enable_imon_aux_PS3.setDefault(True)
        self.pushButton_Enable_imon_aux_PS3.setObjectName("pushButton_Enable_imon_aux_PS3")
        self.frame = QtWidgets.QFrame(self.frame_display)
        self.frame.setGeometry(QtCore.QRect(610, 130, 391, 481))
        self.frame.setStyleSheet("border: 1px solid black;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_PVID_A_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_A_6.setGeometry(QtCore.QRect(80, 390, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_A_6.setFont(font)
        self.lineEdit_PVID_A_6.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_A_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_A_6.setObjectName("lineEdit_PVID_A_6")
        self.label_RailA_18 = QtWidgets.QLabel(self.frame)
        self.label_RailA_18.setGeometry(QtCore.QRect(30, 90, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_18.setFont(font)
        self.label_RailA_18.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_18.setObjectName("label_RailA_18")
        self.lineEdit_PVID_A_7 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_A_7.setGeometry(QtCore.QRect(80, 440, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_A_7.setFont(font)
        self.lineEdit_PVID_A_7.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_A_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_A_7.setObjectName("lineEdit_PVID_A_7")
        self.lineEdit_PVID_B_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_B_6.setGeometry(QtCore.QRect(230, 390, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_B_6.setFont(font)
        self.lineEdit_PVID_B_6.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_B_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_B_6.setObjectName("lineEdit_PVID_B_6")
        self.lineEdit_PVID_A_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_A_3.setGeometry(QtCore.QRect(80, 240, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_A_3.setFont(font)
        self.lineEdit_PVID_A_3.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_A_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_A_3.setObjectName("lineEdit_PVID_A_3")
        self.lineEdit_PVID_B_1 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_B_1.setGeometry(QtCore.QRect(230, 140, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_B_1.setFont(font)
        self.lineEdit_PVID_B_1.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_B_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_B_1.setObjectName("lineEdit_PVID_B_1")
        self.pushButton_Enable_APD_railA = QtWidgets.QPushButton(self.frame)
        self.pushButton_Enable_APD_railA.setGeometry(QtCore.QRect(220, 0, 51, 51))
        self.pushButton_Enable_APD_railA.setMouseTracking(True)
        self.pushButton_Enable_APD_railA.setTabletTracking(True)
        self.pushButton_Enable_APD_railA.setStyleSheet("QPushButton{\n"
"border-image: url(:/D:/Au4592/Ampsemi/Main Files/GUI_IMAGE/but0.png);\n"
"}\n"
"\n"
"\n"
"QPushButton::hover {\n"
"border-image: url(:/D:/Au4592/Ampsemi/Main Files/GUI_IMAGE/but0_hover.png);\n"
"    }\n"
"")
        self.pushButton_Enable_APD_railA.setText("")
        self.pushButton_Enable_APD_railA.setCheckable(True)
        self.pushButton_Enable_APD_railA.setDefault(True)
        self.pushButton_Enable_APD_railA.setObjectName("pushButton_Enable_APD_railA")
        self.label_RailA_20 = QtWidgets.QLabel(self.frame)
        self.label_RailA_20.setGeometry(QtCore.QRect(30, 190, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_20.setFont(font)
        self.label_RailA_20.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_20.setObjectName("label_RailA_20")
        self.lineEdit_PVID_A_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_A_4.setGeometry(QtCore.QRect(80, 290, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_A_4.setFont(font)
        self.lineEdit_PVID_A_4.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_A_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_A_4.setObjectName("lineEdit_PVID_A_4")
        self.lineEdit_PVID_A_0 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_A_0.setGeometry(QtCore.QRect(80, 90, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_A_0.setFont(font)
        self.lineEdit_PVID_A_0.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_A_0.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_A_0.setObjectName("lineEdit_PVID_A_0")
        self.lineEdit_PVID_B_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_B_3.setGeometry(QtCore.QRect(230, 240, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_B_3.setFont(font)
        self.lineEdit_PVID_B_3.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_B_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_B_3.setObjectName("lineEdit_PVID_B_3")
        self.lineEdit_PVID_A_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_A_5.setGeometry(QtCore.QRect(80, 340, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_A_5.setFont(font)
        self.lineEdit_PVID_A_5.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_A_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_A_5.setObjectName("lineEdit_PVID_A_5")
        self.lineEdit_PVID_A_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_A_2.setGeometry(QtCore.QRect(80, 190, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_A_2.setFont(font)
        self.lineEdit_PVID_A_2.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_A_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_A_2.setObjectName("lineEdit_PVID_A_2")
        self.lineEdit_PVID_B_0 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_B_0.setGeometry(QtCore.QRect(230, 90, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_B_0.setFont(font)
        self.lineEdit_PVID_B_0.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_B_0.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_B_0.setObjectName("lineEdit_PVID_B_0")
        self.label_RailA_19 = QtWidgets.QLabel(self.frame)
        self.label_RailA_19.setGeometry(QtCore.QRect(30, 140, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_19.setFont(font)
        self.label_RailA_19.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_19.setObjectName("label_RailA_19")
        self.label_RailA_22 = QtWidgets.QLabel(self.frame)
        self.label_RailA_22.setGeometry(QtCore.QRect(30, 290, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_22.setFont(font)
        self.label_RailA_22.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_22.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_22.setObjectName("label_RailA_22")
        self.lineEdit_PVID_A_1 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_A_1.setGeometry(QtCore.QRect(80, 140, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_A_1.setFont(font)
        self.lineEdit_PVID_A_1.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_A_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_A_1.setObjectName("lineEdit_PVID_A_1")
        self.label_RailA_21 = QtWidgets.QLabel(self.frame)
        self.label_RailA_21.setGeometry(QtCore.QRect(30, 240, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_21.setFont(font)
        self.label_RailA_21.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_21.setObjectName("label_RailA_21")
        self.label_RailA_27 = QtWidgets.QLabel(self.frame)
        self.label_RailA_27.setGeometry(QtCore.QRect(30, 440, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_27.setFont(font)
        self.label_RailA_27.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_27.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_27.setObjectName("label_RailA_27")
        self.label_RailA_24 = QtWidgets.QLabel(self.frame)
        self.label_RailA_24.setGeometry(QtCore.QRect(30, 390, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_24.setFont(font)
        self.label_RailA_24.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_24.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_24.setObjectName("label_RailA_24")
        self.label_RailA_23 = QtWidgets.QLabel(self.frame)
        self.label_RailA_23.setGeometry(QtCore.QRect(30, 340, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_23.setFont(font)
        self.label_RailA_23.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_23.setObjectName("label_RailA_23")
        self.lineEdit_PVID_B_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_B_2.setGeometry(QtCore.QRect(230, 190, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_B_2.setFont(font)
        self.lineEdit_PVID_B_2.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_B_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_B_2.setObjectName("lineEdit_PVID_B_2")
        self.lineEdit_PVID_B_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_B_5.setGeometry(QtCore.QRect(230, 340, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_B_5.setFont(font)
        self.lineEdit_PVID_B_5.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_B_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_B_5.setObjectName("lineEdit_PVID_B_5")
        self.lineEdit_PVID_B_7 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_B_7.setGeometry(QtCore.QRect(230, 440, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_B_7.setFont(font)
        self.lineEdit_PVID_B_7.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_B_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_B_7.setObjectName("lineEdit_PVID_B_7")
        self.lineEdit_PVID_B_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PVID_B_4.setGeometry(QtCore.QRect(230, 290, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_PVID_B_4.setFont(font)
        self.lineEdit_PVID_B_4.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_PVID_B_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PVID_B_4.setObjectName("lineEdit_PVID_B_4")
        self.label_EnableA = QtWidgets.QLabel(self.frame)
        self.label_EnableA.setGeometry(QtCore.QRect(280, 10, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_EnableA.setFont(font)
        self.label_EnableA.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_EnableA.setAlignment(QtCore.Qt.AlignCenter)
        self.label_EnableA.setObjectName("label_EnableA")
        self.label_DisableA = QtWidgets.QLabel(self.frame)
        self.label_DisableA.setGeometry(QtCore.QRect(160, 12, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_DisableA.setFont(font)
        self.label_DisableA.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_DisableA.setObjectName("label_DisableA")
        self.label_RailA_17 = QtWidgets.QLabel(self.frame)
        self.label_RailA_17.setGeometry(QtCore.QRect(40, 10, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_RailA_17.setFont(font)
        self.label_RailA_17.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_17.setObjectName("label_RailA_17")
        self.label_display_RailA = QtWidgets.QLabel(self.frame)
        self.label_display_RailA.setGeometry(QtCore.QRect(100, 50, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_display_RailA.setFont(font)
        self.label_display_RailA.setStyleSheet("border: none;")
        self.label_display_RailA.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_display_RailA.setAlignment(QtCore.Qt.AlignCenter)
        self.label_display_RailA.setObjectName("label_display_RailA")
        self.label_display_RailB = QtWidgets.QLabel(self.frame)
        self.label_display_RailB.setGeometry(QtCore.QRect(240, 50, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_display_RailB.setFont(font)
        self.label_display_RailB.setStyleSheet("border: none;")
        self.label_display_RailB.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_display_RailB.setAlignment(QtCore.Qt.AlignCenter)
        self.label_display_RailB.setObjectName("label_display_RailB")
        self.label_RailA_42 = QtWidgets.QLabel(self.frame)
        self.label_RailA_42.setGeometry(QtCore.QRect(351, 91, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_42.setFont(font)
        self.label_RailA_42.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_42.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_42.setObjectName("label_RailA_42")
        self.label_RailA_43 = QtWidgets.QLabel(self.frame)
        self.label_RailA_43.setGeometry(QtCore.QRect(351, 142, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_43.setFont(font)
        self.label_RailA_43.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_43.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_43.setObjectName("label_RailA_43")
        self.label_RailA_44 = QtWidgets.QLabel(self.frame)
        self.label_RailA_44.setGeometry(QtCore.QRect(351, 198, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_44.setFont(font)
        self.label_RailA_44.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_44.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_44.setObjectName("label_RailA_44")
        self.label_RailA_45 = QtWidgets.QLabel(self.frame)
        self.label_RailA_45.setGeometry(QtCore.QRect(351, 242, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_45.setFont(font)
        self.label_RailA_45.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_45.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_45.setObjectName("label_RailA_45")
        self.label_RailA_46 = QtWidgets.QLabel(self.frame)
        self.label_RailA_46.setGeometry(QtCore.QRect(351, 298, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_46.setFont(font)
        self.label_RailA_46.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_46.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_46.setObjectName("label_RailA_46")
        self.label_RailA_47 = QtWidgets.QLabel(self.frame)
        self.label_RailA_47.setGeometry(QtCore.QRect(351, 348, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_47.setFont(font)
        self.label_RailA_47.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_47.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_47.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_47.setObjectName("label_RailA_47")
        self.label_RailA_48 = QtWidgets.QLabel(self.frame)
        self.label_RailA_48.setGeometry(QtCore.QRect(351, 392, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_48.setFont(font)
        self.label_RailA_48.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_48.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_48.setObjectName("label_RailA_48")
        self.label_RailA_49 = QtWidgets.QLabel(self.frame)
        self.label_RailA_49.setGeometry(QtCore.QRect(351, 442, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_49.setFont(font)
        self.label_RailA_49.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_49.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_49.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_49.setObjectName("label_RailA_49")
        self.label_RailA_50 = QtWidgets.QLabel(self.frame)
        self.label_RailA_50.setGeometry(QtCore.QRect(380, 120, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_50.setFont(font)
        self.label_RailA_50.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_50.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_50.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_50.setObjectName("label_RailA_50")
        self.frame_2 = QtWidgets.QFrame(self.frame_display)
        self.frame_2.setGeometry(QtCore.QRect(30, 360, 551, 201))
        self.frame_2.setStyleSheet("border: 1px solid black;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_pmbus_vid_resolution = QtWidgets.QLabel(self.frame_2)
        self.label_pmbus_vid_resolution.setGeometry(QtCore.QRect(20, 50, 190, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_pmbus_vid_resolution.setFont(font)
        self.label_pmbus_vid_resolution.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_pmbus_vid_resolution.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_pmbus_vid_resolution.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pmbus_vid_resolution.setObjectName("label_pmbus_vid_resolution")
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setGeometry(QtCore.QRect(260, 80, 131, 80))
        self.groupBox.setStyleSheet("border:none;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton_vid_sel_pinA = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_vid_sel_pinA.setGeometry(QtCore.QRect(10, 50, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.radioButton_vid_sel_pinA.setFont(font)
        self.radioButton_vid_sel_pinA.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.radioButton_vid_sel_pinA.setObjectName("radioButton_vid_sel_pinA")
        self.radioButton_internal_registerA = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_internal_registerA.setGeometry(QtCore.QRect(10, 20, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.radioButton_internal_registerA.setFont(font)
        self.radioButton_internal_registerA.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_internal_registerA.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.radioButton_internal_registerA.setObjectName("radioButton_internal_registerA")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_2.setGeometry(QtCore.QRect(400, 80, 120, 80))
        self.groupBox_2.setStyleSheet("border:none;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_internal_registerB = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_internal_registerB.setGeometry(QtCore.QRect(0, 20, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.radioButton_internal_registerB.setFont(font)
        self.radioButton_internal_registerB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_internal_registerB.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.radioButton_internal_registerB.setObjectName("radioButton_internal_registerB")
        self.radioButton_vid_sel_pinB = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_vid_sel_pinB.setGeometry(QtCore.QRect(0, 50, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.radioButton_vid_sel_pinB.setFont(font)
        self.radioButton_vid_sel_pinB.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.radioButton_vid_sel_pinB.setObjectName("radioButton_vid_sel_pinB")
        self.label_display_RailB_2 = QtWidgets.QLabel(self.frame_display)
        self.label_display_RailB_2.setGeometry(QtCore.QRect(420, 140, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_display_RailB_2.setFont(font)
        self.label_display_RailB_2.setStyleSheet("border: none;")
        self.label_display_RailB_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_display_RailB_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_display_RailB_2.setObjectName("label_display_RailB_2")
        self.label_display_RailA_2 = QtWidgets.QLabel(self.frame_display)
        self.label_display_RailA_2.setGeometry(QtCore.QRect(300, 140, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_display_RailA_2.setFont(font)
        self.label_display_RailA_2.setStyleSheet("border: none;")
        self.label_display_RailA_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_display_RailA_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_display_RailA_2.setObjectName("label_display_RailA_2")
        self.label_RailA_32 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_32.setGeometry(QtCore.QRect(241, 480, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_32.setFont(font)
        self.label_RailA_32.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_32.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_32.setObjectName("label_RailA_32")
        self.label_RailA_33 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_33.setGeometry(QtCore.QRect(190, 570, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_33.setFont(font)
        self.label_RailA_33.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_33.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_33.setObjectName("label_RailA_33")
        self.label_RailA_37 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_37.setGeometry(QtCore.QRect(430, 50, 20, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_37.setFont(font)
        self.label_RailA_37.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_37.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_37.setObjectName("label_RailA_37")
        self.label_RailA_38 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_38.setGeometry(QtCore.QRect(520, 250, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_38.setFont(font)
        self.label_RailA_38.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_38.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_38.setObjectName("label_RailA_38")
        self.label_RailA_39 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_39.setGeometry(QtCore.QRect(520, 290, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_39.setFont(font)
        self.label_RailA_39.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_39.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_39.setObjectName("label_RailA_39")
        self.label_RailA_40 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_40.setGeometry(QtCore.QRect(930, 10, 21, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_40.setFont(font)
        self.label_RailA_40.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_40.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_40.setObjectName("label_RailA_40")
        self.label_RailA_41 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_41.setGeometry(QtCore.QRect(930, 50, 20, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_41.setFont(font)
        self.label_RailA_41.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_41.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_41.setObjectName("label_RailA_41")
        self.label_RailA_51 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_51.setGeometry(QtCore.QRect(240, 410, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_51.setFont(font)
        self.label_RailA_51.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_51.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_51.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_51.setObjectName("label_RailA_51")
        self.label_RailA_52 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_52.setGeometry(QtCore.QRect(240, 320, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_52.setFont(font)
        self.label_RailA_52.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_52.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_52.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_52.setObjectName("label_RailA_52")
        self.label_RailA_53 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_53.setGeometry(QtCore.QRect(240, 280, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_53.setFont(font)
        self.label_RailA_53.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_53.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_53.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_53.setObjectName("label_RailA_53")
        self.label_RailA_54 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_54.setGeometry(QtCore.QRect(240, 250, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_54.setFont(font)
        self.label_RailA_54.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_54.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_54.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_54.setObjectName("label_RailA_54")
        self.label_RailA_55 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_55.setGeometry(QtCore.QRect(240, 220, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_55.setFont(font)
        self.label_RailA_55.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_55.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_55.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_55.setObjectName("label_RailA_55")
        self.label_RailA_56 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_56.setGeometry(QtCore.QRect(240, 180, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_56.setFont(font)
        self.label_RailA_56.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_56.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_56.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_56.setObjectName("label_RailA_56")
        self.label_RailA_57 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_57.setGeometry(QtCore.QRect(240, 50, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_57.setFont(font)
        self.label_RailA_57.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_57.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_57.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_57.setObjectName("label_RailA_57")
        self.label_RailA_58 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_58.setGeometry(QtCore.QRect(780, 50, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_58.setFont(font)
        self.label_RailA_58.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_58.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_58.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_58.setObjectName("label_RailA_58")
        self.label_RailA_59 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_59.setGeometry(QtCore.QRect(780, 90, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_59.setFont(font)
        self.label_RailA_59.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_59.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_59.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_59.setObjectName("label_RailA_59")
        self.label_RailA_60 = QtWidgets.QLabel(self.frame_display)
        self.label_RailA_60.setGeometry(QtCore.QRect(780, 10, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_60.setFont(font)
        self.label_RailA_60.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_60.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_60.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_60.setObjectName("label_RailA_60")
        self.checkBox_PMBus_override_railA_2 = QtWidgets.QCheckBox(self.frame_display)
        self.checkBox_PMBus_override_railA_2.setGeometry(QtCore.QRect(420, 370, 130, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_PMBus_override_railA_2.sizePolicy().hasHeightForWidth())
        self.checkBox_PMBus_override_railA_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.checkBox_PMBus_override_railA_2.setFont(font)
        self.checkBox_PMBus_override_railA_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_PMBus_override_railA_2.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.checkBox_PMBus_override_railA_2.setObjectName("checkBox_PMBus_override_railA_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_display)
        self.groupBox_3.setGeometry(QtCore.QRect(120, 80, 331, 61))
        self.groupBox_3.setStyleSheet("border:none;")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_pline = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_pline.setGeometry(QtCore.QRect(20, 20, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.radioButton_pline.setFont(font)
        self.radioButton_pline.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_pline.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.radioButton_pline.setObjectName("radioButton_pline")
        self.radioButton_sline = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_sline.setGeometry(QtCore.QRect(180, 20, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.radioButton_sline.setFont(font)
        self.radioButton_sline.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.radioButton_sline.setObjectName("radioButton_sline")
        self.comboBox_slewrate_fast_RailB = QtWidgets.QComboBox(self.frame_display)
        self.comboBox_slewrate_fast_RailB.setGeometry(QtCore.QRect(420, 320, 100, 25))
        self.comboBox_slewrate_fast_RailB.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_slewrate_fast_RailB.setObjectName("comboBox_slewrate_fast_RailB")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.comboBox_slewrate_fast_RailB.addItem("")
        self.frame_2.raise_()
        self.frame.raise_()
        self.pushButton_Discard.raise_()
        self.pushButton_Save.raise_()
        self.label_RailA_2.raise_()
        self.label_RailA_3.raise_()
        self.label_RailA_4.raise_()
        self.label_RailA_5.raise_()
        self.label_RailA_6.raise_()
        self.label_RailA_7.raise_()
        self.label_RailA_8.raise_()
        self.lineEdit_SVID_address.raise_()
        self.lineEdit_icc_max_railA.raise_()
        self.lineEdit_temp_max.raise_()
        self.lineEdit_vid_max_railA.raise_()
        self.label_RailA_10.raise_()
        self.comboBox_svid_protocol_RailA.raise_()
        self.comboBox_svid_protocol_RailB.raise_()
        self.comboBox_all_call_address_RailA.raise_()
        self.comboBox_all_call_address_RailB.raise_()
        self.lineEdit_icc_max_railB.raise_()
        self.lineEdit_imon_aux.raise_()
        self.lineEdit_vid_max_railB.raise_()
        self.label_RailA_9.raise_()
        self.lineEdit_Pin_max.raise_()
        self.label_RailA_12.raise_()
        self.comboBox_slewrate_fast_RailA.raise_()
        self.label_RailA_13.raise_()
        self.comboBox_slew_rate_slow_railA.raise_()
        self.comboBox_slew_rate_slow_railB.raise_()
        self.checkBox_PMBus_override_railA.raise_()
        self.comboBox_vid_resolution_RailA.raise_()
        self.comboBox_vid_resolution_RailB.raise_()
        self.label_RailA_16.raise_()
        self.comboBox_vid_sel_pin_resolution_railA.raise_()
        self.comboBox_vid_sel_pin_resolution_railB.raise_()
        self.label_DisableA_2.raise_()
        self.label_EnableA_2.raise_()
        self.label_RailA_25.raise_()
        self.pushButton_Enable_imon_aux_PS3.raise_()
        self.label_display_RailB_2.raise_()
        self.label_display_RailA_2.raise_()
        self.label_RailA_32.raise_()
        self.label_RailA_33.raise_()
        self.label_RailA_37.raise_()
        self.label_RailA_38.raise_()
        self.label_RailA_39.raise_()
        self.label_RailA_40.raise_()
        self.label_RailA_41.raise_()
        self.label_RailA_51.raise_()
        self.label_RailA_52.raise_()
        self.label_RailA_53.raise_()
        self.label_RailA_54.raise_()
        self.label_RailA_55.raise_()
        self.label_RailA_56.raise_()
        self.label_RailA_57.raise_()
        self.label_RailA_58.raise_()
        self.label_RailA_59.raise_()
        self.label_RailA_60.raise_()
        self.checkBox_PMBus_override_railA_2.raise_()
        self.groupBox_3.raise_()
        self.comboBox_slewrate_fast_RailB.raise_()
        SVID_Configuration.setCentralWidget(self.centralwidget)

        self.retranslateUi(SVID_Configuration)
        QtCore.QMetaObject.connectSlotsByName(SVID_Configuration)

    def retranslateUi(self, SVID_Configuration):
        _translate = QtCore.QCoreApplication.translate
        SVID_Configuration.setWindowTitle(_translate("SVID_Configuration", "Device Configuration"))
        self.label_SVID_Configuration.setText(_translate("SVID_Configuration", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">SVID</span><span style=\" font-size:14pt;\"> Configuration</span></p></body></html>"))
        self.pushButton_Discard.setText(_translate("SVID_Configuration", "Discard"))
        self.pushButton_Save.setText(_translate("SVID_Configuration", "Save"))
        self.label_RailA_2.setText(_translate("SVID_Configuration", "SVID Address"))
        self.label_RailA_3.setText(_translate("SVID_Configuration", "SVID Protocol"))
        self.label_RailA_4.setText(_translate("SVID_Configuration", "SVID Vid Max"))
        self.label_RailA_5.setText(_translate("SVID_Configuration", "SVID All Call Address"))
        self.label_RailA_6.setText(_translate("SVID_Configuration", "SVID Icc Max"))
        self.label_RailA_7.setText(_translate("SVID_Configuration", "IMON Aux"))
        self.label_RailA_8.setText(_translate("SVID_Configuration", "SVID Temp Max"))
        self.lineEdit_SVID_address.setPlaceholderText(_translate("SVID_Configuration", "A"))
        self.lineEdit_icc_max_railA.setPlaceholderText(_translate("SVID_Configuration", "125"))
        self.lineEdit_temp_max.setPlaceholderText(_translate("SVID_Configuration", "27"))
        self.lineEdit_vid_max_railA.setPlaceholderText(_translate("SVID_Configuration", "1.25"))
        self.label_RailA_10.setText(_translate("SVID_Configuration", "  :         0x"))
        self.comboBox_svid_protocol_RailA.setItemText(0, _translate("SVID_Configuration", "IMVP8"))
        self.comboBox_svid_protocol_RailA.setItemText(1, _translate("SVID_Configuration", "IMVP9"))
        self.comboBox_svid_protocol_RailA.setItemText(2, _translate("SVID_Configuration", "IMVP9.1"))
        self.comboBox_svid_protocol_RailB.setItemText(0, _translate("SVID_Configuration", "IMVP8"))
        self.comboBox_svid_protocol_RailB.setItemText(1, _translate("SVID_Configuration", "IMVP9"))
        self.comboBox_svid_protocol_RailB.setItemText(2, _translate("SVID_Configuration", "IMVP9.1"))
        self.comboBox_all_call_address_RailA.setItemText(0, _translate("SVID_Configuration", "Disabled"))
        self.comboBox_all_call_address_RailA.setItemText(1, _translate("SVID_Configuration", "E"))
        self.comboBox_all_call_address_RailA.setItemText(2, _translate("SVID_Configuration", "F"))
        self.comboBox_all_call_address_RailA.setItemText(3, _translate("SVID_Configuration", "E & F"))
        self.comboBox_all_call_address_RailB.setItemText(0, _translate("SVID_Configuration", "Disabled"))
        self.comboBox_all_call_address_RailB.setItemText(1, _translate("SVID_Configuration", "E"))
        self.comboBox_all_call_address_RailB.setItemText(2, _translate("SVID_Configuration", "F"))
        self.comboBox_all_call_address_RailB.setItemText(3, _translate("SVID_Configuration", "E & F"))
        self.lineEdit_icc_max_railB.setPlaceholderText(_translate("SVID_Configuration", "125"))
        self.lineEdit_imon_aux.setPlaceholderText(_translate("SVID_Configuration", "125"))
        self.lineEdit_vid_max_railB.setPlaceholderText(_translate("SVID_Configuration", "1.25"))
        self.label_RailA_9.setText(_translate("SVID_Configuration", "SVID Pin Max"))
        self.lineEdit_Pin_max.setPlaceholderText(_translate("SVID_Configuration", "125"))
        self.label_RailA_12.setText(_translate("SVID_Configuration", "Slew Rate Fast"))
        self.comboBox_slewrate_fast_RailA.setItemText(0, _translate("SVID_Configuration", "0.12mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(1, _translate("SVID_Configuration", "0.5mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(2, _translate("SVID_Configuration", "1mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(3, _translate("SVID_Configuration", "2.5mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(4, _translate("SVID_Configuration", "5mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(5, _translate("SVID_Configuration", "7.5mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(6, _translate("SVID_Configuration", "10mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(7, _translate("SVID_Configuration", "12.5mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(8, _translate("SVID_Configuration", "15mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(9, _translate("SVID_Configuration", "17.5mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(10, _translate("SVID_Configuration", "20mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(11, _translate("SVID_Configuration", "22.5mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(12, _translate("SVID_Configuration", "25mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(13, _translate("SVID_Configuration", "27.5mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(14, _translate("SVID_Configuration", "30mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(15, _translate("SVID_Configuration", "32.5mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(16, _translate("SVID_Configuration", "35mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(17, _translate("SVID_Configuration", "37.5mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(18, _translate("SVID_Configuration", "40mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(19, _translate("SVID_Configuration", "48mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(20, _translate("SVID_Configuration", "60mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(21, _translate("SVID_Configuration", "80mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(22, _translate("SVID_Configuration", "96mV/μs"))
        self.comboBox_slewrate_fast_RailA.setItemText(23, _translate("SVID_Configuration", "125mV/μs"))
        self.label_RailA_13.setText(_translate("SVID_Configuration", "Slew Rate Slow"))
        self.comboBox_slew_rate_slow_railA.setItemText(0, _translate("SVID_Configuration", "Slew Rate Fast / 16"))
        self.comboBox_slew_rate_slow_railA.setItemText(1, _translate("SVID_Configuration", "Slew Rate Fast / 8"))
        self.comboBox_slew_rate_slow_railA.setItemText(2, _translate("SVID_Configuration", "Slew Rate Fast / 4"))
        self.comboBox_slew_rate_slow_railA.setItemText(3, _translate("SVID_Configuration", "Slew Rate Fast / 2"))
        self.comboBox_slew_rate_slow_railB.setItemText(0, _translate("SVID_Configuration", "Slew Rate Fast / 16"))
        self.comboBox_slew_rate_slow_railB.setItemText(1, _translate("SVID_Configuration", "Slew Rate Fast / 8"))
        self.comboBox_slew_rate_slow_railB.setItemText(2, _translate("SVID_Configuration", "Slew Rate Fast / 4"))
        self.comboBox_slew_rate_slow_railB.setItemText(3, _translate("SVID_Configuration", "Slew Rate Fast / 2"))
        self.checkBox_PMBus_override_railA.setText(_translate("SVID_Configuration", "PMBus Vid override"))
        self.comboBox_vid_resolution_RailA.setItemText(0, _translate("SVID_Configuration", "5mV"))
        self.comboBox_vid_resolution_RailA.setItemText(1, _translate("SVID_Configuration", "6.25mV"))
        self.comboBox_vid_resolution_RailA.setItemText(2, _translate("SVID_Configuration", "10mV"))
        self.comboBox_vid_resolution_RailB.setItemText(0, _translate("SVID_Configuration", "5mV"))
        self.comboBox_vid_resolution_RailB.setItemText(1, _translate("SVID_Configuration", "6.25mV"))
        self.comboBox_vid_resolution_RailB.setItemText(2, _translate("SVID_Configuration", "10mV"))
        self.label_RailA_16.setText(_translate("SVID_Configuration", "Vid Resolution  source"))
        self.comboBox_vid_sel_pin_resolution_railA.setItemText(0, _translate("SVID_Configuration", "5mV"))
        self.comboBox_vid_sel_pin_resolution_railA.setItemText(1, _translate("SVID_Configuration", "10mV"))
        self.comboBox_vid_sel_pin_resolution_railB.setItemText(0, _translate("SVID_Configuration", "5mV"))
        self.comboBox_vid_sel_pin_resolution_railB.setItemText(1, _translate("SVID_Configuration", "10mV"))
        self.label_DisableA_2.setText(_translate("SVID_Configuration", "Disable"))
        self.label_EnableA_2.setText(_translate("SVID_Configuration", "Enable"))
        self.label_RailA_25.setText(_translate("SVID_Configuration", "IMON Aux in PS3"))
        self.lineEdit_PVID_A_6.setPlaceholderText(_translate("SVID_Configuration", "1.25"))
        self.label_RailA_18.setText(_translate("SVID_Configuration", "0  :"))
        self.lineEdit_PVID_A_7.setPlaceholderText(_translate("SVID_Configuration", "1.25"))
        self.lineEdit_PVID_B_6.setPlaceholderText(_translate("SVID_Configuration", "1.25"))
        self.lineEdit_PVID_A_3.setPlaceholderText(_translate("SVID_Configuration", "1.25"))
        self.lineEdit_PVID_B_1.setPlaceholderText(_translate("SVID_Configuration", "1.25"))
        self.label_RailA_20.setText(_translate("SVID_Configuration", "2  :"))
        self.lineEdit_PVID_A_4.setPlaceholderText(_translate("SVID_Configuration", "1.25"))
        self.lineEdit_PVID_A_0.setPlaceholderText(_translate("SVID_Configuration", "1.25"))
        self.lineEdit_PVID_B_3.setPlaceholderText(_translate("SVID_Configuration", "1.25"))
        self.lineEdit_PVID_A_5.setPlaceholderText(_translate("SVID_Configuration", "1.25"))
        self.lineEdit_PVID_A_2.setPlaceholderText(_translate("SVID_Configuration", "1.25"))
        self.lineEdit_PVID_B_0.setPlaceholderText(_translate("SVID_Configuration", "1.25"))
        self.label_RailA_19.setText(_translate("SVID_Configuration", "1  :"))
        self.label_RailA_22.setText(_translate("SVID_Configuration", "4  :"))
        self.lineEdit_PVID_A_1.setPlaceholderText(_translate("SVID_Configuration", "1.25"))
        self.label_RailA_21.setText(_translate("SVID_Configuration", "3  :"))
        self.label_RailA_27.setText(_translate("SVID_Configuration", "7  :"))
        self.label_RailA_24.setText(_translate("SVID_Configuration", "6  :"))
        self.label_RailA_23.setText(_translate("SVID_Configuration", "5  :"))
        self.lineEdit_PVID_B_2.setPlaceholderText(_translate("SVID_Configuration", "1.25"))
        self.lineEdit_PVID_B_5.setPlaceholderText(_translate("SVID_Configuration", "1.25"))
        self.lineEdit_PVID_B_7.setPlaceholderText(_translate("SVID_Configuration", "1.25"))
        self.lineEdit_PVID_B_4.setPlaceholderText(_translate("SVID_Configuration", "1.25"))
        self.label_EnableA.setText(_translate("SVID_Configuration", "Enable"))
        self.label_DisableA.setText(_translate("SVID_Configuration", "Disable"))
        self.label_RailA_17.setText(_translate("SVID_Configuration", "PVID-Table"))
        self.label_display_RailA.setText(_translate("SVID_Configuration", "Alpha"))
        self.label_display_RailB.setText(_translate("SVID_Configuration", "Beta"))
        self.label_RailA_42.setText(_translate("SVID_Configuration", "V"))
        self.label_RailA_43.setText(_translate("SVID_Configuration", "V"))
        self.label_RailA_44.setText(_translate("SVID_Configuration", "V"))
        self.label_RailA_45.setText(_translate("SVID_Configuration", "V"))
        self.label_RailA_46.setText(_translate("SVID_Configuration", "V"))
        self.label_RailA_47.setText(_translate("SVID_Configuration", "V"))
        self.label_RailA_48.setText(_translate("SVID_Configuration", "V"))
        self.label_RailA_49.setText(_translate("SVID_Configuration", "V"))
        self.label_RailA_50.setText(_translate("SVID_Configuration", "V"))
        self.label_pmbus_vid_resolution.setText(_translate("SVID_Configuration", "PMBus Vid resolution"))
        self.radioButton_vid_sel_pinA.setText(_translate("SVID_Configuration", "VID_SEL Pin"))
        self.radioButton_internal_registerA.setText(_translate("SVID_Configuration", "Internal Register"))
        self.radioButton_internal_registerB.setText(_translate("SVID_Configuration", "Internal Register"))
        self.radioButton_vid_sel_pinB.setText(_translate("SVID_Configuration", "VID_SEL Pin"))
        self.label_display_RailB_2.setText(_translate("SVID_Configuration", "Beta"))
        self.label_display_RailA_2.setText(_translate("SVID_Configuration", "Alpha"))
        self.label_RailA_32.setText(_translate("SVID_Configuration", "  :"))
        self.label_RailA_33.setText(_translate("SVID_Configuration", "  : "))
        self.label_RailA_37.setText(_translate("SVID_Configuration", "W"))
        self.label_RailA_38.setText(_translate("SVID_Configuration", "A"))
        self.label_RailA_39.setText(_translate("SVID_Configuration", "V"))
        self.label_RailA_40.setText(_translate("SVID_Configuration", "°C"))
        self.label_RailA_41.setText(_translate("SVID_Configuration", "A"))
        self.label_RailA_51.setText(_translate("SVID_Configuration", "  :"))
        self.label_RailA_52.setText(_translate("SVID_Configuration", "  :"))
        self.label_RailA_53.setText(_translate("SVID_Configuration", "  :"))
        self.label_RailA_54.setText(_translate("SVID_Configuration", "  :"))
        self.label_RailA_55.setText(_translate("SVID_Configuration", "  :"))
        self.label_RailA_56.setText(_translate("SVID_Configuration", "  :"))
        self.label_RailA_57.setText(_translate("SVID_Configuration", "  :"))
        self.label_RailA_58.setText(_translate("SVID_Configuration", "  :"))
        self.label_RailA_59.setText(_translate("SVID_Configuration", "  :"))
        self.label_RailA_60.setText(_translate("SVID_Configuration", "  :"))
        self.checkBox_PMBus_override_railA_2.setText(_translate("SVID_Configuration", "PMBus Vid override"))
        self.radioButton_pline.setText(_translate("SVID_Configuration", "P-line"))
        self.radioButton_sline.setText(_translate("SVID_Configuration", "S-line"))
        self.comboBox_slewrate_fast_RailB.setItemText(0, _translate("SVID_Configuration", "0.12mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(1, _translate("SVID_Configuration", "0.5mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(2, _translate("SVID_Configuration", "1mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(3, _translate("SVID_Configuration", "2.5mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(4, _translate("SVID_Configuration", "5mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(5, _translate("SVID_Configuration", "7.5mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(6, _translate("SVID_Configuration", "10mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(7, _translate("SVID_Configuration", "12.5mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(8, _translate("SVID_Configuration", "15mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(9, _translate("SVID_Configuration", "17.5mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(10, _translate("SVID_Configuration", "20mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(11, _translate("SVID_Configuration", "22.5mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(12, _translate("SVID_Configuration", "25mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(13, _translate("SVID_Configuration", "27.5mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(14, _translate("SVID_Configuration", "30mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(15, _translate("SVID_Configuration", "32.5mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(16, _translate("SVID_Configuration", "35mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(17, _translate("SVID_Configuration", "37.5mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(18, _translate("SVID_Configuration", "40mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(19, _translate("SVID_Configuration", "48mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(20, _translate("SVID_Configuration", "60mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(21, _translate("SVID_Configuration", "80mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(22, _translate("SVID_Configuration", "96mV/μs"))
        self.comboBox_slewrate_fast_RailB.setItemText(23, _translate("SVID_Configuration", "125mV/μs"))
