# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PMBus_custom_commands.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PMBus_custom_commands(object):
    def setupUi(self, PMBus_custom_commands):
        PMBus_custom_commands.setObjectName("PMBus_custom_commands")
        PMBus_custom_commands.resize(1300, 180)
        self.centralwidget = QtWidgets.QWidget(PMBus_custom_commands)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_railA = QtWidgets.QFrame(self.centralwidget)
        self.frame_railA.setGeometry(QtCore.QRect(0, 0, 1301, 181))
        self.frame_railA.setStyleSheet("background-color: rgba(201, 255, 226, 179);")
        self.frame_railA.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_railA.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_railA.setObjectName("frame_railA")
        self.label_3 = QtWidgets.QLabel(self.frame_railA)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1301, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(38, 23, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_35 = QtWidgets.QLabel(self.frame_railA)
        self.label_35.setGeometry(QtCore.QRect(940, 80, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.label_35.setObjectName("label_35")
        self.label_ACK = QtWidgets.QLabel(self.frame_railA)
        self.label_ACK.setGeometry(QtCore.QRect(970, 110, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_ACK.setFont(font)
        self.label_ACK.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_ACK.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(160, 188, 173);\n"
"border-radius:2px;")
        self.label_ACK.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ACK.setObjectName("label_ACK")
        self.lineEdit_Payload = QtWidgets.QLineEdit(self.frame_railA)
        self.lineEdit_Payload.setGeometry(QtCore.QRect(560, 100, 190, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_Payload.setFont(font)
        self.lineEdit_Payload.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_Payload.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Payload.setPlaceholderText("")
        self.lineEdit_Payload.setObjectName("lineEdit_Payload")
        self.label_37 = QtWidgets.QLabel(self.frame_railA)
        self.label_37.setGeometry(QtCore.QRect(539, 110, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.label_37.setObjectName("label_37")
        self.groupBox = QtWidgets.QGroupBox(self.frame_railA)
        self.groupBox.setGeometry(QtCore.QRect(340, 80, 91, 60))
        self.groupBox.setStyleSheet("border:none;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton_railA = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_railA.setGeometry(QtCore.QRect(10, 10, 80, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_railA.setFont(font)
        self.radioButton_railA.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_railA.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.radioButton_railA.setObjectName("radioButton_railA")
        self.radioButton_railB = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_railB.setGeometry(QtCore.QRect(10, 40, 80, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_railB.setFont(font)
        self.radioButton_railB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_railB.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.radioButton_railB.setObjectName("radioButton_railB")
        self.label_30 = QtWidgets.QLabel(self.frame_railA)
        self.label_30.setGeometry(QtCore.QRect(600, 70, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.lineEdit_Received_DATA = QtWidgets.QLineEdit(self.frame_railA)
        self.lineEdit_Received_DATA.setGeometry(QtCore.QRect(1099, 110, 190, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_Received_DATA.setFont(font)
        self.lineEdit_Received_DATA.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_Received_DATA.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Received_DATA.setReadOnly(True)
        self.lineEdit_Received_DATA.setPlaceholderText("")
        self.lineEdit_Received_DATA.setObjectName("lineEdit_Received_DATA")
        self.label_38 = QtWidgets.QLabel(self.frame_railA)
        self.label_38.setGeometry(QtCore.QRect(1070, 120, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.label_38.setObjectName("label_38")
        self.label_31 = QtWidgets.QLabel(self.frame_railA)
        self.label_31.setGeometry(QtCore.QRect(1130, 80, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.pushButton_Discard = QtWidgets.QPushButton(self.frame_railA)
        self.pushButton_Discard.setGeometry(QtCore.QRect(790, 110, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Discard.setFont(font)
        self.pushButton_Discard.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Discard.setStyleSheet("QPushButton{background-color: rgb(219, 100, 17);\n"
"color: rgb(255, 255, 255);\n"
"border:2px;\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid red;\n"
"background-color: orange;\n"
"}\n"
"")
        self.pushButton_Discard.setObjectName("pushButton_Discard")
        self.label_32 = QtWidgets.QLabel(self.frame_railA)
        self.label_32.setGeometry(QtCore.QRect(20, 90, 150, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.label_39 = QtWidgets.QLabel(self.frame_railA)
        self.label_39.setGeometry(QtCore.QRect(180, 90, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.label_39.setObjectName("label_39")
        self.label_33 = QtWidgets.QLabel(self.frame_railA)
        self.label_33.setGeometry(QtCore.QRect(20, 50, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.lineEdit_device_command = QtWidgets.QLineEdit(self.frame_railA)
        self.lineEdit_device_command.setGeometry(QtCore.QRect(200, 45, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_device_command.setFont(font)
        self.lineEdit_device_command.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_device_command.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_device_command.setReadOnly(False)
        self.lineEdit_device_command.setPlaceholderText("")
        self.lineEdit_device_command.setObjectName("lineEdit_device_command")
        self.label_40 = QtWidgets.QLabel(self.frame_railA)
        self.label_40.setGeometry(QtCore.QRect(180, 50, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.label_40.setObjectName("label_40")
        self.label_34 = QtWidgets.QLabel(self.frame_railA)
        self.label_34.setGeometry(QtCore.QRect(340, 50, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_railA)
        self.groupBox_3.setGeometry(QtCore.QRect(440, 80, 61, 60))
        self.groupBox_3.setStyleSheet("border:none;")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_railA_3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_railA_3.setGeometry(QtCore.QRect(0, 10, 61, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_railA_3.setFont(font)
        self.radioButton_railA_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_railA_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.radioButton_railA_3.setObjectName("radioButton_railA_3")
        self.radioButton_railB_3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_railB_3.setGeometry(QtCore.QRect(0, 40, 61, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_railB_3.setFont(font)
        self.radioButton_railB_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_railB_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.radioButton_railB_3.setObjectName("radioButton_railB_3")
        self.label_36 = QtWidgets.QLabel(self.frame_railA)
        self.label_36.setGeometry(QtCore.QRect(30, 130, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.label_36.setObjectName("label_36")
        self.label_command_type = QtWidgets.QLabel(self.frame_railA)
        self.label_command_type.setGeometry(QtCore.QRect(180, 130, 131, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_command_type.setFont(font)
        self.label_command_type.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_command_type.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(160, 188, 173);\n"
"border-radius:2px;")
        self.label_command_type.setText("")
        self.label_command_type.setAlignment(QtCore.Qt.AlignCenter)
        self.label_command_type.setObjectName("label_command_type")
        self.label_device_address = QtWidgets.QLabel(self.frame_railA)
        self.label_device_address.setGeometry(QtCore.QRect(200, 90, 60, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_device_address.setFont(font)
        self.label_device_address.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_device_address.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(160, 188, 173);\n"
"border-radius:2px;")
        self.label_device_address.setText("")
        self.label_device_address.setAlignment(QtCore.Qt.AlignCenter)
        self.label_device_address.setObjectName("label_device_address")
        self.label_size = QtWidgets.QLabel(self.frame_railA)
        self.label_size.setGeometry(QtCore.QRect(455, 45, 60, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_size.setFont(font)
        self.label_size.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_size.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(160, 188, 173);\n"
"border-radius:2px;")
        self.label_size.setText("")
        self.label_size.setAlignment(QtCore.Qt.AlignCenter)
        self.label_size.setObjectName("label_size")
        PMBus_custom_commands.setCentralWidget(self.centralwidget)

        self.retranslateUi(PMBus_custom_commands)
        QtCore.QMetaObject.connectSlotsByName(PMBus_custom_commands)

    def retranslateUi(self, PMBus_custom_commands):
        _translate = QtCore.QCoreApplication.translate
        PMBus_custom_commands.setWindowTitle(_translate("PMBus_custom_commands", "Custom Command"))
        self.label_3.setText(_translate("PMBus_custom_commands", "<html><head/><body><p><span style=\" font-weight:600;\">PMBUS</span>: Command</p></body></html>"))
        self.label_35.setText(_translate("PMBus_custom_commands", "Acknowledgement"))
        self.label_ACK.setText(_translate("PMBus_custom_commands", "ACK"))
        self.label_37.setText(_translate("PMBus_custom_commands", "0x"))
        self.radioButton_railA.setText(_translate("PMBus_custom_commands", "Rail-A"))
        self.radioButton_railB.setText(_translate("PMBus_custom_commands", "Rail-B"))
        self.label_30.setText(_translate("PMBus_custom_commands", "Payload"))
        self.label_38.setText(_translate("PMBus_custom_commands", "0x"))
        self.label_31.setText(_translate("PMBus_custom_commands", "Received Data"))
        self.pushButton_Discard.setText(_translate("PMBus_custom_commands", "SEND"))
        self.label_32.setText(_translate("PMBus_custom_commands", "Device Address :"))
        self.label_39.setText(_translate("PMBus_custom_commands", "0x"))
        self.label_33.setText(_translate("PMBus_custom_commands", "Command          :"))
        self.label_40.setText(_translate("PMBus_custom_commands", "0x"))
        self.label_34.setText(_translate("PMBus_custom_commands", "Size (Bytes)"))
        self.radioButton_railA_3.setText(_translate("PMBus_custom_commands", "Read"))
        self.radioButton_railB_3.setText(_translate("PMBus_custom_commands", "Write"))
        self.label_36.setText(_translate("PMBus_custom_commands", "Command Type  :"))

