# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SVID_custom_commands.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SVID_custom_commands(object):
    def setupUi(self, SVID_custom_commands):
        SVID_custom_commands.setObjectName("SVID_custom_commands")
        SVID_custom_commands.resize(751, 191)
        self.centralwidget = QtWidgets.QWidget(SVID_custom_commands)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_railA = QtWidgets.QFrame(self.centralwidget)
        self.frame_railA.setGeometry(QtCore.QRect(0, 0, 751, 191))
        self.frame_railA.setStyleSheet("background-color: rgba(201, 255, 226, 179);")
        self.frame_railA.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_railA.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_railA.setObjectName("frame_railA")
        self.label_3 = QtWidgets.QLabel(self.frame_railA)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 751, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(38, 23, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.comboBox_SVID_command = QtWidgets.QComboBox(self.frame_railA)
        self.comboBox_SVID_command.setGeometry(QtCore.QRect(10, 120, 120, 25))
        self.comboBox_SVID_command.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_SVID_command.setObjectName("comboBox_SVID_command")
        self.comboBox_SVID_command.addItem("")
        self.comboBox_SVID_command.addItem("")
        self.comboBox_SVID_command.addItem("")
        self.comboBox_SVID_command.addItem("")
        self.comboBox_SVID_command.addItem("")
        self.comboBox_SVID_command.addItem("")
        self.comboBox_SVID_command.addItem("")
        self.comboBox_SVID_command.addItem("")
        self.label_29 = QtWidgets.QLabel(self.frame_railA)
        self.label_29.setGeometry(QtCore.QRect(0, 80, 150, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_35 = QtWidgets.QLabel(self.frame_railA)
        self.label_35.setGeometry(QtCore.QRect(460, 80, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.label_35.setObjectName("label_35")
        self.label_ACK = QtWidgets.QLabel(self.frame_railA)
        self.label_ACK.setGeometry(QtCore.QRect(490, 110, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_ACK.setFont(font)
        self.label_ACK.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_ACK.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(160, 188, 173);\n"
"border-radius:2px;")
        self.label_ACK.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ACK.setObjectName("label_ACK")
        self.lineEdit_Payload = QtWidgets.QLineEdit(self.frame_railA)
        self.lineEdit_Payload.setGeometry(QtCore.QRect(340, 110, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_Payload.setFont(font)
        self.lineEdit_Payload.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_Payload.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Payload.setPlaceholderText("")
        self.lineEdit_Payload.setObjectName("lineEdit_Payload")
        self.label_37 = QtWidgets.QLabel(self.frame_railA)
        self.label_37.setGeometry(QtCore.QRect(319, 120, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.label_37.setObjectName("label_37")
        self.groupBox = QtWidgets.QGroupBox(self.frame_railA)
        self.groupBox.setGeometry(QtCore.QRect(170, 80, 120, 80))
        self.groupBox.setStyleSheet("border:none;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton_railA = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_railA.setGeometry(QtCore.QRect(30, 10, 80, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_railA.setFont(font)
        self.radioButton_railA.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_railA.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.radioButton_railA.setObjectName("radioButton_railA")
        self.radioButton_railB = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_railB.setGeometry(QtCore.QRect(30, 40, 80, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_railB.setFont(font)
        self.radioButton_railB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_railB.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.radioButton_railB.setObjectName("radioButton_railB")
        self.label_30 = QtWidgets.QLabel(self.frame_railA)
        self.label_30.setGeometry(QtCore.QRect(320, 80, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.lineEdit_Received_DATA = QtWidgets.QLineEdit(self.frame_railA)
        self.lineEdit_Received_DATA.setGeometry(QtCore.QRect(640, 110, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_Received_DATA.setFont(font)
        self.lineEdit_Received_DATA.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_Received_DATA.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Received_DATA.setReadOnly(True)
        self.lineEdit_Received_DATA.setPlaceholderText("")
        self.lineEdit_Received_DATA.setObjectName("lineEdit_Received_DATA")
        self.label_38 = QtWidgets.QLabel(self.frame_railA)
        self.label_38.setGeometry(QtCore.QRect(619, 120, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.label_38.setObjectName("label_38")
        self.label_31 = QtWidgets.QLabel(self.frame_railA)
        self.label_31.setGeometry(QtCore.QRect(620, 80, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.pushButton_Discard = QtWidgets.QPushButton(self.frame_railA)
        self.pushButton_Discard.setGeometry(QtCore.QRect(340, 160, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Discard.setFont(font)
        self.pushButton_Discard.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Discard.setStyleSheet("QPushButton{background-color: rgb(219, 100, 17);\n"
"color: rgb(255, 255, 255);\n"
"border:2px;\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid red;\n"
"background-color: orange;\n"
"}\n"
"")
        self.pushButton_Discard.setObjectName("pushButton_Discard")
        self.label_3.raise_()
        self.comboBox_SVID_command.raise_()
        self.label_35.raise_()
        self.label_ACK.raise_()
        self.lineEdit_Payload.raise_()
        self.label_37.raise_()
        self.label_29.raise_()
        self.groupBox.raise_()
        self.label_30.raise_()
        self.lineEdit_Received_DATA.raise_()
        self.label_38.raise_()
        self.label_31.raise_()
        self.pushButton_Discard.raise_()
        SVID_custom_commands.setCentralWidget(self.centralwidget)

        self.retranslateUi(SVID_custom_commands)
        QtCore.QMetaObject.connectSlotsByName(SVID_custom_commands)

    def retranslateUi(self, SVID_custom_commands):
        _translate = QtCore.QCoreApplication.translate
        SVID_custom_commands.setWindowTitle(_translate("SVID_custom_commands", "Custom Command"))
        self.label_3.setText(_translate("SVID_custom_commands", "<html><head/><body><p><span style=\" font-weight:600;\">SVID</span>: Command</p></body></html>"))
        self.comboBox_SVID_command.setItemText(0, _translate("SVID_custom_commands", "SetVID Fast"))
        self.comboBox_SVID_command.setItemText(1, _translate("SVID_custom_commands", "SetVID Slow"))
        self.comboBox_SVID_command.setItemText(2, _translate("SVID_custom_commands", "SetVID Decay"))
        self.comboBox_SVID_command.setItemText(3, _translate("SVID_custom_commands", "SetPS"))
        self.comboBox_SVID_command.setItemText(4, _translate("SVID_custom_commands", "SetRegAddr"))
        self.comboBox_SVID_command.setItemText(5, _translate("SVID_custom_commands", "SetRegData"))
        self.comboBox_SVID_command.setItemText(6, _translate("SVID_custom_commands", "GetReg"))
        self.comboBox_SVID_command.setItemText(7, _translate("SVID_custom_commands", "SetWP"))
        self.label_29.setText(_translate("SVID_custom_commands", "Commands"))
        self.label_35.setText(_translate("SVID_custom_commands", "Acknowledgement"))
        self.label_ACK.setText(_translate("SVID_custom_commands", "ACK"))
        self.label_37.setText(_translate("SVID_custom_commands", "0x"))
        self.radioButton_railA.setText(_translate("SVID_custom_commands", "Rail-A"))
        self.radioButton_railB.setText(_translate("SVID_custom_commands", "Rail-B"))
        self.label_30.setText(_translate("SVID_custom_commands", "Payload"))
        self.label_38.setText(_translate("SVID_custom_commands", "0x"))
        self.label_31.setText(_translate("SVID_custom_commands", "Received Data"))
        self.pushButton_Discard.setText(_translate("SVID_custom_commands", "SEND"))

