# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Telemetry_calibration.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Telemetry_calibration(object):
    def setupUi(self, Telemetry_calibration):
        Telemetry_calibration.setObjectName("Telemetry_calibration")
        Telemetry_calibration.resize(609, 337)
        self.centralwidget = QtWidgets.QWidget(Telemetry_calibration)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Calibration = QtWidgets.QLabel(self.centralwidget)
        self.label_Calibration.setGeometry(QtCore.QRect(10, 0, 591, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_Calibration.setFont(font)
        self.label_Calibration.setStyleSheet("background-color: rgb(38, 23, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_Calibration.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Calibration.setObjectName("label_Calibration")
        self.frame_phase_display = QtWidgets.QFrame(self.centralwidget)
        self.frame_phase_display.setGeometry(QtCore.QRect(10, 45, 591, 281))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame_phase_display.setFont(font)
        self.frame_phase_display.setStyleSheet("\n"
"border: 2px solid darkorange;\n"
"border-radius:0px;\n"
"")
        self.frame_phase_display.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_phase_display.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_phase_display.setObjectName("frame_phase_display")
        self.pushButton_Discard = QtWidgets.QPushButton(self.frame_phase_display)
        self.pushButton_Discard.setGeometry(QtCore.QRect(160, 200, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Discard.setFont(font)
        self.pushButton_Discard.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Discard.setStyleSheet("QPushButton{background-color: rgb(219, 100, 17);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid red;\n"
"background-color: orange;\n"
"}\n"
"")
        self.pushButton_Discard.setObjectName("pushButton_Discard")
        self.pushButton_Save = QtWidgets.QPushButton(self.frame_phase_display)
        self.pushButton_Save.setGeometry(QtCore.QRect(320, 200, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Save.setStyleSheet("QPushButton{background-color: rgb(0, 153, 74);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid green;\n"
"background-color:lightgreen;\n"
"}\n"
"")
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.lineEdit_iout_offset_railB = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_iout_offset_railB.setGeometry(QtCore.QRect(420, 110, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_iout_offset_railB.setFont(font)
        self.lineEdit_iout_offset_railB.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_iout_offset_railB.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_iout_offset_railB.setObjectName("lineEdit_iout_offset_railB")
        self.label_RailA_54 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_54.setGeometry(QtCore.QRect(240, 75, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_54.setFont(font)
        self.label_RailA_54.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_54.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_54.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_54.setObjectName("label_RailA_54")
        self.label_RailA_6 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_6.setGeometry(QtCore.QRect(50, 75, 141, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_6.setFont(font)
        self.label_RailA_6.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_6.setObjectName("label_RailA_6")
        self.label_RailA_38 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_38.setGeometry(QtCore.QRect(510, 80, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_38.setFont(font)
        self.label_RailA_38.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_38.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_38.setObjectName("label_RailA_38")
        self.lineEdit_iout_gain_railA = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_iout_gain_railA.setGeometry(QtCore.QRect(300, 75, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_iout_gain_railA.setFont(font)
        self.lineEdit_iout_gain_railA.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_iout_gain_railA.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_iout_gain_railA.setObjectName("lineEdit_iout_gain_railA")
        self.label_RailA_39 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_39.setGeometry(QtCore.QRect(520, 115, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_39.setFont(font)
        self.label_RailA_39.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_39.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_39.setObjectName("label_RailA_39")
        self.lineEdit_iout_offset_railA = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_iout_offset_railA.setGeometry(QtCore.QRect(300, 110, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_iout_offset_railA.setFont(font)
        self.lineEdit_iout_offset_railA.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_iout_offset_railA.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_iout_offset_railA.setObjectName("lineEdit_iout_offset_railA")
        self.lineEdit_iout_gain_railB = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_iout_gain_railB.setGeometry(QtCore.QRect(420, 75, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_iout_gain_railB.setFont(font)
        self.lineEdit_iout_gain_railB.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_iout_gain_railB.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_iout_gain_railB.setObjectName("lineEdit_iout_gain_railB")
        self.label_RailA_53 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_53.setGeometry(QtCore.QRect(240, 105, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_53.setFont(font)
        self.label_RailA_53.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_53.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_53.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_53.setObjectName("label_RailA_53")
        self.label_RailA_4 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_4.setGeometry(QtCore.QRect(50, 110, 131, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_4.setFont(font)
        self.label_RailA_4.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_4.setObjectName("label_RailA_4")
        self.label_display_RailB = QtWidgets.QLabel(self.frame_phase_display)
        self.label_display_RailB.setGeometry(QtCore.QRect(420, 30, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_display_RailB.setFont(font)
        self.label_display_RailB.setStyleSheet("border: none;")
        self.label_display_RailB.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_display_RailB.setAlignment(QtCore.Qt.AlignCenter)
        self.label_display_RailB.setObjectName("label_display_RailB")
        self.label_display_RailA = QtWidgets.QLabel(self.frame_phase_display)
        self.label_display_RailA.setGeometry(QtCore.QRect(300, 30, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_display_RailA.setFont(font)
        self.label_display_RailA.setStyleSheet("border: none;")
        self.label_display_RailA.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_display_RailA.setAlignment(QtCore.Qt.AlignCenter)
        self.label_display_RailA.setObjectName("label_display_RailA")
        Telemetry_calibration.setCentralWidget(self.centralwidget)

        self.retranslateUi(Telemetry_calibration)
        QtCore.QMetaObject.connectSlotsByName(Telemetry_calibration)

    def retranslateUi(self, Telemetry_calibration):
        _translate = QtCore.QCoreApplication.translate
        Telemetry_calibration.setWindowTitle(_translate("Telemetry_calibration", "Telemetry"))
        self.label_Calibration.setText(_translate("Telemetry_calibration", "<html><head/><body><p><span style=\" font-size:14pt;\">Calibration </span></p></body></html>"))
        self.pushButton_Discard.setText(_translate("Telemetry_calibration", "Discard"))
        self.pushButton_Save.setText(_translate("Telemetry_calibration", "Save"))
        self.lineEdit_iout_offset_railB.setPlaceholderText(_translate("Telemetry_calibration", "10"))
        self.label_RailA_54.setText(_translate("Telemetry_calibration", "  :"))
        self.label_RailA_6.setText(_translate("Telemetry_calibration", "IOUT Gain"))
        self.label_RailA_38.setText(_translate("Telemetry_calibration", "x"))
        self.lineEdit_iout_gain_railA.setPlaceholderText(_translate("Telemetry_calibration", "1.25"))
        self.label_RailA_39.setText(_translate("Telemetry_calibration", "A"))
        self.lineEdit_iout_offset_railA.setPlaceholderText(_translate("Telemetry_calibration", "-1"))
        self.lineEdit_iout_gain_railB.setPlaceholderText(_translate("Telemetry_calibration", "0.25"))
        self.label_RailA_53.setText(_translate("Telemetry_calibration", "  :"))
        self.label_RailA_4.setText(_translate("Telemetry_calibration", "IOUT Offset"))
        self.label_display_RailB.setText(_translate("Telemetry_calibration", "Beta"))
        self.label_display_RailA.setText(_translate("Telemetry_calibration", "Alpha"))

