# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logger_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(678, 108)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Logger_frame = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Logger_frame.setGeometry(QtCore.QRect(0, 10, 671, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Logger_frame.setFont(font)
        self.Logger_frame.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"border-radius: 10px;")
        self.Logger_frame.setTabChangesFocus(True)
        self.Logger_frame.setReadOnly(True)
        self.Logger_frame.setObjectName("Logger_frame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Logger_frame.setPlaceholderText(_translate("MainWindow", "Place Holder Text"))
