# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PMBus_Configuration.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PMBus_configuration_main_window(object):
    def setupUi(self, PMBus_configuration_main_window):
        PMBus_configuration_main_window.setObjectName("PMBus_configuration_main_window")
        PMBus_configuration_main_window.resize(602, 670)
        self.centralwidget = QtWidgets.QWidget(PMBus_configuration_main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label_main_PMBus_Configuration = QtWidgets.QLabel(self.centralwidget)
        self.label_main_PMBus_Configuration.setGeometry(QtCore.QRect(10, 0, 581, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_main_PMBus_Configuration.setFont(font)
        self.label_main_PMBus_Configuration.setStyleSheet("background-color: rgb(38, 23, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_main_PMBus_Configuration.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main_PMBus_Configuration.setObjectName("label_main_PMBus_Configuration")
        self.frame_phase_display = QtWidgets.QFrame(self.centralwidget)
        self.frame_phase_display.setGeometry(QtCore.QRect(10, 40, 581, 621))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame_phase_display.setFont(font)
        self.frame_phase_display.setStyleSheet("\n"
"border: 2px solid darkorange;\n"
"border-radius:0px;\n"
"")
        self.frame_phase_display.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_phase_display.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_phase_display.setObjectName("frame_phase_display")
        self.pushButton_Discard = QtWidgets.QPushButton(self.frame_phase_display)
        self.pushButton_Discard.setGeometry(QtCore.QRect(140, 570, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Discard.setFont(font)
        self.pushButton_Discard.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Discard.setStyleSheet("QPushButton{background-color: rgb(219, 100, 17);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid red;\n"
"background-color: orange;\n"
"}\n"
"")
        self.pushButton_Discard.setObjectName("pushButton_Discard")
        self.pushButton_Save = QtWidgets.QPushButton(self.frame_phase_display)
        self.pushButton_Save.setGeometry(QtCore.QRect(310, 570, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Save.setStyleSheet("QPushButton{background-color: rgb(0, 153, 74);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid green;\n"
"background-color:lightgreen;\n"
"}\n"
"")
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.label_RailA_3 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_3.setGeometry(QtCore.QRect(40, 150, 181, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_3.setFont(font)
        self.label_RailA_3.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_3.setObjectName("label_RailA_3")
        self.label_RailA_4 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_4.setGeometry(QtCore.QRect(40, 270, 201, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_4.setFont(font)
        self.label_RailA_4.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_4.setObjectName("label_RailA_4")
        self.label_RailA_5 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_5.setGeometry(QtCore.QRect(40, 190, 191, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_5.setFont(font)
        self.label_RailA_5.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_5.setObjectName("label_RailA_5")
        self.label_RailA_6 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_6.setGeometry(QtCore.QRect(40, 230, 201, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_6.setFont(font)
        self.label_RailA_6.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_6.setObjectName("label_RailA_6")
        self.lineEdit_vout_trim_railA = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_vout_trim_railA.setGeometry(QtCore.QRect(300, 195, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_vout_trim_railA.setFont(font)
        self.lineEdit_vout_trim_railA.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_vout_trim_railA.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vout_trim_railA.setPlaceholderText("")
        self.lineEdit_vout_trim_railA.setObjectName("lineEdit_vout_trim_railA")
        self.comboBox_address_selection_mode = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_address_selection_mode.setGeometry(QtCore.QRect(330, 20, 140, 25))
        self.comboBox_address_selection_mode.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_address_selection_mode.setObjectName("comboBox_address_selection_mode")
        self.comboBox_address_selection_mode.addItem("")
        self.comboBox_address_selection_mode.addItem("")
        self.lineEdit_vout_trim_railB = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_vout_trim_railB.setGeometry(QtCore.QRect(420, 195, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_vout_trim_railB.setFont(font)
        self.lineEdit_vout_trim_railB.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_vout_trim_railB.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vout_trim_railB.setPlaceholderText("")
        self.lineEdit_vout_trim_railB.setObjectName("lineEdit_vout_trim_railB")
        self.label_RailA_12 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_12.setGeometry(QtCore.QRect(40, 310, 211, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_12.setFont(font)
        self.label_RailA_12.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_12.setObjectName("label_RailA_12")
        self.comboBox_ton_delay_RailA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_ton_delay_RailA.setGeometry(QtCore.QRect(310, 430, 75, 25))
        self.comboBox_ton_delay_RailA.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_ton_delay_RailA.setObjectName("comboBox_ton_delay_RailA")
        self.comboBox_ton_delay_RailA.addItem("")
        self.comboBox_ton_delay_RailA.addItem("")
        self.comboBox_ton_delay_RailA.addItem("")
        self.comboBox_ton_delay_RailA.addItem("")
        self.comboBox_ton_delay_RailA.addItem("")
        self.comboBox_ton_delay_RailA.addItem("")
        self.comboBox_ton_delay_RailA.addItem("")
        self.comboBox_ton_delay_RailA.addItem("")
        self.comboBox_freq_switch_RailA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_freq_switch_RailA.setGeometry(QtCore.QRect(300, 510, 90, 25))
        self.comboBox_freq_switch_RailA.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_freq_switch_RailA.setObjectName("comboBox_freq_switch_RailA")
        self.comboBox_freq_switch_RailA.addItem("")
        self.comboBox_freq_switch_RailA.addItem("")
        self.comboBox_freq_switch_RailA.addItem("")
        self.comboBox_freq_switch_RailA.addItem("")
        self.comboBox_freq_switch_RailA.addItem("")
        self.comboBox_freq_switch_RailA.addItem("")
        self.comboBox_freq_switch_RailA.addItem("")
        self.comboBox_freq_switch_RailA.addItem("")
        self.comboBox_freq_switch_RailA.addItem("")
        self.comboBox_freq_switch_RailA.addItem("")
        self.comboBox_freq_switch_RailA.addItem("")
        self.comboBox_freq_switch_RailA.addItem("")
        self.comboBox_freq_switch_RailA.addItem("")
        self.comboBox_freq_switch_RailA.addItem("")
        self.comboBox_freq_switch_RailA.addItem("")
        self.comboBox_freq_switch_RailA.addItem("")
        self.comboBox_freq_switch_RailA.addItem("")
        self.comboBox_freq_switch_RailA.addItem("")
        self.comboBox_freq_switch_RailA.addItem("")
        self.comboBox_freq_switch_RailA.addItem("")
        self.comboBox_vout_mode_RailA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vout_mode_RailA.setGeometry(QtCore.QRect(310, 150, 75, 26))
        self.comboBox_vout_mode_RailA.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vout_mode_RailA.setObjectName("comboBox_vout_mode_RailA")
        self.comboBox_vout_mode_RailA.addItem("")
        self.comboBox_vout_mode_RailA.addItem("")
        self.comboBox_vout_mode_RailA.addItem("")
        self.comboBox_vout_mode_RailB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_vout_mode_RailB.setGeometry(QtCore.QRect(430, 150, 75, 25))
        self.comboBox_vout_mode_RailB.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_vout_mode_RailB.setObjectName("comboBox_vout_mode_RailB")
        self.comboBox_vout_mode_RailB.addItem("")
        self.comboBox_vout_mode_RailB.addItem("")
        self.comboBox_vout_mode_RailB.addItem("")
        self.label_display_RailB = QtWidgets.QLabel(self.frame_phase_display)
        self.label_display_RailB.setGeometry(QtCore.QRect(420, 70, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_display_RailB.setFont(font)
        self.label_display_RailB.setStyleSheet("border: none;")
        self.label_display_RailB.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_display_RailB.setAlignment(QtCore.Qt.AlignCenter)
        self.label_display_RailB.setObjectName("label_display_RailB")
        self.label_display_RailA = QtWidgets.QLabel(self.frame_phase_display)
        self.label_display_RailA.setGeometry(QtCore.QRect(300, 70, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_display_RailA.setFont(font)
        self.label_display_RailA.setStyleSheet("border: none;")
        self.label_display_RailA.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_display_RailA.setAlignment(QtCore.Qt.AlignCenter)
        self.label_display_RailA.setObjectName("label_display_RailA")
        self.label_RailA_15 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_15.setGeometry(QtCore.QRect(260, 150, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_15.setFont(font)
        self.label_RailA_15.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_15.setObjectName("label_RailA_15")
        self.label_RailA_26 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_26.setGeometry(QtCore.QRect(260, 190, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_26.setFont(font)
        self.label_RailA_26.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_26.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_26.setObjectName("label_RailA_26")
        self.label_RailA_28 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_28.setGeometry(QtCore.QRect(260, 230, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_28.setFont(font)
        self.label_RailA_28.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_28.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_28.setObjectName("label_RailA_28")
        self.label_RailA_29 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_29.setGeometry(QtCore.QRect(260, 430, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_29.setFont(font)
        self.label_RailA_29.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_29.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_29.setObjectName("label_RailA_29")
        self.label_RailA_30 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_30.setGeometry(QtCore.QRect(260, 310, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_30.setFont(font)
        self.label_RailA_30.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_30.setObjectName("label_RailA_30")
        self.label_RailA_31 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_31.setGeometry(QtCore.QRect(260, 350, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_31.setFont(font)
        self.label_RailA_31.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_31.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_31.setObjectName("label_RailA_31")
        self.label_RailA_32 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_32.setGeometry(QtCore.QRect(260, 470, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_32.setFont(font)
        self.label_RailA_32.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_32.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_32.setObjectName("label_RailA_32")
        self.label_RailA_39 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_39.setGeometry(QtCore.QRect(520, 200, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_39.setFont(font)
        self.label_RailA_39.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_39.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_39.setObjectName("label_RailA_39")
        self.label_RailA_7 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_7.setGeometry(QtCore.QRect(40, 100, 211, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_7.setFont(font)
        self.label_RailA_7.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_7.setObjectName("label_RailA_7")
        self.label_RailA_17 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_17.setGeometry(QtCore.QRect(260, 100, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_17.setFont(font)
        self.label_RailA_17.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_17.setObjectName("label_RailA_17")
        self.label_RailA_18 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_18.setGeometry(QtCore.QRect(260, 20, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_18.setFont(font)
        self.label_RailA_18.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_18.setObjectName("label_RailA_18")
        self.label_RailA_8 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_8.setGeometry(QtCore.QRect(40, 20, 211, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_8.setFont(font)
        self.label_RailA_8.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_8.setObjectName("label_RailA_8")
        self.label_RailA_14 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_14.setGeometry(QtCore.QRect(40, 350, 211, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_14.setFont(font)
        self.label_RailA_14.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_14.setObjectName("label_RailA_14")
        self.label_RailA_19 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_19.setGeometry(QtCore.QRect(40, 390, 211, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_19.setFont(font)
        self.label_RailA_19.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_19.setObjectName("label_RailA_19")
        self.label_RailA_20 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_20.setGeometry(QtCore.QRect(40, 430, 211, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_20.setFont(font)
        self.label_RailA_20.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_20.setObjectName("label_RailA_20")
        self.label_RailA_21 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_21.setGeometry(QtCore.QRect(40, 470, 141, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_21.setFont(font)
        self.label_RailA_21.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_21.setObjectName("label_RailA_21")
        self.label_RailA_22 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_22.setGeometry(QtCore.QRect(40, 510, 211, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_22.setFont(font)
        self.label_RailA_22.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_22.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RailA_22.setObjectName("label_RailA_22")
        self.label_RailA_16 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_16.setGeometry(QtCore.QRect(260, 390, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_16.setFont(font)
        self.label_RailA_16.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_16.setObjectName("label_RailA_16")
        self.label_RailA_34 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_34.setGeometry(QtCore.QRect(260, 270, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_34.setFont(font)
        self.label_RailA_34.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_34.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_34.setObjectName("label_RailA_34")
        self.label_RailA_35 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_35.setGeometry(QtCore.QRect(260, 510, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RailA_35.setFont(font)
        self.label_RailA_35.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_35.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_35.setObjectName("label_RailA_35")
        self.label_RailA_40 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_40.setGeometry(QtCore.QRect(520, 235, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_40.setFont(font)
        self.label_RailA_40.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_40.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_40.setObjectName("label_RailA_40")
        self.lineEdit_vout_command_railA = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_vout_command_railA.setGeometry(QtCore.QRect(300, 230, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_vout_command_railA.setFont(font)
        self.lineEdit_vout_command_railA.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_vout_command_railA.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vout_command_railA.setPlaceholderText("")
        self.lineEdit_vout_command_railA.setObjectName("lineEdit_vout_command_railA")
        self.lineEdit_vout_command_railB = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_vout_command_railB.setGeometry(QtCore.QRect(420, 230, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_vout_command_railB.setFont(font)
        self.lineEdit_vout_command_railB.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_vout_command_railB.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vout_command_railB.setPlaceholderText("")
        self.lineEdit_vout_command_railB.setObjectName("lineEdit_vout_command_railB")
        self.label_RailA_41 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_41.setGeometry(QtCore.QRect(520, 275, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_41.setFont(font)
        self.label_RailA_41.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_41.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_41.setObjectName("label_RailA_41")
        self.lineEdit_vout_margin_high_railA = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_vout_margin_high_railA.setGeometry(QtCore.QRect(300, 270, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_vout_margin_high_railA.setFont(font)
        self.lineEdit_vout_margin_high_railA.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_vout_margin_high_railA.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vout_margin_high_railA.setPlaceholderText("")
        self.lineEdit_vout_margin_high_railA.setObjectName("lineEdit_vout_margin_high_railA")
        self.lineEdit_vout_margin_high_railB = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_vout_margin_high_railB.setGeometry(QtCore.QRect(420, 270, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_vout_margin_high_railB.setFont(font)
        self.lineEdit_vout_margin_high_railB.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_vout_margin_high_railB.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vout_margin_high_railB.setPlaceholderText("")
        self.lineEdit_vout_margin_high_railB.setObjectName("lineEdit_vout_margin_high_railB")
        self.label_RailA_42 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_42.setGeometry(QtCore.QRect(520, 315, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_42.setFont(font)
        self.label_RailA_42.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_42.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_42.setObjectName("label_RailA_42")
        self.lineEdit_vout_margin_low_railA = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_vout_margin_low_railA.setGeometry(QtCore.QRect(300, 310, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_vout_margin_low_railA.setFont(font)
        self.lineEdit_vout_margin_low_railA.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_vout_margin_low_railA.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vout_margin_low_railA.setPlaceholderText("")
        self.lineEdit_vout_margin_low_railA.setObjectName("lineEdit_vout_margin_low_railA")
        self.lineEdit_vout_margin_low_railB = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_vout_margin_low_railB.setGeometry(QtCore.QRect(420, 310, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_vout_margin_low_railB.setFont(font)
        self.lineEdit_vout_margin_low_railB.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_vout_margin_low_railB.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vout_margin_low_railB.setPlaceholderText("")
        self.lineEdit_vout_margin_low_railB.setObjectName("lineEdit_vout_margin_low_railB")
        self.label_RailA_43 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_43.setGeometry(QtCore.QRect(520, 355, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_43.setFont(font)
        self.label_RailA_43.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_43.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_43.setObjectName("label_RailA_43")
        self.lineEdit_vout_max_railA = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_vout_max_railA.setGeometry(QtCore.QRect(300, 350, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_vout_max_railA.setFont(font)
        self.lineEdit_vout_max_railA.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_vout_max_railA.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vout_max_railA.setPlaceholderText("")
        self.lineEdit_vout_max_railA.setObjectName("lineEdit_vout_max_railA")
        self.lineEdit_vout_max_railB = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_vout_max_railB.setGeometry(QtCore.QRect(420, 350, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_vout_max_railB.setFont(font)
        self.lineEdit_vout_max_railB.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_vout_max_railB.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vout_max_railB.setPlaceholderText("")
        self.lineEdit_vout_max_railB.setObjectName("lineEdit_vout_max_railB")
        self.label_RailA_44 = QtWidgets.QLabel(self.frame_phase_display)
        self.label_RailA_44.setGeometry(QtCore.QRect(520, 395, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_RailA_44.setFont(font)
        self.label_RailA_44.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.label_RailA_44.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_RailA_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RailA_44.setObjectName("label_RailA_44")
        self.lineEdit_vout_min_railA = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_vout_min_railA.setGeometry(QtCore.QRect(300, 390, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_vout_min_railA.setFont(font)
        self.lineEdit_vout_min_railA.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_vout_min_railA.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vout_min_railA.setPlaceholderText("")
        self.lineEdit_vout_min_railA.setObjectName("lineEdit_vout_min_railA")
        self.lineEdit_vout_min_railB = QtWidgets.QLineEdit(self.frame_phase_display)
        self.lineEdit_vout_min_railB.setGeometry(QtCore.QRect(420, 390, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_vout_min_railB.setFont(font)
        self.lineEdit_vout_min_railB.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"border:2px solid  rgb(173, 77, 12);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border:2px solid red;\n"
"    background-color: rgb(255, 173, 101);\n"
"}")
        self.lineEdit_vout_min_railB.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vout_min_railB.setPlaceholderText("")
        self.lineEdit_vout_min_railB.setObjectName("lineEdit_vout_min_railB")
        self.comboBox_ton_delay_RailB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_ton_delay_RailB.setGeometry(QtCore.QRect(430, 430, 75, 25))
        self.comboBox_ton_delay_RailB.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_ton_delay_RailB.setObjectName("comboBox_ton_delay_RailB")
        self.comboBox_ton_delay_RailB.addItem("")
        self.comboBox_ton_delay_RailB.addItem("")
        self.comboBox_ton_delay_RailB.addItem("")
        self.comboBox_ton_delay_RailB.addItem("")
        self.comboBox_ton_delay_RailB.addItem("")
        self.comboBox_ton_delay_RailB.addItem("")
        self.comboBox_ton_delay_RailB.addItem("")
        self.comboBox_ton_delay_RailB.addItem("")
        self.comboBox_toff_delay_RailA = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_toff_delay_RailA.setGeometry(QtCore.QRect(310, 470, 75, 25))
        self.comboBox_toff_delay_RailA.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_toff_delay_RailA.setObjectName("comboBox_toff_delay_RailA")
        self.comboBox_toff_delay_RailA.addItem("")
        self.comboBox_toff_delay_RailA.addItem("")
        self.comboBox_toff_delay_RailA.addItem("")
        self.comboBox_toff_delay_RailA.addItem("")
        self.comboBox_toff_delay_RailA.addItem("")
        self.comboBox_toff_delay_RailA.addItem("")
        self.comboBox_toff_delay_RailA.addItem("")
        self.comboBox_toff_delay_RailA.addItem("")
        self.comboBox_toff_delay_RailB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_toff_delay_RailB.setGeometry(QtCore.QRect(430, 470, 75, 25))
        self.comboBox_toff_delay_RailB.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_toff_delay_RailB.setObjectName("comboBox_toff_delay_RailB")
        self.comboBox_toff_delay_RailB.addItem("")
        self.comboBox_toff_delay_RailB.addItem("")
        self.comboBox_toff_delay_RailB.addItem("")
        self.comboBox_toff_delay_RailB.addItem("")
        self.comboBox_toff_delay_RailB.addItem("")
        self.comboBox_toff_delay_RailB.addItem("")
        self.comboBox_toff_delay_RailB.addItem("")
        self.comboBox_toff_delay_RailB.addItem("")
        self.comboBox_freq_switch_RailB = QtWidgets.QComboBox(self.frame_phase_display)
        self.comboBox_freq_switch_RailB.setGeometry(QtCore.QRect(420, 510, 90, 25))
        self.comboBox_freq_switch_RailB.setStyleSheet("QComboBox{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: black;\n"
"\n"
"    background-color: rgb(151, 188, 168);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:white;\n"
"font:bold;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QListView {\n"
"background-color:lightgreen;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.comboBox_freq_switch_RailB.setObjectName("comboBox_freq_switch_RailB")
        self.comboBox_freq_switch_RailB.addItem("")
        self.comboBox_freq_switch_RailB.addItem("")
        self.comboBox_freq_switch_RailB.addItem("")
        self.comboBox_freq_switch_RailB.addItem("")
        self.comboBox_freq_switch_RailB.addItem("")
        self.comboBox_freq_switch_RailB.addItem("")
        self.comboBox_freq_switch_RailB.addItem("")
        self.comboBox_freq_switch_RailB.addItem("")
        self.comboBox_freq_switch_RailB.addItem("")
        self.comboBox_freq_switch_RailB.addItem("")
        self.comboBox_freq_switch_RailB.addItem("")
        self.comboBox_freq_switch_RailB.addItem("")
        self.comboBox_freq_switch_RailB.addItem("")
        self.comboBox_freq_switch_RailB.addItem("")
        self.comboBox_freq_switch_RailB.addItem("")
        self.comboBox_freq_switch_RailB.addItem("")
        self.comboBox_freq_switch_RailB.addItem("")
        self.comboBox_freq_switch_RailB.addItem("")
        self.comboBox_freq_switch_RailB.addItem("")
        self.comboBox_freq_switch_RailB.addItem("")
        self.checkBox_PMBus_overrideB = QtWidgets.QCheckBox(self.frame_phase_display)
        self.checkBox_PMBus_overrideB.setGeometry(QtCore.QRect(440, 100, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.checkBox_PMBus_overrideB.setFont(font)
        self.checkBox_PMBus_overrideB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_PMBus_overrideB.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.checkBox_PMBus_overrideB.setObjectName("checkBox_PMBus_overrideB")
        self.checkBox_PMBus_override = QtWidgets.QCheckBox(self.frame_phase_display)
        self.checkBox_PMBus_override.setGeometry(QtCore.QRect(320, 100, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.checkBox_PMBus_override.setFont(font)
        self.checkBox_PMBus_override.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_PMBus_override.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);")
        self.checkBox_PMBus_override.setObjectName("checkBox_PMBus_override")
        PMBus_configuration_main_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(PMBus_configuration_main_window)
        QtCore.QMetaObject.connectSlotsByName(PMBus_configuration_main_window)

    def retranslateUi(self, PMBus_configuration_main_window):
        _translate = QtCore.QCoreApplication.translate
        PMBus_configuration_main_window.setWindowTitle(_translate("PMBus_configuration_main_window", "Device Configuration"))
        self.label_main_PMBus_Configuration.setText(_translate("PMBus_configuration_main_window", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">PMBus</span><span style=\" font-size:14pt;\"> Configuration</span></p></body></html>"))
        self.pushButton_Discard.setText(_translate("PMBus_configuration_main_window", "Discard"))
        self.pushButton_Save.setText(_translate("PMBus_configuration_main_window", "Save"))
        self.label_RailA_3.setText(_translate("PMBus_configuration_main_window", "VOUT_MODE "))
        self.label_RailA_4.setText(_translate("PMBus_configuration_main_window", "VOUT_MARGIN_HIGH"))
        self.label_RailA_5.setText(_translate("PMBus_configuration_main_window", "VOUT_TRIM   "))
        self.label_RailA_6.setText(_translate("PMBus_configuration_main_window", "VOUT_COMMAND "))
        self.comboBox_address_selection_mode.setItemText(0, _translate("PMBus_configuration_main_window", "External Resistor"))
        self.comboBox_address_selection_mode.setItemText(1, _translate("PMBus_configuration_main_window", "Internal Register"))
        self.label_RailA_12.setText(_translate("PMBus_configuration_main_window", "VOUT_MARGIN_LOW"))
        self.comboBox_ton_delay_RailA.setItemText(0, _translate("PMBus_configuration_main_window", "0 ms"))
        self.comboBox_ton_delay_RailA.setItemText(1, _translate("PMBus_configuration_main_window", "0.5 ms"))
        self.comboBox_ton_delay_RailA.setItemText(2, _translate("PMBus_configuration_main_window", "1 ms"))
        self.comboBox_ton_delay_RailA.setItemText(3, _translate("PMBus_configuration_main_window", "1.5 ms"))
        self.comboBox_ton_delay_RailA.setItemText(4, _translate("PMBus_configuration_main_window", "2 ms"))
        self.comboBox_ton_delay_RailA.setItemText(5, _translate("PMBus_configuration_main_window", "3 ms"))
        self.comboBox_ton_delay_RailA.setItemText(6, _translate("PMBus_configuration_main_window", "4 ms"))
        self.comboBox_ton_delay_RailA.setItemText(7, _translate("PMBus_configuration_main_window", "5 ms"))
        self.comboBox_freq_switch_RailA.setItemText(0, _translate("PMBus_configuration_main_window", "0.25 MHz"))
        self.comboBox_freq_switch_RailA.setItemText(1, _translate("PMBus_configuration_main_window", "0.5 MHz"))
        self.comboBox_freq_switch_RailA.setItemText(2, _translate("PMBus_configuration_main_window", "0.75 MHz"))
        self.comboBox_freq_switch_RailA.setItemText(3, _translate("PMBus_configuration_main_window", "1 MHz"))
        self.comboBox_freq_switch_RailA.setItemText(4, _translate("PMBus_configuration_main_window", "1.25 MHz"))
        self.comboBox_freq_switch_RailA.setItemText(5, _translate("PMBus_configuration_main_window", "1.5 MHz"))
        self.comboBox_freq_switch_RailA.setItemText(6, _translate("PMBus_configuration_main_window", "1.75 MHz"))
        self.comboBox_freq_switch_RailA.setItemText(7, _translate("PMBus_configuration_main_window", "2 MHz"))
        self.comboBox_freq_switch_RailA.setItemText(8, _translate("PMBus_configuration_main_window", "2.25 MHz"))
        self.comboBox_freq_switch_RailA.setItemText(9, _translate("PMBus_configuration_main_window", "2.5 MHz"))
        self.comboBox_freq_switch_RailA.setItemText(10, _translate("PMBus_configuration_main_window", "2.75 MHz"))
        self.comboBox_freq_switch_RailA.setItemText(11, _translate("PMBus_configuration_main_window", "3 MHz"))
        self.comboBox_freq_switch_RailA.setItemText(12, _translate("PMBus_configuration_main_window", "3.25 MHz"))
        self.comboBox_freq_switch_RailA.setItemText(13, _translate("PMBus_configuration_main_window", "3.5 MHz"))
        self.comboBox_freq_switch_RailA.setItemText(14, _translate("PMBus_configuration_main_window", "3.75 MHz"))
        self.comboBox_freq_switch_RailA.setItemText(15, _translate("PMBus_configuration_main_window", "4 MHz"))
        self.comboBox_freq_switch_RailA.setItemText(16, _translate("PMBus_configuration_main_window", "4.25 MHz"))
        self.comboBox_freq_switch_RailA.setItemText(17, _translate("PMBus_configuration_main_window", "4.5 MHz"))
        self.comboBox_freq_switch_RailA.setItemText(18, _translate("PMBus_configuration_main_window", "4.75 MHz"))
        self.comboBox_freq_switch_RailA.setItemText(19, _translate("PMBus_configuration_main_window", "5 MHz"))
        self.comboBox_vout_mode_RailA.setItemText(0, _translate("PMBus_configuration_main_window", "5mV"))
        self.comboBox_vout_mode_RailA.setItemText(1, _translate("PMBus_configuration_main_window", "6.25mV"))
        self.comboBox_vout_mode_RailA.setItemText(2, _translate("PMBus_configuration_main_window", "10mV"))
        self.comboBox_vout_mode_RailB.setItemText(0, _translate("PMBus_configuration_main_window", "5mV"))
        self.comboBox_vout_mode_RailB.setItemText(1, _translate("PMBus_configuration_main_window", "6.25mV"))
        self.comboBox_vout_mode_RailB.setItemText(2, _translate("PMBus_configuration_main_window", "10mV"))
        self.label_display_RailB.setText(_translate("PMBus_configuration_main_window", "Beta"))
        self.label_display_RailA.setText(_translate("PMBus_configuration_main_window", "Alpha"))
        self.label_RailA_15.setText(_translate("PMBus_configuration_main_window", "  :             "))
        self.label_RailA_26.setText(_translate("PMBus_configuration_main_window", "  :             "))
        self.label_RailA_28.setText(_translate("PMBus_configuration_main_window", "  :             "))
        self.label_RailA_29.setText(_translate("PMBus_configuration_main_window", "  :             "))
        self.label_RailA_30.setText(_translate("PMBus_configuration_main_window", "  :             "))
        self.label_RailA_31.setText(_translate("PMBus_configuration_main_window", "  :             "))
        self.label_RailA_32.setText(_translate("PMBus_configuration_main_window", "  :             "))
        self.label_RailA_39.setText(_translate("PMBus_configuration_main_window", "V"))
        self.label_RailA_7.setText(_translate("PMBus_configuration_main_window", "Enable PMBus Override"))
        self.label_RailA_17.setText(_translate("PMBus_configuration_main_window", "  :             "))
        self.label_RailA_18.setText(_translate("PMBus_configuration_main_window", "  :             "))
        self.label_RailA_8.setText(_translate("PMBus_configuration_main_window", "Address Selection Mode"))
        self.label_RailA_14.setText(_translate("PMBus_configuration_main_window", "VOUT_MAX"))
        self.label_RailA_19.setText(_translate("PMBus_configuration_main_window", "VOUT_MIN"))
        self.label_RailA_20.setText(_translate("PMBus_configuration_main_window", "TON_DELAY"))
        self.label_RailA_21.setText(_translate("PMBus_configuration_main_window", "TOFF_DELAY"))
        self.label_RailA_22.setText(_translate("PMBus_configuration_main_window", "FREQUENCY_SWITCH"))
        self.label_RailA_16.setText(_translate("PMBus_configuration_main_window", "  :             "))
        self.label_RailA_34.setText(_translate("PMBus_configuration_main_window", "  :             "))
        self.label_RailA_35.setText(_translate("PMBus_configuration_main_window", "  :             "))
        self.label_RailA_40.setText(_translate("PMBus_configuration_main_window", "V"))
        self.label_RailA_41.setText(_translate("PMBus_configuration_main_window", "V"))
        self.label_RailA_42.setText(_translate("PMBus_configuration_main_window", "V"))
        self.label_RailA_43.setText(_translate("PMBus_configuration_main_window", "V"))
        self.label_RailA_44.setText(_translate("PMBus_configuration_main_window", "V"))
        self.comboBox_ton_delay_RailB.setItemText(0, _translate("PMBus_configuration_main_window", "0 ms"))
        self.comboBox_ton_delay_RailB.setItemText(1, _translate("PMBus_configuration_main_window", "0.5 ms"))
        self.comboBox_ton_delay_RailB.setItemText(2, _translate("PMBus_configuration_main_window", "1 ms"))
        self.comboBox_ton_delay_RailB.setItemText(3, _translate("PMBus_configuration_main_window", "1.5 ms"))
        self.comboBox_ton_delay_RailB.setItemText(4, _translate("PMBus_configuration_main_window", "2 ms"))
        self.comboBox_ton_delay_RailB.setItemText(5, _translate("PMBus_configuration_main_window", "3 ms"))
        self.comboBox_ton_delay_RailB.setItemText(6, _translate("PMBus_configuration_main_window", "4 ms"))
        self.comboBox_ton_delay_RailB.setItemText(7, _translate("PMBus_configuration_main_window", "5 ms"))
        self.comboBox_toff_delay_RailA.setItemText(0, _translate("PMBus_configuration_main_window", "0 ms"))
        self.comboBox_toff_delay_RailA.setItemText(1, _translate("PMBus_configuration_main_window", "0.5 ms"))
        self.comboBox_toff_delay_RailA.setItemText(2, _translate("PMBus_configuration_main_window", "1 ms"))
        self.comboBox_toff_delay_RailA.setItemText(3, _translate("PMBus_configuration_main_window", "1.5 ms"))
        self.comboBox_toff_delay_RailA.setItemText(4, _translate("PMBus_configuration_main_window", "2 ms"))
        self.comboBox_toff_delay_RailA.setItemText(5, _translate("PMBus_configuration_main_window", "3 ms"))
        self.comboBox_toff_delay_RailA.setItemText(6, _translate("PMBus_configuration_main_window", "4 ms"))
        self.comboBox_toff_delay_RailA.setItemText(7, _translate("PMBus_configuration_main_window", "5 ms"))
        self.comboBox_toff_delay_RailB.setItemText(0, _translate("PMBus_configuration_main_window", "0 ms"))
        self.comboBox_toff_delay_RailB.setItemText(1, _translate("PMBus_configuration_main_window", "0.5 ms"))
        self.comboBox_toff_delay_RailB.setItemText(2, _translate("PMBus_configuration_main_window", "1 ms"))
        self.comboBox_toff_delay_RailB.setItemText(3, _translate("PMBus_configuration_main_window", "1.5 ms"))
        self.comboBox_toff_delay_RailB.setItemText(4, _translate("PMBus_configuration_main_window", "2 ms"))
        self.comboBox_toff_delay_RailB.setItemText(5, _translate("PMBus_configuration_main_window", "3 ms"))
        self.comboBox_toff_delay_RailB.setItemText(6, _translate("PMBus_configuration_main_window", "4 ms"))
        self.comboBox_toff_delay_RailB.setItemText(7, _translate("PMBus_configuration_main_window", "5 ms"))
        self.comboBox_freq_switch_RailB.setItemText(0, _translate("PMBus_configuration_main_window", "0.25 MHz"))
        self.comboBox_freq_switch_RailB.setItemText(1, _translate("PMBus_configuration_main_window", "0.5 MHz"))
        self.comboBox_freq_switch_RailB.setItemText(2, _translate("PMBus_configuration_main_window", "0.75 MHz"))
        self.comboBox_freq_switch_RailB.setItemText(3, _translate("PMBus_configuration_main_window", "1 MHz"))
        self.comboBox_freq_switch_RailB.setItemText(4, _translate("PMBus_configuration_main_window", "1.25 MHz"))
        self.comboBox_freq_switch_RailB.setItemText(5, _translate("PMBus_configuration_main_window", "1.5 MHz"))
        self.comboBox_freq_switch_RailB.setItemText(6, _translate("PMBus_configuration_main_window", "1.75 MHz"))
        self.comboBox_freq_switch_RailB.setItemText(7, _translate("PMBus_configuration_main_window", "2 MHz"))
        self.comboBox_freq_switch_RailB.setItemText(8, _translate("PMBus_configuration_main_window", "2.25 MHz"))
        self.comboBox_freq_switch_RailB.setItemText(9, _translate("PMBus_configuration_main_window", "2.5 MHz"))
        self.comboBox_freq_switch_RailB.setItemText(10, _translate("PMBus_configuration_main_window", "2.75 MHz"))
        self.comboBox_freq_switch_RailB.setItemText(11, _translate("PMBus_configuration_main_window", "3 MHz"))
        self.comboBox_freq_switch_RailB.setItemText(12, _translate("PMBus_configuration_main_window", "3.25 MHz"))
        self.comboBox_freq_switch_RailB.setItemText(13, _translate("PMBus_configuration_main_window", "3.5 MHz"))
        self.comboBox_freq_switch_RailB.setItemText(14, _translate("PMBus_configuration_main_window", "3.75 MHz"))
        self.comboBox_freq_switch_RailB.setItemText(15, _translate("PMBus_configuration_main_window", "4 MHz"))
        self.comboBox_freq_switch_RailB.setItemText(16, _translate("PMBus_configuration_main_window", "4.25 MHz"))
        self.comboBox_freq_switch_RailB.setItemText(17, _translate("PMBus_configuration_main_window", "4.5 MHz"))
        self.comboBox_freq_switch_RailB.setItemText(18, _translate("PMBus_configuration_main_window", "4.75 MHz"))
        self.comboBox_freq_switch_RailB.setItemText(19, _translate("PMBus_configuration_main_window", "5 MHz"))
        self.checkBox_PMBus_overrideB.setText(_translate("PMBus_configuration_main_window", "Vout"))
        self.checkBox_PMBus_override.setText(_translate("PMBus_configuration_main_window", "Vout"))

